### ISSUE TITLE
Blindworm model appears to have some clipping around the head

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#102]
![screenshot 2018-11-21 04 38 18](https://user-images.githubusercontent.com/5614902/48834416-c51ad400-ed4b-11e8-919e-5f93292ca5df.png)

**Comment by cybercat5555** [comment]
In regards to the clipping- that's because the head and the main body segment are actually 2 smaller cubes pushed together to make the illusion of a "middle sized" cube. This issue can be fixed with some texture tweaks
