### ISSUE TITLE
WAWLA descriptions for enchantments

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#104]
This can easily be done via proper localizations, just leaving this up for anyone who wants to do it

**Comment by OtisGoodman** [comment]
Wait, how do I set the descriptions?

**Comment by zabi94** [comment]
The issue description is not clear, I don't even know what that means... Wawla doesn't deal with enchantments...

**Comment by Sunconure11** [comment]
WAWLA adds descriptions to enchantments

**Comment by OtisGoodman** [comment]
but how do I add them?

**Comment by Sunconure11** [comment]
You add them to the localizations file. See other mods examples of WAWLA enchantment descriptions.

**Comment by tcheinen** [comment]
The code that reads it in WAWLA is [here](https://github.com/Darkhax-Minecraft/WAWLA/blob/a3f3cc3e75441ec511d4b4cd5ac39ef896871e0f/src/main/java/net/darkhax/wawla/plugins/generic/PluginEnchantmentDescription.java#L136).  An example of this used in a mod can be found [here](https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/0e0366bd05b9ad56877ac119ff31ea47ef788935/src/main/resources/assets/soulshardstow/lang/en_US.lang#L49).

**Comment by OtisGoodman** [comment]
What do the ward enchantments do?

**Comment by OtisGoodman** [comment]
and Occultation

**Comment by tcheinen** [comment]
Enchantments can be found [here](https://github.com/Um-Mitternacht/Bewitchment/tree/master/src/main/java/com/bewitchment/common/content/enchantments).   The wards will reduce (or nullify) damage and consume mp.  Occultation doesn't do anything right now but if theres a design document you might find it in there.
