### ISSUE TITLE
Toad hit animation plays for all toads

### ISSUE THREAD

**Issue by mjra007** [Um-Mitternacht/Bewitchment#127]
I was told this was a known issue on discord but couldn't find here.

### Expected Behavior
If you hit a toad the animation should only be played for that toad

### Actual Behavior
If you hit a toad all toads in the world will play that animation

### Steps to Reproduce
Simply spawn two toads hit one and both will play the jump animation

### Version of Minecraft, Bewitchment, Forge, and Baubles
1.12.2 - 14.23.5.2796 , Patchouli 1.0.12, Bewitchment 0.0.16

### Logs, in the event of a crash
![](https://media.giphy.com/media/65AORR1JD66PWRlMXe/giphy.gif)

**Comment by Sunconure11** [comment]
Assigning @itsmeow, due to animation expertise.

**Comment by itsmeow** [comment]
Yeah, no `timer` field inside model class. Don't store things in model classes. They are not unique. Working on it- use a datamanager field to sync animation data over network if you MUST.
