### ISSUE TITLE
Showing incorrect power data.

### ISSUE THREAD

**Issue by UnexceptedError** [Um-Mitternacht/Bewitchment#13]
Witch Altar is showing incorrect power data.
Minecraft 1.12.2
Bewitchment 1.12.2-0.0.6

Altar shows:
![screenshot_19](https://user-images.githubusercontent.com/27512754/42277103-e3143728-7f9e-11e8-9b56-718e10097304.png)

Real power (got using /blockdata):
![screenshot_20](https://user-images.githubusercontent.com/27512754/42277155-10f7c268-7f9f-11e8-9184-b5cb2549d6bc.png)

**Comment by zabi94** [comment]
The bug is already known. The whole MP mechanic will be rewritten, so we won't even bother fixing it for now
