### ISSUE TITLE
Neck01achild hell

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#130]
### Expected Behavior
Snakes, blindworms, and uranids should not have these redundant cubes that cause clipping.

### Actual Behavior
Mobs mentioned above do in fact have these redundant cubes

### Steps to Reproduce
Install tabula, use Import from Game to import the snake/uran/blindworm models as they appear in-game. Clicking on the cubes named "neck01aChild - 1" and "neck01aChild - 2" shows the 2 bad cubes, and they can be found on all serpentine models. These cubes have no reason and can be safely deleted without impacting the models, and deleting them fixes the clipping issues.

### Version of Minecraft, Bewitchment, Forge, and Baubles
MC 1.12.2
Bewitchment:  .16 (compiled myself)
Baubles: 1.5.2
Forge: .2796

### Screenshots encouraged
Imgur album link: https://imgur.com/a/b9kA8Nz

If needed I can re-export the 3 models if it will fix the issue

**Comment by Sunconure11** [comment]
Re-export them, if need be

**Comment by Sunconure11** [comment]
![screenshot 2018-12-10 18 36 42](https://user-images.githubusercontent.com/5614902/49768634-fa5f7580-fcaa-11e8-9173-90d369f631a7.png)

Look at the side.

**Comment by Sunconure11** [comment]
![e73b5d6f1994fd238a96d743cf1add73](https://user-images.githubusercontent.com/5614902/49769350-cfc2ec00-fcad-11e8-9d93-3338004bf99a.png)
