### ISSUE TITLE
Crash during game startup

### ISSUE THREAD

**Issue by Yukkioh** [Um-Mitternacht/Bewitchment#131]
[crash-2018-12-10_20.29.06-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2665588/crash-2018-12-10_20.29.06-client.txt)
My game keeps crashing during the startup and i dont know why

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bewitchment (bewitchment)

**Comment by Sunconure11** [comment]
Use Forge 14.23.5.2796.
