### ISSUE TITLE
Right-clicking with a broom (item) causes crashes

### ISSUE THREAD

**Issue by thanasishadow** [Um-Mitternacht/Bewitchment#143]
### Expected Behavior
The broom entity should probably be spawned

### Actual Behavior
Crash

### Steps to Reproduce
Right click with any broom besides the basic one

### Version of Minecraft, Bewitchment, Forge, and Baubles
Minecraft 1.12.2
Bewitchment 0.0.16.5
Forge 14.23.5.2796
Baubles 1.5.2

### Logs, in the event of a crash
https://paste.dimdev.org/jubemufuma.mccrash

### Modlist
https://pastebin.com/gASWsNzX

**Comment by Sunconure11** [comment]
I'm attempting to investigate this now, and it seems brooms do not spawn for me

**Comment by Sunconure11** [comment]
This has been confirmed to be fixed.
