### ISSUE TITLE
Hearts from this mod get renamed if the cannibalism mod is present in a workspace

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#145]
Decided to do some toying around in terms of cross-compat for a future commit, stumbled upon this:

![screenshot 2018-12-18 17 07 01](https://user-images.githubusercontent.com/5614902/50185974-62374100-02e7-11e9-9e9a-e97030bd36b0.png)

**Comment by Sunconure11** [comment]
@SoraZodia by any chance, are you doing anything weird with naming that could cause this? I was toying around with compat in terms of silver being able to target the wendigo from your mod, and ended up finding this bug instead.

**Comment by SoraZodia** [comment]
I would have to look in it, only thing that comes to mind is the player
flesh changing its name to match the player's username

**Comment by Sunconure11** [comment]
@SoraZodia Bug is still present. I have released indev builds to curse, BTW.

**Comment by SoraZodia** [comment]
v5.2.1 should have that bug fixed, my bad for taking this long. 

It was due to our items sharing the same unlocalized name so the last language file to load had its mapping used for those items.
