### ISSUE TITLE
Chisel support is not fully implemented

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#146]
Decided to test our chisel integration, it seems to not be working in the workspace, or at least, wanting to work. Further checking of the code indicates the compat was never fully completed.

**Comment by Sunconure11** [comment]
Mod now builds against chisel. Please rebuild your workspace.

**Comment by itsmeow** [comment]
chisel doesn't work in mod workspaces at all just fyi, tried using it before. has to do with the way it does class calls and such

**Comment by Sunconure11** [comment]
Works fine for me.
