### ISSUE TITLE
Dynamic Surroundings crash

### ISSUE THREAD

**Issue by thenextelement** [Um-Mitternacht/Bewitchment#147]
### Expected Behavior
The game loading normally.

### Actual Behavior
The game is crashing on startup

### Steps to Reproduce
Download bewitchment and all dependencies as well as Dynamics surroundings and its core then launch.

### Version of Minecraft, Bewitchment, Forge, and Baubles
MC 1.12.2,  Bewitchment 0.0.16.6, Forge 14.23.5.2796,  and Baubles  1.12-1.5.2.

### Logs, in the event of a crash
https://pastebin.com/3WMexJjN

**Comment by Sunconure11** [comment]
WTF. @OreCruncher

**Comment by OreCruncher** [comment]
This is more than likely my bad.  The BETA stuff is my WIP for getting DS ready for 1.13.  What is happening is that I am processing a ore dictionary entry, and trying to convert ItemStacks into IBlockStates.  In the majority of cases the subtype of the ItemStack maps to the meta value for the block.  In this case it appears not to be the case thus the blow up.

**Comment by OreCruncher** [comment]
@Sunconure11 Actually you may have a bug as well.  The reason it is choking is that it is processing the "oreAlexandrite" dictionary entries.  There is a single ItemStack that has an subtype of "9".  I can also see in code where it is registered with that subtype ID.  However, in JEI the Alexandrite ItemStack has a subtype of 8.  Is there such a subtype of "9" for gem_ore?

**Comment by Sunconure11** [comment]
This has been (hopefully) fixed in dev. Think you can wait a bit though before i release the next alpha? It's only 5 days until I release it.
