### ISSUE TITLE
Mekanism crash

### ISSUE THREAD

**Issue by thenextelement** [Um-Mitternacht/Bewitchment#148]
### Expected Behavior
Normal loading

### Actual Behavior
Another startup crash

### Steps to Reproduce
Download Bewitchment and all dependencies, as well as mekanism.

### Version of Minecraft, Bewitchment, Forge, and Baubles
MC 1.12.2 Bewitchment 0.16.6, Forge 14.23.5.2796 and Baubles 1.12.2-1.5.2

### Logs, in the event of a crash
https://pastebin.com/RHEGH9Hj

**Comment by OreCruncher** [comment]
Bet its the same issue as [#147].

**Comment by Sunconure11** [comment]
It is. It's now fixed in dev, but I won't push out the next alpha until christmas
