### ISSUE TITLE
Thaumcraft minimum version not specified

### ISSUE THREAD

**Issue by Mountain-Hemlock** [Um-Mitternacht/Bewitchment#150]
### Expected Behavior
As far as I understand, Thaumcraft should be compatible with Bewitchment

### Actual Behavior
Every time I try to load with Bewitchment and Thaumcraft, the game crashes with the java.lang.NoClassDefFoundError, specifically with the moonbell

### Steps to Reproduce
Installed forge 1.12.2, placed latest versions of bewitchment, patchouli, baubles, and thaumcraft into mods folder

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles
Minecraft 1.12.2, Bewitchment 0.0.16.7, Forge 1.12.2-14.23.5.2796, Patchouli 1.0-13, Baubles 1.12-1.5.2

### Screenshots encouraged
![screen shot 2018-12-21 at 4 40 46 pm](https://user-images.githubusercontent.com/46057990/50364823-b3da0880-053f-11e9-9166-6bf2c549acdc.png)

### Logs, in the event of a crash
<https://pastebin.com/sWu74DAN>

### If this is a question, developer commentary, or a suggestion, ignore this template

**Comment by zabi94** [comment]
Thaumcraft is not the latest version, you have beta25 installed, beta26 is on curseforge

**Comment by zabi94** [comment]
This however highlights that a minimum version of thaumcraft should probably be added to the soft dependencies list

**Comment by Mountain-Hemlock** [comment]
It works now, didn't notice it was the previous beta. Thank you.
