### ISSUE TITLE
Cold iron armour

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#152]
The textures for the Cold Iron set are already in-game, but it is not yet an actual armour. Should be between iron and diamond in strength, should also be stronger than our own silver. 
Each piece acts like the Thorns enchant when a demon-based or spirit-based entity using a melee attack on the wearer, each piece stacks. Also should provide extra protection from demon-based attacks, melee or otherwise.
Possibly a bit of innate fire-resistance too? Both due to its cold nature and its use as anti-demon gear.

**Comment by MoriyaShiine** [comment]
armor has been added, will add special effects when I get back from dinner

**Comment by Sunconure11** [comment]
Check this enchant for details on demon protection.

https://github.com/Um-Mitternacht/Bewitchment/blob/master/src/main/java/com/bewitchment/common/content/enchantments/EnchantmentDemonProtection.java

**Comment by Sunconure11** [comment]
Players wearing it should receive the slowness effect
