### ISSUE TITLE
Natural generation for Spanish moss

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#153]
Spanish moss should generate on solid blocks (logs mostly) and semi-solid blocks (i.e. back of stairs and on upside-down stairs, and of course leaves) in any overworld biomes with the SWAMP tag. In addition, these natural spanish mosses should only grow a max of 3 blocks (2 upper parts and 1 lower part) in the wild, but "cultivated" (player-placed) spanish moss should grow just as it does now

**Comment by anqingchen** [comment]
done in diabolic
