### ISSUE TITLE
Hellhound gets damaged when it attacks another mob, even passive ones

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#157]
It should not be taking damage from inflicting damage. Check if other hostile/neutral mobs suffer from this, as well.

**Comment by Sunconure11** [comment]
Confirming that the uranids suffer from it, too.

**Comment by Sunconure11** [comment]
Might want to check if the armor set is cold iron, I'm going to do some testing involving a player wearing leather armor and what not.

**Comment by MoriyaShiine** [comment]
Shouldn't be an issue, the getArmorPieces method only counts with cold iron
