### ISSUE TITLE
Allow recipes, rituals, and brews using beeswax to accept more Oredict entries 

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#162]
Just a bit of small mod compat, but recipes such as candles, rituals, and brews that use beeswax should also accept items with the following OreDict tags:
`wax` (Rustic)
`tallow` (Rustic)
`clumpWax` (Primalcore)

**Comment by Sunconure11** [comment]
Trying to figure this out now

**Comment by Sunconure11** [comment]
Apparently CompoundIngredient has protected access for some reason. This will have to be figured out later.

**Comment by Sunconure11** [comment]
Mostly complete, aside from candle recipes.

**Comment by Sunconure11** [comment]
I wonder if there is a way involving the code itself, and not JSON, to tackle all of these recipes, for the candles at least.
