### ISSUE TITLE
New logo is needed when more of the requirements of the snapshot are complete

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#163]
Assigning Kraehe to the creation of this, but this will come closer to when I'm nearing a release of a snapshot build for curse.

Versions needed:

One that can fit on a discord channel
One that can fit on a curseforge page

**Comment by cybercat5555** [comment]
For a general idea, look at the silver, cold iron, and nethersteel chisel variants named "symbol" and "symbol bevel"

**Comment by Sunconure11** [comment]
This is finished, but it will not be closed until Wednesday.
