### ISSUE TITLE
Heads for hellhounds and alpha hellhounds

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#166]
As it says in the title, hellhounds and their alpha version should have heads, both for use in rituals, as altar boosters, and as decorations, as Witchery also had heads for these beasts. BA+ has a method for adding new mob heads that can be looked at if needed.

**Comment by itsmeow** [comment]
@Sunconure11 I'll set up the system - but actual ritual stuff I can't do since I don't know what Witchery was like :3

**Comment by itsmeow** [comment]
@cybercat5555 Do you have the 2D textures for these?

**Comment by cybercat5555** [comment]
Nope, but I can make them fairly easily. Should it be one for each variant texture?

**Comment by itsmeow** [comment]
If you want, as long as you tell me what textures go to what variant number wise, it can be any amount.
