### ISSUE TITLE
Oven GUI broken

### ISSUE THREAD

**Issue by Tiktalik** [Um-Mitternacht/Bewitchment#177]
### Expected Behavior
Fuel should stay in the fuel slot and results should be shift clickable out.

### Actual Behavior
When using the oven, fuel consumption doesn't work properly. Placing a stack of fuel inside, closing the GUI, and opening it will result in all the fuel disappearing with the burn time of one item;
sometimes just placing the fuel inside will do it.

Items in either of the output slots also can't be removed.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12, Bewitchment-1.12.2-0.0.17.6, Forge 14.23.5.2807, Patchouli 1.0-16, LLibrary 1.7.17-1.12.2, Baubles 1.12-1.5.2

**Comment by Sunconure11** [comment]
The same behavior is occurring in Covens Reborn. I shall see if there are any fixes I can use.
