### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by catlover21** [Um-Mitternacht/Bewitchment#186]
Bewitchment-1.12.2-0.0.18.5 is crashing on start up.

i'm on the lates version of forge.

[crash-2019-02-05_10.31.54-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2832717/crash-2019-02-05_10.31.54-client.txt)

**Comment by Sunconure11** [comment]
Download LLibrary.

**Comment by zabi94** [comment]
Well, the error would be avoided if it was marked as a proper dependency, you should probably do that to avoid future reports
