### ISSUE TITLE
Stuff to do before first release

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#19]
- [x] FINISH TILE ENTITY REWRITE BEFORE ANYTHING ELSE
- [ ] Rewrite Athame and Boline code
- [ ] More advanced fume recipes
- [x] Decide the barrels fate
- [ ] More rituals
- [ ] Distillery
- [ ] Brazier
- [ ] Add more stuff and things here, other devs

**Comment by Placid-Storm** [comment]
Glad to see it's coming along. Wish I could help but I'm not ready as a developer to take on projects.

**Comment by zabi94** [comment]
We should either move the release map on an issue or close this and use the map exclusively. Both makes for a confusing tracker

**Comment by zabi94** [comment]
Moved to private doc
