### ISSUE TITLE
Ore spawning needs to be redone

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#193]
Neither is our only stone, coquina. This needs to be resolved before release.

**Comment by Sunconure11** [comment]
Coquina should spawn on beaches and in oceans

**Comment by Sunconure11** [comment]
Gems should spawn in all biomes

**Comment by Sunconure11** [comment]
Assigning @ArekkuusuJerii, since I'm pretty sure he did the original generation for ore.

Ore simply does not seem to be very common from this mod.

**Comment by Sunconure11** [comment]
Ore spawns seem to be entirely broken, I'm trying to get a setting for the upcoming indev build that would allow all to spawn, but it seems one of the gemstones will take precedence over the others.

Also, not seeing any coquina. Requesting the rewrite for any generation be brought over to the master branch as well, since that will be the indev build on Wednesday.

**Comment by xAlicatt** [comment]
Can confirm...not getting any ore spawns except for Silver in my worlds so far

**Comment by xAlicatt** [comment]
> Ore spawns seem to be entirely broken, I'm trying to get a setting for the upcoming indev build that would allow all to spawn with a decent chance of being found by players readily, but it seems one of the gemstones will take precedence over the others. Salt and silver are not affected by this.
> 
> Also, not seeing any coquina. Requesting the rewrite for any generation be brought over to the master branch as well, since that will be the indev build on Wednesday.
> 
> For the coquina, it should spawn on both beaches and in oceans, via biomedict.

Coquina is generating, perhaps not as often as you would like? I have seen it though. On beaches....not in oceans so far.

**Comment by Sunconure11** [comment]
Yeah, coquina got fixed. However, it was spawning a bit too much so I had to tone down spawn rates to 5.
