### ISSUE TITLE
Chalk stacks temporarily with itself

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#194]
https://cdn.discordapp.com/attachments/509421347714367491/545773393874649118/unknown.png

"There seems to be a glitch with Chalk stacking temporarily and then unstacking. It only seems to be problematic when using the chest sorting button here, as it deleted one of the two Focal Chalk I had."

**Comment by itsmeow** [comment]
I would suggest getting rid of the meta and switching to seperate item instances. Also, why is the durability a custom nbt tag? Use the builtin durability.

**Comment by zabi94** [comment]
It inherited that from old covens code, where damage was used to account for other things. We should both change that
