### ISSUE TITLE
Possibly more shared bugs between this mod and Covens

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#196]
https://github.com/zabi94/Covens-reborn/issues/22

**Comment by olol5620** [comment]
also this
https://github.com/zabi94/Covens-reborn/issues/23#issue-410653038

**Comment by olol5620** [comment]
and for that matter, the back of the magic mirror has no texture

**Comment by Sunconure11** [comment]
A bunch more have been found, for devs, check the dev channels in BW's discord.

**Comment by Sunconure11** [comment]
Rewrite has changed a lot of the codebase. No longer relevant.
