### ISSUE TITLE
Add mob spawn configs

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#198]
And allow them to be easily shut off, if needed, as well, through said config.

**Comment by MokahTGS** [comment]
Along with general mob spawning controls, please allow for mob control per dimension to allow mod pack makers the greatest freedoms.

**Comment by xt9** [comment]
There's plenty of mods that allow you to set up mob spawning rules. Just having a disable/enable toggle would be enough.

**Comment by MokahTGS** [comment]
There is basically on mod, InControl which is spotty at best.

**Comment by MokahTGS** [comment]
You need to add spawn weight controls.  The mobs from this are too many.  Simply turning them off or making players use other mods to control yours is not enough.

**Comment by Sunconure11** [comment]
@itsmeow
