### ISSUE TITLE
Stuff that requires textures

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#20]
- [x] Regal Silk
- [x] Graveyard Dust
- [x] Golden Thread
- [x] Hellish Bauble
- [x] Witches Stitching
- [x] Diabolic Vein
- [x] Pure Filament
- [x] Sacrosanct Earth
- [x] Graveyard Dirt
- [x] Gem Blocks (they should be redone)
- [x] Rest of the tarot cards
- [x] Grilled Watermelon (New texture is needed IMO)
- [x] "Location Stone"
- [x] Kelp. Kelp needs a revamp in it's entirety, texturally.
- [x] New apiary GUI

**Comment by OtisGoodman** [comment]
They are all done check them oof!

**Comment by OtisGoodman** [comment]
off*

**Comment by zabi94** [comment]
Cards are all done, closing
