### ISSUE TITLE
Witches Hood

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#204]
Model is in, it just needs an implementation. Assigning two individuals to this, since I'm not sure how to tackle this.

It would have the same armor value and stats as a witches hat, but just have a different look.

**Comment by Sunconure11** [comment]
Hood/cowl is in, but will not render.

**Comment by itsmeow** [comment]
The texture was set to the one for witch armor, I fixed that, but the model still is not rendering.
