### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by PixelEyeStudios** [Um-Mitternacht/Bewitchment#210]
### Expected Behavior
The game to load

### Actual Behavior
Crashes before loading

### Steps to Reproduce
Not sure, just crashes before loading

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Latest bewitchment version (mod list in the crash report)

### Screenshots encouraged
Not sure how a screenshot of minecraft saying "Fuck you" is going to help

### Logs, in the event of a crash
https://pastebin.com/Zx3pe6pe

**Comment by Sunconure11** [comment]
angkor wat

**Comment by PixelEyeStudios** [comment]
Trust me, I have a knack of breaking things somehow in some way, ask Zabi when I was a tester for covens

**Comment by Sunconure11** [comment]
Issue appears to be connected to NEI. But I'd advise switching over to JEI at this point, due to more support.

**Comment by PixelEyeStudios** [comment]
Alright thank you

**Comment by zabi94** [comment]
Does this happen if you only have nei + jei + forge? Without bewitchment? Looks like NEI doesn't handle new Forge Versions properly

**Comment by zabi94** [comment]
Oh, you're using an old-ass NEI version there. Update it
