### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Deaky4** [Um-Mitternacht/Bewitchment#217]
### Expected Behavior
Game loads to the Forge Mod Loader Loading screen with the hammer and anvil

### Actual Behavior
Goes back to the Minecraft Launcher (pictured in screenshot)

### Steps to Reproduce
Start game with forge 1.12.2.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, Bewitchment 0.0.19.3-indev, Forge 1.12.2-14.23.5.2815. Patchouli 1.0-16, LLibrary 17.17, Baubles 1.5.2

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/47761335/52985782-e7f46d00-33ba-11e9-8c36-56c6f425c43f.png)

### Logs, in the event of a crash
Nothing was posted in the Crash-Reports folder.

**Comment by Sunconure11** [comment]
Post the full crash report

**Comment by ToxinEren** [comment]
What can I do about this?
[crash-2019-02-26_19.39.20-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2906993/crash-2019-02-26_19.39.20-client.txt)

**Comment by Sunconure11** [comment]
@ToxinEren Use Forge 1.12.2-14.23.5.2815.
