### ISSUE TITLE
Crash on startup, Other mods are installed

### ISSUE THREAD

**Issue by BennyTurtle** [Um-Mitternacht/Bewitchment#219]
### Expected Behavior

For the modpack to load up and work properly

### Actual Behavior

it crashes at loading bewitchment (newest)

### Steps to Reproduce

Download Tinkers haven modpack and add bewitchment and patchouli
Run the pack 

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used

All Newest (Minecraft 1.12.2)

### Screenshots encouraged

https://drive.google.com/open?id=1vHGLkhX4tSUk9-XoCm7C1TiMLOQmYgIZ

### Logs, in the event of a crash

[crash-2019-02-19_09.36.06-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2880453/crash-2019-02-19_09.36.06-client.txt)

**Comment by Sunconure11** [comment]
Install the latest build of Forge. For some reason, when I tried to enforce it in the code, it would not warn users.

**Comment by BennyTurtle** [comment]
I do have the latest forge

**Comment by BennyTurtle** [comment]
It seems to be a issue with twitch launcher saying its the latest
