### ISSUE TITLE
Some blocks don't drop themselves

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#222]
Recorded with the distillery and the cauldron, may affect other blocks too.

**Comment by Sunconure11** [comment]
This would normally be easy to fix, but it seems it's ignoring the methods used to determine what it is mined with.

**Comment by zabi94** [comment]
Was this on multiplayer, single player or lan? It makes a difference

**Comment by Sunconure11** [comment]
I've encountered it on singleplayer, and players on the server found it too.
