### ISSUE TITLE
NoClassDefFoundError: crash while loading  net/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent

### ISSUE THREAD

**Issue by TheOneTraveler** [Um-Mitternacht/Bewitchment#225]
### Expected Behavior
i expected my game to load lol

### Actual Behavior
my game crashed the moment i tried loading it

### Steps to Reproduce
try loading the game lol

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
im using the latest version of bewitchment 0.0.19.10, Forge 14.23.5.2814, Patchouli 1.0-1.5, LLibrary 1.7.14, Baubles 1.5.2, and obviously, Minecraft 1.12.2/ 

### Screenshots encouraged
N/A

### Logs, in the event of a crash
i'll send the crash log. should i also send the regular latest.log? it might show different crashes due to different reasons as i've been playing around with my mods getting them to work with bewitchment all day. pretty sure this isnt on my end entirely. could be a mod incompatibility. in this event, i'd like to know which mod is incompatible so i can look into my options lmao.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/20/19 1:34 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bewitchment (bewitchment)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:255)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:296)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration$1.<init>(EntityRegistry.java:81)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:80)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:67)
	at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:199)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:192)
	at com.bewitchment.common.entity.ModEntities.init(ModEntities.java:43)
	at com.bewitchment.common.Bewitchment.preInit(Bewitchment.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.PotionEvent$PotionApplicableEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1515095232 bytes (1444 MB) / 2281701376 bytes (2176 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E2 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version         | Source                                                | Signature                                |
	|:----- |:------------------ |:--------------- |:----------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2          | minecraft.jar                                         | None                                     |
	| UCH   | mcp                | 9.42            | minecraft.jar                                         | None                                     |
	| UCH   | FML                | 8.0.99.99       | forge-1.12.2-14.23.5.2770.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.5.2770    | forge-1.12.2-14.23.5.2770.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | dsurroundcore      | 3.5.4.3         | minecraft.jar                                         | None                                     |
	| UCH   | applepie           | 1.1             | applepie-1.1.jar                                      | None                                     |
	| UCH   | backstab           | 1.0.3.1         | backstab-1.12.2-1.0.3.1.jar                           | None                                     |
	| UCH   | ichunutil          | 7.1.4           | iChunUtil-1.12.2-7.1.4 (2).jar                        | None                                     |
	| UCH   | backtools          | 7.0.0           | BackTools-1.12.2-7.0.0.jar                            | None                                     |
	| UCH   | baubles            | 1.5.2           | Baubles-1.12-1.5.2 (1).jar                            | None                                     |
	| UCH   | betteranimalsplus  | 5.0.1           | betteranimalsplus-5.0.1.jar                           | None                                     |
	| UCH   | bettergolem        | 1.0             | bettergolem-1.12.2-1.0.jar                            | None                                     |
	| UCH   | betternether       | 0.1.8.2         | betternether-0.1.8.2.jar                              | None                                     |
	| UCH   | patchouli          | 1.0-15          | Patchouli-1.0-15.jar                                  | None                                     |
	| UCH   | llibrary           | 1.7.14          | llibrary-1.7.14-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCEE  | bewitchment        | @VERSION@       | Bewitchment-1.12.2-0.0.19.10-indev.jar                | None                                     |
	| UC    | forgelin           | 1.8.2           | Forgelin-1.8.2.jar                                    | None                                     |
	| UC    | bountiful          | 2.1.0           | Bountiful-2.1.0.jar                                   | None                                     |
	| UC    | brownmooshrooms    | 1.0.0           | brownmooshrooms-1.0.0 (2).jar                         | None                                     |
	| UC    | cakechomps         | 1.12.2-1.0      | cakechomps-1.12.2-1.0.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | codechickenlib     | 3.2.2.353       | CodeChickenLib-1.12.2-3.2.2.353-universal (2).jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | extendedrenderer   | v1.0            | coroutil-1.12.1-1.2.14.jar                            | None                                     |
	| UC    | coroutil           | 1.12.1-1.2.14   | coroutil-1.12.1-1.2.14.jar                            | None                                     |
	| UC    | configmod          | v1.0            | coroutil-1.12.1-1.2.14.jar                            | None                                     |
	| UC    | cosmeticbeds       | 1.12.2-1.0.2    | cosmeticbeds-1.12.2-1.0.2.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | crafttweaker       | 4.1.14          | CraftTweaker2-1.12-4.1.14.jar                         | None                                     |
	| UC    | ctgui              | 1.0.0           | CraftTweaker2-1.12-4.1.14.jar                         | None                                     |
	| UC    | jei                | 4.12.1.217      | jei_1.12.2-4.12.1.217.jar                             | None                                     |
	| UC    | crafttweakerjei    | 2.0.2           | CraftTweaker2-1.12-4.1.14.jar                         | None                                     |
	| UC    | creaturebeacons    | 1.12.2-1.0.1    | creaturebeacons-1.12.2-1.0.1.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | cucumber           | 1.0.0           | CucumberMod-1.0.0[1.12.2].jar                         | None                                     |
	| UC    | culinaryconstruct  | 1.3.1           | culinaryconstruct-1.3.1.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | customnpcs         | 1.12            | CustomNPCs_1.12.2(26aug18) (1).jar                    | None                                     |
	| UC    | cyclopscore        | 0.11.11         | CyclopsCore-1.12.2-0.11.11.jar                        | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | dungeontactics     | DT-0.15.8       | DungeonTactics-1.12.2-0.15.8.jar                      | None                                     |
	| UC    | ebwizardry         | 4.1.4           | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar        | None                                     |
	| UC    | ffenchants         | 1.1.2           | ffenchants-1.12.2-1.1.3.jar                           | None                                     |
	| UC    | giacomos_bookshelf | 1.2             | GiacomosBookshelf-1.12.2-1.2 (1).jar                  | None                                     |
	| UC    | leopardengruen37   | 1.1.0           | GlowingCocoaMod_by_Leopardengruen_1.1.0 (2).jar       | None                                     |
	| UC    | guardillagers      | 1.0.0           | guardillagers-1.12.2-1.0.0.jar                        | None                                     |
	| UC    | howlitdo           | 1.1             | HowlItDo-1.1.jar                                      | None                                     |
	| UC    | iceandfire         | 1.6.1           | iceandfire-1.6.1-1.12.2.jar                           | None                                     |
	| UC    | infinitedark       | 1.1.0.0         | InfiniteDark-1.12.2-1.1.0.0.jar                       | None                                     |
	| UC    | livingenchantment  | 3.1.6           | living_enchantment-3.1.6.jar                          | None                                     |
	| UC    | gbook              | 2.8.3           | Guidebook-1.12.2-2.8.3.jar                            | None                                     |
	| UC    | ltta               | 1.3.1           | ltta-1.12.2-1.3.1.jar                                 | None                                     |
	| UC    | maille             | 2.0             | Maille1.12.2-2.0 (2).jar                              | None                                     |
	| UC    | mirageorb          | 1.1.0           | mirageorb-1.12.2-1.1.0.jar                            | None                                     |
	| UC    | monk               | 1.4             | monk-mod-1.4 (1).jar                                  | None                                     |
	| UC    | mowziesmobs        | 1.5.3           | mowziesmobs-1.5.3.jar                                 | None                                     |
	| UC    | nei                | 2.4.2           | NotEnoughItems-1.12.2-2.4.2.240-universal (1).jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | peachy             | 1.0             | peachy-1.0 (1).jar                                    | None                                     |
	| UC    | jmilpol            | 1.6             | PendantOfLife-1.7.jar                                 | None                                     |
	| UC    | pvj                | 1.5.2           | ProjectVibrantJourneys-1.12.2-1.5.2 (1).jar           | None                                     |
	| UC    | puddles            | 1.1             | Puddles-1.1.jar                                       | None                                     |
	| UC    | repairgem          | 1.3.0           | RepairGem-1.12.2-1.3.0.jar                            | None                                     |
	| UC    | rustic             | 1.1.0           | rustic-1.1.0.jar                                      | None                                     |
	| UC    | tiffitlib          | 1.0.3           | tiffitlib-1.0.3.jar                                   | None                                     |
	| UC    | sanity             | 1.0.3           | sanity-1.0.3.jar                                      | None                                     |
	| UC    | sauceconstruct     | 1.1.3           | sauceconstruct-1.12.2-1.1.3.jar                       | None                                     |
	| UC    | simplecorn         | 2.4.1           | SimpleCorn1.12-1.12-2.4.1 (1).jar                     | None                                     |
	| UC    | simpleflax         | 0.2.0           | SimpleFlax-0.2.0.jar                                  | None                                     |
	| UC    | skeletalband       | 1.1.1           | skeletalband-1.12.2-1.1.1.jar                         | None                                     |
	| UC    | skewers            | 1.1             | Skewers-1.1.jar                                       | None                                     |
	| UC    | lemonlib           | 1.3.0           | lemonlib-1.12.2-1.3.0.jar                             | None                                     |
	| UC    | statues            | 1.0.1           | statues-rechiseled-1.12.2-1.0.1.jar                   | None                                     |
	| UC    | strawgolem         | 1.3             | strawgolem-1.3.jar                                    | None                                     |
	| UC    | tabula             | 7.0.0           | Tabula-1.12.2-7.0.0 (1).jar                           | None                                     |
	| UC    | torchlever         | 1.0             | TorchLever-1.0.jar                                    | None                                     |
	| UC    | toughnessbar       | 1.4             | toughnessbar-1.4.jar                                  | None                                     |
	| UC    | universalbestiary  | 1.1.0           | universalbestiary-1.12.2-1.1.0.jar                    | None                                     |
	| UC    | walljump           | 1.12.2-1.2.0    | walljump-1.12.2-1.2.0 (1).jar                         | None                                     |
	| UC    | waystones          | 4.0.67          | Waystones_1.12.2-4.0.67 (2).jar                       | None                                     |
	| UC    | worldedit          | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1).jar | None                                     |
	| UC    | xaerominimap       | 1.15.8          | Xaeros_Minimap_1.15.8_Forge_1.12.jar                  | None                                     |
	| UC    | orelib             | 3.5.2.2         | OreLib-1.12.2-3.5.2.2.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UC    | dsurround          | 3.5.4.3         | DynamicSurroundings-1.12.2-3.5.4.3.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UC    | ladylib            | 2.1             | Ladylib-2.1.jar                                       | None                                     |
	| UC    | lumen              | 0.4.0           | lumen-Beta+0.4.1 (3).jar                              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 6670'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 6670
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2`

**Comment by GameGlr1** [comment]
I had a similar crash, only the mods I had were just the bewitchment mod and the required mods.

**Comment by Sunconure11** [comment]
Use the LATEST build of forge. My warning screwed up.

**Comment by TheOneTraveler** [comment]
I AM.

**Comment by Sunconure11** [comment]
You are using 14.23.5.2770, according to the error.

Use 14.23.5.2814

**Comment by TheOneTraveler** [comment]
I AM. that's the problem. every time i load up 2814 it says i am loading up 2770 and crashes, but im not. i uninstalled witchery and it literally immediately fixed the problem.

**Comment by yoopgim** [comment]
wait did you  put it back in after uninstalling it if so then thsank you for telling me funny thing is i had another mod problem with thermal expansion in 1.7.10  and it was caused by me putting the rwrong versions in and/ or not all the needed mods and it corrupted some of the mods so i had to delete then re install them anyway im rambling on and if thes does not work then here is the crash report 



---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2019-06-03 16:33:21 CDT
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:255)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:296)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:264)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:264)
    at com.bewitchment.common.entity.ModEntities.registerWithEgg(ModEntities.java:85)
    at com.bewitchment.common.entity.ModEntities.<clinit>(ModEntities.java:64)
    at com.bewitchment.common.entity.ModEntities$RegistrationHandler.onEvent(ModEntities.java:123)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_RegistrationHandler_onEvent_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.PotionEvent$PotionApplicableEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 572174240 bytes (545 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 25 mods loaded, 25 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID              | Version                | Source                                                | Signature                                |
       |:----- |:--------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft       | 1.12.2                 | minecraft.jar                                         | None                                     |
       | UCH   | mcp             | 9.42                   | minecraft.jar                                         | None                                     |
       | UCH   | FML             | 8.0.99.99              | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge           | 14.23.5.2768           | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | movillages      | 1.5.4                  | [1.12]MoVillages-1.5.4.jar                            | None                                     |
       | UCH   | baubles         | 1.5.2                  | Baubles-1.12-1.5.2.jar                                | None                                     |
       | UCH   | patchouli       | 1.0-18                 | Patchouli-1.0-18.jar                                  | None                                     |
       | UCH   | llibrary        | 1.7.15                 | llibrary-1.7.15-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | UCH   | bewitchment     | @VERSION@              | Bewitchment-1.12.2-0.0.19.47-indev.jar                | None                                     |
       | UCH   | jei             | 4.14.3.240             | jei_1.12.2-4.14.3.240.jar                             | None                                     |
       | UCH   | botania         | r1.10-361              | Botania+r1.10-361.jar                                 | None                                     |
       | UCH   | codechickenlib  | 3.2.2.353              | CodeChickenLib-1.12.2-3.2.2.353-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | dc              | Beta 1.0.0             | DungeonCraft+Beta+1.0.0.jar                           | None                                     |
       | UCH   | embers          | 1.12                   | EmbersRekindled-1.12.jar                              | None                                     |
       | UCH   | roots           | 0.104                  | roots-2-0.104.jar                                     | None                                     |
       | UCH   | rustic          | 1.1.0                  | rustic-1.1.0.jar                                      | None                                     |
       | UCH   | totemic         | 1.12.2-0.11.1          | Totemic-1.12.2-0.11.1.jar                             | 21d11d7bf4d97b465382a1f95428029aac6daaea |
       | UCH   | vanillafix      | 1.0.10-SNAPSHOT        | VanillaFix-1.0.10-99.jar                              | None                                     |
       | UCH   | drplibrary      | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.024240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpcmblueprints | 1.12.2-1.2.4           | drpcmblueprints-1.12.2-1.2.4.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpcmmaarg      | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.064036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpcmguis       | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.110253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpcore         | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.7.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpcmlocks      | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.101203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | UCH   | drpmedieval     | 1.12.2-0.3.4           | drpmedieval-1.12.2-0.3.4.jar                          | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      llibrary (llibrary-core-1.0.8-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13547 Compatibility Profile Context 25.20.15015.1002' Renderer: 'AMD Radeon R7 240'
  Suspected Mods: Bewitchment (bewitchment)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
  LWJGL: 2.9.4
  OpenGL: AMD Radeon R7 240 GL version 4.6.13547 Compatibility Profile Context 25.20.15015.1002, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by yoopgim** [comment]
yeah its not working please help
