### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by MACMAN2003** [Um-Mitternacht/Bewitchment#229]
### Expected Behavior
Opening the game exe and showing the loading screen

### Actual Behavior
The exe doesn't even open and I have to go into task manager to close the launcher.

### Steps to Reproduce
Install Optifine manually and launch the mod.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, all, all, up to date, up to date, up to date.

### Logs, in the event of a crash
No logs, but the game launched only after I uninstalled optifine.

**Comment by Sunconure11** [comment]
Due to Optifine's nature, I really can't do anything about this. Try FoamFix and BetterFPS.

**Comment by PulseBeat02** [comment]
I had this issue before. The problem was about invalid image files in the splash.properties. Make sure to check that also.
