### ISSUE TITLE
Crash to do with cauldrons

### ISSUE THREAD

**Issue by CammiePone** [Um-Mitternacht/Bewitchment#231]
### Expected Behavior
I believe what was supposed to happen was something was being crafted.

### Actual Behavior
It crashed the server

### Steps to Reproduce
I am not entirely sure, but it was on multiplayer.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, 0.9.14, 14.23.5.2815, 1.0-17, 1.7.17, 1.5.2

### Logs, in the event of a crash
https://pastebin.com/BSaXbz0v

**Comment by CammiePone** [comment]
Update: The cauldron is trying to craft an empty recipe, and that's why it's crafting
![image](https://user-images.githubusercontent.com/16853086/53289634-56904c80-3766-11e9-8ab2-48fafd6c6ac2.png)

**Comment by zabi94** [comment]
Was this the second recipe being crafted in a row?
That's the only way I can imagine to enter this status

**Comment by CammiePone** [comment]
According to everyone who was at the scene of the offending cauldrons, none of them were crafting anything at all. It was just a cauldron that had altar power. My guess is it was fine when they did it at first, but when they came back to the chunk, it tried to craft something.
