### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Wolfy2002** [Um-Mitternacht/Bewitchment#232]
### Expected Behavior
I wanted to play on the server.

### Actual Behavior
It doesn't happen every time but when I try to craft something(in my inventory or in the crafting table) or to press anywhere when I'm inside my inventory it crashes.

### Steps to Reproduce
Explained it above

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Downloaded the modpack from the Twitch Client

### Screenshots encouraged
This is how the crash thing appears on the client: http://prntscr.com/moam5x

### Logs, in the event of a crash

https://pastebin.com/iaJHtVFq

**Comment by Sunconure11** [comment]
Probably connected to #221
