### ISSUE TITLE
Cauldron Crashes Game when Shift-Right-Clicked

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#233]
### Expected Behavior
I wanted to put the handle of the Witches Cauldron up, so I shift-right-clicked it to change it.

### Actual Behavior
The game crashed as soon as I tried.

### Steps to Reproduce
1.  Place down a cauldron.
2.  Shift-right-click it.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC: 1.12.2
BW: 0.0.19.16
Forge: 14.23.5.2815
Patchouli: 1.0-17
LLibrary: 1.7.17
Baubles: 1.5.2

### Logs, in the event of a crash
https://pastebin.com/euNJCuNv

**Comment by Sunconure11** [comment]
This is a fault of me porting stuff over blindly trying to fix another bug. I'll roll out a hotfix.
