### ISSUE TITLE
Crash With Gem Bowl on Altar

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#234]
### Expected Behavior
Placed a gem bowl on an altar, then tried to put a diamond inside.

### Actual Behavior
It crashed when I put the diamond in the bowl.

### Steps to Reproduce

1. Place Gem Bowl on an atlar.
2. Place a Diamond in the Bowl.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC: 1.12.2
BW: 0.0.19.16
Forge: 14.23.5.2815
Patchouli: 1.0-17
LLibrary: 1.7.17
Baubles: 1.5.2

### Logs, in the event of a crash
https://pastebin.com/4vSJHtHu

**Comment by Sunconure11** [comment]
Same as 233.
