### ISSUE TITLE
Infusions lost after death

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#235]
### Expected Behavior
Infusions are kept after death but their MP emptied

### Actual Behavior
Dying removes the infusion and reverts it back to the default

### Steps to Reproduce
1) Set up any infusion (I used "Infusion of the Flames" for this, but I'd assume any others would work)
2) Kill yourself somehow
3) Respawn with the default power bar

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC 1.12.2
BW 0.19.16
Forge .2814
Patchouli 1.0-16
Llibrary: 1.7.17-1.12.2
Baubles: 1.13-1.5.2

### Screenshots encouraged
https://imgur.com/a/H2hReuN

### Logs, in the event of a crash
N/A

**Comment by DaveArndt** [comment]
It looks like the infusion type isn't saved with the other capabilities on player death. I don't have time to set this up in my dev environment or test that the fix works today, but it just needs one line of code. Add
```
CapabilityHelper.copyDataOnPlayerRespawn(event, InfusionCapability.CAPABILITY);
```
after line 28.

https://github.com/Um-Mitternacht/Bewitchment/blob/5ee1034ce152cd0f8ed90a4ea1dc1a12148b2368/src/main/java/com/bewitchment/common/core/event/EnergyEvents.java#L24-L30

**Comment by DaveArndt** [comment]
It looks like this issue should be closed. Sunconure11 took care of it
