### ISSUE TITLE
Cannot Grow Yew Trees with Bonemeal

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#236]
### Expected Behavior
Place a yew sapling down, bonemeal it to grow it up.

### Actual Behavior
Bonemeal makes particle effects, but tree stays as a sapling.

### Steps to Reproduce
1. Place Yew Sapling down.
2. Bonemeal it into oblivion.
3. It shouldn't grow.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC: 1.12.2
BW: 0.0.19.16
Forge: 14.23.5.2815
Patchouli: 1.0-17
LLibrary: 1.7.17
Baubles: 1.5.2

**Comment by cybercat5555** [comment]
Not a bug, Yew Trees are 2x2 like vanilla dark oaks

**Comment by TechnoMysterio** [comment]
Ah, I am a pillock. Closing.
