### ISSUE TITLE
Crash when INT

### ISSUE THREAD

**Issue by cofffeeelinux** [Um-Mitternacht/Bewitchment#238]
### Expected Behavior
Load

### Actual Behavior
Crash

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, all versions of Bewitchment, 2814, most current for all others

### Logs, in the event of a crash
https://paste.dimdev.org/raluwomacu.mccrash

**Comment by Sunconure11** [comment]
You ran out of potion IDs. Either clear some mods or install JEID.

**Comment by cofffeeelinux** [comment]
thanks!
