### ISSUE TITLE
Book of shadows bug

### ISSUE THREAD

**Issue by Shadowcat704** [Um-Mitternacht/Bewitchment#240]
When you change the GUI size the book changes in size and you can’t interact with it or change it back

**Comment by Shadowcat704** [comment]
I was using the current versions of the mods as in latest download files

**Comment by Sunconure11** [comment]
Make a video of this.

**Comment by Shadowcat704** [comment]
Do you just want a video of the small book, cause I can’t make it big again

**Comment by Sunconure11** [comment]
If you can produce it, yes

**Comment by Shadowcat704** [comment]
i screen recorded the bug but it's not letting me post it on here, sorry

**Comment by Sunconure11** [comment]
No input. Closing, as I am trying to clean up the issue tracker a bit.
