### ISSUE TITLE
cant put items in a cauldron??

### ISSUE THREAD

**Issue by TheOneTraveler** [Um-Mitternacht/Bewitchment#241]
### Expected Behavior
i expected to be able to put in the honeycomb and make wax

### Actual Behavior
nothing happened

### Steps to Reproduce
https://youtu.be/FR9LA76cnnM

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
im using the latest modpack for the server, 1.4.0 i dont know what mod versions the pack uses.

### Screenshots encouraged
https://youtu.be/FR9LA76cnnM

### Logs, in the event of a crash
N/A

**Comment by CammiePone** [comment]
You press Q to throw them in :p
