### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#247]
### Expected Behavior
Exactly what it says on the tin- in the title. Game crashes when starting it, around the 6/7 mark on the loading bar.

### Actual Behavior
I start the game... and then it crashes.

### Steps to Reproduce
1. Start game.
2. ...It crashes.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC: 1.12.2
BW: 0.0.19.20
Forge: 14.23.5.2815
Patchouli: 1.0-17
LLibrary: 1.7.17
Baubles: 1.5.2

### Logs, in the event of a crash
https://pastebin.com/7Z0r25a0

**Comment by itsmeow** [comment]
Please start game again and send debug.log

**Comment by TechnoMysterio** [comment]
debug.log on Pastebin: https://pastebin.com/0n3MBcGP

**Comment by TechnoMysterio** [comment]
Just discovered something: when I load up the pack with Rustic installed, the game loads up perfectly fine. From what I can tell, it's something to do with how Forge registers honey.

**Comment by Sunconure11** [comment]
I'm trying to change the internal name for honey. It's probably my fault.
