### ISSUE TITLE
Discord channel has disappeared

### ISSUE THREAD

**Issue by megaminer94** [Um-Mitternacht/Bewitchment#251]
The Bewitchment Discord channel has disappeared from my server list, and when I try to join it it say's it's expired or I don't have permission. Is the server down, or have I been banned for some reason? I am TheFacelessOne#5881 on Discord if that helps.

**Comment by Sunconure11** [comment]
Don't contest bans here. You got mistaken for someone else.

**Comment by Sunconure11** [comment]
You have been however, unbanned.
