### ISSUE TITLE
Honey needs to check for other modded forms of honey

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#252]
As a result of this, the fluid gets broken with mods like Rustic. As there is only one ID for the fluid honey, this is the cause of our errors. This needs to be resolved properly, for when our ID loses.

**Comment by Sunconure11** [comment]
@the-realest-stu Any light you can shed on this? We've gotten pretty close to stamping out this bug.

**Comment by Sunconure11** [comment]
Okay mangoose, sorry for the ping, it has come to my attention that I am an idiot, and was using an outdated build of Rustic in the workspace.

**Comment by Sidnatum** [comment]
Honey fluid and Honey Bucket texture is missed now, without Rustic.
Bewitchment Indev 0.19.25
![honey](https://user-images.githubusercontent.com/48053759/53486673-6d9ea980-3a9a-11e9-8250-a7fdb90a6a01.png)
