### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by BrightDarknessZ** [Um-Mitternacht/Bewitchment#253]
### Actual Behavior
Minecraft crashes during the loading.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
minecraft 1.12.2
Bewitchment Indev 0.19.20 
Forge: 1.12.2 - 14.23.5.2814
Patchouli-1.0-17.jar
LLibrary 1.7.17
`Baubles-1.12-1.5.2.jar`

### Logs, in the event of a crash

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.0.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/24/19 2:36 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:556)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:556)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 238297296 bytes (227 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 Optifine OptiFine_1.12.2_HD_U_E3 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                           | Signature                                |
	|:------ |:------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2814.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2814             | forge-1.12.2-14.23.5.2814.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCHIJA | clothesline-hooks   | 1.12.2-0.0.1.2           | minecraft.jar                                    | None                                     |
	| LCHIJA | uncraftingtable     | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar              | None                                     |
	| LCHIJA | astikorcarts        | 1.12.2-0.1.2.4           | astikorcarts-1.12.2-0.1.2.4.jar                  | None                                     |
	| LCHIJA | backpacks16840      | 3.5.4                    | backpacks+1.12.2+-+3.5.4.jar                     | None                                     |
	| LCHIJA | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | patchouli           | 1.0-17                   | Patchouli-1.0-17.jar                             | None                                     |
	| LCHIJA | llibrary            | 1.7.17                   | llibrary-1.7.17-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | bewitchment         | @VERSION@                | Bewitchment-1.12.2-0.0.19.20-indev.jar           | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCHIJA | bookshelf           | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | forgelin            | 1.8.0                    | Forgelin-1.8.0.jar                               | None                                     |
	| LCHIJA | bountiful           | 2.2.0                    | Bountiful-2.2.0.jar                              | None                                     |
	| LCHIJA | buildinggadgets     | 2.4.6                    | BuildingGadgets-2.4.6.jar                        | None                                     |
	| LCHIJA | carryon             | 1.12.1                   | CarryOn+MC1.12.2+v1.12.1.jar                     | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | coherentvillages    | v0.0.5.10                | coherent_villages-pre-release_v0.0.5.10.jar      | None                                     |
	| LCHIJA | consecration        | 1.0.2                    | consecration-1.12.2-1.0.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | ctm                 | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| LCHIJA | dragonmounts        | 1.12.2-1.5.3             | DragonMounts-1.12.2-1.5.3-resourceFix.jar        | None                                     |
	| LCHIJA | dynamictrees        | 1.12.2-0.9.2             | DynamicTrees-1.12.2-0.9.2.jar                    | None                                     |
	| LCHIJA | ebwizardry          | 4.1.4                    | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar   | None                                     |
	| LCHIJA | eplus               | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | endercompass        | 1.2.6.2                  | EnderCompass-1.12-1.2.6.2.jar                    | None                                     |
	| LCHIJA | gravestone          | 1.10.2                   | gravestone-1.10.2.jar                            | None                                     |
	| LCHIJA | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | iceandfire          | 1.6.1                    | iceandfire-1.6.1-1.12.2.jar                      | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jei                 | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                        | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| LCHIJA | librarianlib        | 4.15                     | librarianlib-1.12.2-4.15.jar                     | None                                     |
	| LCHIJA | livingenchantment   | 3.1.9                    | living_enchantment-3.1.9.jar                     | None                                     |
	| LCHIJA | mowziesmobs         | 1.5.2                    | mowziesmobs-1.5.2.jar                            | None                                     |
	| LCHIJA | multimob            | 1.0.4                    | multimob-1.0.4.jar                               | None                                     |
	| LCHIJA | nethergoldplus      | 1.0.0                    | NetherGoldPlus.jar                               | None                                     |
	| LCHIJA | primitivemobs       | 1.2.3                    | primitivemobs-1.2.3.jar                          | None                                     |
	| LCHIJA | rblr                | 7.0.1                    | RabbitsBreedLikeRabbits-1.12.2-7.0.1.jar         | None                                     |
	| LCHIJA | reccomplex          | 1.4.7                    | RecurrentComplex-1.4.7.jar                       | None                                     |
	| LCHIJA | twilightforest      | 3.9.851                  | twilightforest-1.12.2-3.9.851-universal.jar      | None                                     |
	| LCHIJA | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| LCHIJA | wards               | 1.2                      | wards-1.2.jar                                    | None                                     |
	| LCHIJA | wawla               | 2.5.257                  | Wawla-1.12.2-2.5.257.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones           | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                      | None                                     |
	| LCHIJA | worleycaves         | 1.3.0                    | worleycaves-1.3.0.jar                            | None                                     |
	| LCHIJA | ladylib             | 2.6.2                    | Ladylib-2.6.2.jar                                | None                                     |
	| LCHIJA | modwinder           | 1.1                      | Ladylib-2.6.2.jar                                | None                                     |
	| LCHIJA | dissolution         | 0.3.6                    | Dissolution-1.12.2-0.3.6.jar                     | None                                     |
	| LCHIJA | structurize         | 1.12.2-0.10.47-ALPHA     | structurize-1.12.2-0.10.47-ALPHA.jar             | None                                     |
	| LCHIJA | minecolonies        | 1.12.2-0.10.172-ALPHA    | minecolonies-1.12.2-0.10.172-ALPHA-universal.jar | None                                     |
	| LCHIJA | librarianliblate    | 4.15                     | librarianlib-1.12.2-4.15.jar                     | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.8.0.jar)
  
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
  brad16840.core.ClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6344' Renderer: 'Intel(R) HD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 24.20.100.6344, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: GorgonGreek.zip, Beyond+the+Lands.zip, Wild Hippocampi.zip, Monstrous Cyclops.zip, Faery Pixies.zip, Wild Dragons V3.zip, GoT Dragon Eggs.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 9
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6344
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 

> `4`

**Comment by Sunconure11** [comment]
I'm aware of this error. I'm trying to work on fixing it.
