### ISSUE TITLE
Bottles consumed on uncraftable brews

### ISSUE THREAD

**Issue by Ayrion** [Um-Mitternacht/Bewitchment#256]
### Expected Behavior
Either make the brew or not consume the bottle

### Actual Behavior
Consumed bottle

### Steps to Reproduce
https://drive.google.com/open?id=1PzefpT6CDQXXu3R2vFWsliaGL5EDgDRT

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, 0.0.19.23, 14.23.5.2808, 1.0.17, 1.7.17, 1.5.2

**Comment by Sunconure11** [comment]
I believe @CammiePone is working on some tweaks for brews. Might want to ask her.

**Comment by CammiePone** [comment]
Yeah, been working it out. I basically need to find a way to check if the bottle can accept the brew.

**Comment by CammiePone** [comment]
Alrighty, that should be fixed now with my last commit.
