### ISSUE TITLE
Missed textures: Honey, Oil - source and flowing blocks; Honey bucket.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#260]
![honey](https://user-images.githubusercontent.com/48053759/53487986-0edb2f00-3a9e-11e9-9e85-487c07cbe1d6.png)
![2019-02-28_00 26 28](https://user-images.githubusercontent.com/48053759/53524244-f3007900-3aef-11e9-8a84-b70b4e33b375.png)

Bewitchment Indev 0.19.25 (without Rustic)

**Comment by Sunconure11** [comment]
God damnit, I thought I tackled this.
