### ISSUE TITLE
Black Dog Attacks Through Walls and Ignored By Guards

### ISSUE THREAD

**Issue by MokahTGS** [Um-Mitternacht/Bewitchment#264]
### Expected Behavior
They shouldn't be able to attack vanilla and MCA villagers through walls.  They are also ignored by guards meaning they aren't registered as monsters even though they should be.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Bewitchment-1.12.2-0.0.19.27-indev
Patchouli-1.0-17
llibrary-1.7.17-1.12.2
Baubles-1.12-1.5.2
Forge 2815

### Screenshots encouraged
https://www.dropbox.com/s/pwtwn4p32dtokxr/2019-02-28_19.15.59.png?dl=0

Full modpack list: 
https://pastebin.com/ncNc5S1V

**Comment by Sunconure11** [comment]
@itsmeow

**Comment by MokahTGS** [comment]
As it is now, black dogs spawn en mase and completely decimate a village and the countryside.

**Comment by MokahTGS** [comment]
OK, I'm done some testing and have determined that the mobs attacking through walls was not the fault of Bewitchment.  Minecraft Comes Alive was doing something with the AI where mobs were much more aggressive.  It was affecting all mobs, not just Bewitchment mobs.

**Comment by MokahTGS** [comment]
For reference our mod pack list: https://pastebin.com/ncNc5S1V

**Comment by MokahTGS** [comment]
For pete's sake...I take it back, just saw a black dog eat a villager through a wall.

**Comment by laserlemons** [comment]
I can confirm this. Happened the first day I installed the mod, the dogs were attacking through the wall.
