### ISSUE TITLE
Boline Causing Crash

### ISSUE THREAD

**Issue by cofffeeelinux** [Um-Mitternacht/Bewitchment#265]
### Expected Behavior
Boline works some times however when in Inventory occasionally crashes client

### Steps to Reproduce
have boline

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
12.2, latest, 2814, latest, latest, latest

### Logs, in the event of a crash
https://paste.dimdev.org/tomupoqagu.mccrash

**Comment by cofffeeelinux** [comment]
After further investigation, hovering over boline is what causes the crash

**Comment by DaveArndt** [comment]
Have you added or removed any mods since you crafted the boline? Do you remember the biome you were in when you right clicked it?

**Comment by cofffeeelinux** [comment]
haven't added or removed mods, looks like i was in a plains biome. i ended up getting rid of the boline by going into creative mode and removing it that way. i think it had an issue with the tooltip when hovering over the boline, because using it was fine.

**Comment by DaveArndt** [comment]
What had you recently done with the boline? Did you use it in a ritual?

**Comment by cofffeeelinux** [comment]
nope just crafted it out to see what it did. it worked for cutting grass and leaves.

**Comment by cofffeeelinux** [comment]
if im the only one experiencing this i would hesitate to continue with requesting assistance, there are other bugs and content that shouldnt be held up by me

**Comment by cofffeeelinux** [comment]
Thanks! so i just get the new release and it fixes it? or do i need to do something else to patch

**Comment by DaveArndt** [comment]
unless you know how to build the .jar from source code, you'll need to wait until the next release

**Comment by cofffeeelinux** [comment]
sure thing thank you very much!
