### ISSUE TITLE
Gem ore don't generate, only salt and some silver.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#266]
### Steps to Reproduce
Install World-Stripper-1.6.0-1.12.2, move to the place of intended generation, press delete, wait.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2
Bewitchment-1.12.2-0.0.19.30-indev
Forge 14.23.5.2815
Patchouli-1.0-17
llibrary-1.7.17-1.12.2
Baubles-1.12-1.5.2

### Screenshots encouraged
![2019-03-02_10 51 21](https://user-images.githubusercontent.com/48053759/53679153-d6c03000-3cd9-11e9-9ca6-9f833081a2b5.png)

**Comment by Sunconure11** [comment]
Regen your config.

**Comment by Sunconure11** [comment]
Okay, this is not a config issue.

**Comment by Sunconure11** [comment]
I'm pushing out a new build shortly. I would advise regenerating your configs for that one.
