### ISSUE TITLE
Stuff that needs recipes

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#27]
- [x] "Location Stones"
- [ ] Lanterns
- [x] Oil (Created from either veggies or sunflowers)
- [x] Liquid honey (Created by placing honey items in a cauldron)
- [ ] Add a way to obtain chiselled versions of blocks when chisel is not installed
- [ ] Add more stuff here as needed

**Comment by zabi94** [comment]
Revealing lanterns can already be crafted. It's regular lanterns that are missing

**Comment by OtisGoodman** [comment]
Location stone is done alredy.
