### ISSUE TITLE
Unexpected Crash Straight After Loading Into World

### ISSUE THREAD

**Issue by IceArrow04** [Um-Mitternacht/Bewitchment#271]
###Expected Behavior
Standard Gameplay 

### Actual Behavior
Crash instantly after loading into a the world

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, 19.30, 14.23.5.2814, 1.0-17, 1.7.17, and 1.12-1.5.2

### Logs, in the event of a crash
[crash-2019-03-01_20.01.14-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2921737/crash-2019-03-01_20.01.14-client.txt)

**Comment by Sunconure11** [comment]
This is being caused by whatever WorkshopCraft is.
