### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DrakeSayer** [Um-Mitternacht/Bewitchment#273]
### Expected Behavior
Game Loads

### Actual Behavior
Game Crashed

### Steps to Reproduce
Load Minecraft

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2 Forge 14.23.5.2772
Baubles 1.5.2
Patchouli 1.0-17
Llibrary 1.7.17
Bewitchment 0.0.19.32

### Screenshots encouraged
N/A

### Logs, in the event of a crash
https://pastebin.com/Mxgv78Zw

**Comment by Sunconure11** [comment]
Use the latest build of forge, not the recommended build. My warning regarding this is broken for some reason.
