### ISSUE TITLE
Taglocking White Bed Crash (Base Minecraft)

### ISSUE THREAD

**Issue by Ashelotte** [Um-Mitternacht/Bewitchment#275]
### Expected Behavior
Taglocking other bed results in Filled Taglock Kit

### Actual Behavior
Taglocking bed results in crash

### Steps to Reproduce
Stack of 2 Taglocks, shift right click the person's white bed while they are online. No taglock is produced on re-launch of the game, they are both empty.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2, Bewitchment 1.12.2-0.0.19.17-indev, Forge 14.23.5.2815, Patchouli 1.0-16, LLibrary 1.7.17-1.12.2, Baubles 1.12-1.5.2

### Logs, in the event of a crash
[crash-2019-03-03_02.51.26-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2922885/crash-2019-03-03_02.51.26-client.txt)

The first crash of this happened two days ago, I don't have the report for that, but the steps taken were identical.

**Comment by DaveArndt** [comment]
fixed
