### ISSUE TITLE
GL Vertices being warped for unknown reasons

### ISSUE THREAD

**Issue by Deadwinterdead** [Um-Mitternacht/Bewitchment#278]
after killing mob and dropping adder's fork and getting poisoned, the surrounding constructions were deformed

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
forge 14.23.5.2808
Bewitchment-1.12.2-0.0.19.32-indev.jar
Patchouli-1.0-17.jar
llibrary-1.7.17-1.12.2.jar
Baubles-1.12-1.5.2.jar

![2019-03-03-123135_1366x768_scrot](https://user-images.githubusercontent.com/48182413/53697744-3b02f280-3db3-11e9-81c9-428c3dd6c949.png)
![2019-03-03-123312_1366x768_scrot](https://user-images.githubusercontent.com/48182413/53697745-3b02f280-3db3-11e9-8d39-dbb2ee384c23.png)
![2019-03-03-123332_1366x768_scrot](https://user-images.githubusercontent.com/48182413/53697746-3b02f280-3db3-11e9-9804-7219ee5e60b1.png)

**Comment by zabi94** [comment]
That's definitely some other mod messing with rendering. Those are gl vertexes messing up. 
What's in your pack? If you have optifine, albedo, or any other mod that messes with rendering, try and remove that first, and see if it still happens

**Comment by Deadwinterdead** [comment]
> That's definitely some other mod messing with rendering. Those are gl vertexes messing up.
> What's in your pack? If you have optifine, albedo, or any other mod that messes with rendering, try and remove that first, and see if it still happens

i have only Bewitchmen,Patchouli,llibrary,Baubles and jei 
![2019-03-03-134513_1366x768_scrot](https://user-images.githubusercontent.com/48182413/53698378-997f9f00-3dba-11e9-87a0-d250bcae1324.png)

**Comment by zabi94** [comment]
Might be llibrary then, that's the only coremod

**Comment by Sunconure11** [comment]
LLibrary is required for the mod to run

**Comment by zabi94** [comment]
I know, but it still can be the cause

**Comment by gegy1000** [comment]
What rendering in question is being messed with?

**Comment by Sunconure11** [comment]
I'm legitimately unsure.

**Comment by gegy1000** [comment]
LLibrary could very well be causing it, but I don't believe it'd be rendering anything on its own. It'd have to be interfering with something else's rendering.

**Comment by itsmeow** [comment]
Perhaps try updating your graphics drivers? I noticed you're on a Linux distro, possible they're out of date.
