### ISSUE TITLE
Black Dog ticking entity crash on MP

### ISSUE THREAD

**Issue by xAlicatt** [Um-Mitternacht/Bewitchment#290]
### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
Seems to be random

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC-1.12.2
Bewitch-19.35-indev
Forge-2815
Patch-17
LLib1.7.17
Baub-1.5.2

### Screenshots encouraged
N/A

### Logs, in the event of a crash
https://paste.dimdev.org/ijenosiviw.sql

**Comment by zEpiixz** [comment]
https://pastebin.com/1aXTDdDJ

#metoo

**Comment by Sunconure11** [comment]
It might be a bit before the bugfix is out, as it will probably be lumped into the next build of the mod.

**Comment by DaveArndt** [comment]
We might want to roll this one out immediately. If I'm right, this will crash the server any time a black dog attacks anything
