### ISSUE TITLE
Some items not stacking

### ISSUE THREAD

**Issue by raltus** [Um-Mitternacht/Bewitchment#301]
### Expected Behavior
Items stacking with each other

### Actual Behavior

After the latest update if you split a stack it won't restack. It seems to be honeycomb, mob drops, salt, 
oak apple gall, and the gems. Silver ore, coquina, and the plant drops I've checked are all fine.

### Steps to Reproduce
Take a item that was stacked in a previous version and try restacking it after updating.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2, Bewitchment Indev 0.19.36, Patchouli 1.0-17, LLibrary 1.7.17-1.12.2, Baubles 1.12-1.5.2

### Screenshots encouraged
![2019-03-08_00 18 50](https://user-images.githubusercontent.com/21094140/54011351-d5f32800-4137-11e9-9834-b064e7082f05.png)

**Comment by Sunconure11** [comment]
For those assigned, commit this to master. I will port it over to the diabolic update branch.

**Comment by 6269329** [comment]
Silver ingots and Tourmaline don't stack either

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/54066526-8bd57980-41ff-11e9-9b1f-41ffc92e93b8.png)
k what retard did this

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/54066538-b1628300-41ff-11e9-9055-da0162ee82ca.png)
@DaveArndt reeeeeeeeeeeeeeeee
