### ISSUE TITLE
Kenaf Breaks when interacting with adjacent crops

### ISSUE THREAD

**Issue by MaragretRLautzenhiser** [Um-Mitternacht/Bewitchment#302]
The following bug was discovered on the official Bewitchment test server

### Expected Behavior
Kenaf crop remains planted regardless of actions to adjacent crops.

### Actual Behavior
When a crop is interacted with via right click, whether to plant or right click to harvest, any adjacent Kenaf crops will break and drop as seeds. This behavior prevents Kenaf from being planted in a compact manner or adjacent to other crops. This behavior has only been tested for on Rustic's Fertile soil blocks, not on vanilla tilled soil. It is unknown if the bug occurs with vanilla tilled soil.

### Steps to Reproduce
Plant kenaf adjacent to an unplanted fertile soil or a mature crop, then plant any crop on the fertile soil, or right click to harvest the adjacent plant.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2
Bewitchment 0.0.19.33
Forge 14.23.5.2815
Patchouli 1.0-17
LLibrary 1.7.17

**Comment by Sunconure11** [comment]
Put this on the master branch first as well, for those assigned. I will bring it to the update branch afterwards.

**Comment by MaragretRLautzenhiser** [comment]
After some testing, it seems to only occur on Rustic's Fertile Soil. The bug also occurs with Silphium.

**Comment by 6269329** [comment]
Silver ingots and Tourmaline don't stack either
