### ISSUE TITLE
Game Crashes due to something related to Hellhounds

### ISSUE THREAD

**Issue by caliban888** [Um-Mitternacht/Bewitchment#304]
### Expected Behavior
Game runs

### Actual Behavior
Game crashes

### Steps to Reproduce
Play on multiplayer server (may/may not be relevant). Be in same chunk as Hellhound, maybe. Hellhound could not be found at -923.50, 65.00, 1064.50, may/may not be user error.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2, Forge 14.23.5.2815, Witchery 1.12.2-0.0.19.36-indev, Patchouli 1.0-18, LLibrary 1.7.17-1.12.2, Baubles 1.12-1.5.2

### Logs, in the event of a crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 3/9/19 1:25 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at net.minecraft.entity.passive.EntityTameable.func_70909_n(SourceFile:107)
	at net.minecraft.entity.passive.EntityTameable.func_96124_cp(SourceFile:183)
	at net.minecraft.util.EntitySelectors.func_188442_a(SourceFile:91)
	at net.minecraft.entity.EntityLivingBase.func_85033_bc(EntityLivingBase.java:2439)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2396)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.bewitchment.common.entity.spirits.demons.EntityHellhound.func_70636_d(EntityHellhound.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.bewitchment.common.entity.spirits.demons.EntityHellhound.func_70071_h_(EntityHellhound.java:72)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.entity.passive.EntityTameable.func_70909_n(SourceFile:107)
	at net.minecraft.entity.passive.EntityTameable.func_96124_cp(SourceFile:183)
	at net.minecraft.util.EntitySelectors.func_188442_a(SourceFile:91)
	at net.minecraft.entity.EntityLivingBase.func_85033_bc(EntityLivingBase.java:2439)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2396)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.bewitchment.common.entity.spirits.demons.EntityHellhound.func_70636_d(EntityHellhound.java:178)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.bewitchment.common.entity.spirits.demons.EntityHellhound.func_70071_h_(EntityHellhound.java:72)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: bewitchment:hellhound (com.bewitchment.common.entity.spirits.demons.EntityHellhound)
	Entity ID: 283607
	Entity Name: Hellhound
	Entity's Exact location: -923.50, 65.00, 1064.50
	Entity's Block location: World: (-924,65,1064), Chunk: (at 4,4,8 in -58,66; contains blocks -928,0,1056 to -913,255,1071), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['caliban888'/181167, l='MpServer', x=-862.80, y=63.15, z=1107.99]]
	Chunk stats: MultiplayerChunkCache: 395, 395
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-79,64,253), Chunk: (at 1,4,13 in -5,15; contains blocks -80,0,240 to -65,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 849296 game time, 851549 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['caliban888'/181167, l='MpServer', x=-662.58, y=59.64, z=1110.76], EntitySquid['Squid'/282368, l='MpServer', x=-801.18, y=61.42, z=1094.71], EntitySquid['Squid'/282369, l='MpServer', x=-806.80, y=59.84, z=1112.55], EntityZombie['Zombie'/284929, l='MpServer', x=-813.50, y=25.00, z=1096.50], EntityItem['item.tile.coral.pink_coral'/277517, l='MpServer', x=-822.13, y=17.00, z=1161.92], EntitySkeleton['Skeleton'/285199, l='MpServer', x=-921.50, y=28.00, z=1146.50], EntityItem['item.tile.flower_1.miners_delight'/277512, l='MpServer', x=-818.13, y=13.00, z=1065.13], EntityItem['item.tile.flower_1.miners_delight'/277513, l='MpServer', x=-823.46, y=13.00, z=1066.33], EntityItem['item.tile.flower_1.miners_delight'/277514, l='MpServer', x=-821.13, y=13.00, z=1069.88], EntityShip['entity.shipmod.name'/267293, l='MpServer', x=-863.30, y=62.00, z=1107.99], EntityItem['item.tile.flower_1.miners_delight'/281629, l='MpServer', x=-829.88, y=13.00, z=1065.13], EntityItem['item.tile.flower_1.miners_delight'/281630, l='MpServer', x=-828.88, y=13.00, z=1070.18], EntityItem['item.tile.flower_1.miners_delight'/281631, l='MpServer', x=-827.88, y=13.00, z=1078.88], EntityItem['item.item.tile.rustic.core_root'/281636, l='MpServer', x=-829.88, y=13.00, z=1065.13], EntityItem['item.item.tile.rustic.core_root'/281638, l='MpServer', x=-828.88, y=13.00, z=1064.13], EntityItem['item.tile.flower_1.miners_delight'/281632, l='MpServer', x=-822.13, y=13.00, z=1070.88], EntityZombie['Zombie'/284961, l='MpServer', x=-896.81, y=28.00, z=1178.47], EntityHippocampus['Hippocampus'/267810, l='MpServer', x=-813.69, y=51.94, z=1078.84], EntitySkeleton['Skeleton'/284450, l='MpServer', x=-818.91, y=13.01, z=1066.35], EntityItem['item.item.tile.rustic.core_root'/281635, l='MpServer', x=-821.13, y=13.00, z=1069.88], EntityOtherPlayerMP['Inpaladin1'/217677, l='MpServer', x=1.50, y=83.88, z=792.12], EntityCreeper['Creeper'/283463, l='MpServer', x=-823.50, y=38.00, z=1128.50], EntitySkeleton['Skeleton'/284756, l='MpServer', x=-865.48, y=15.00, z=1067.51], EntitySquid['Squid'/282453, l='MpServer', x=-802.19, y=48.04, z=1061.73], EntityZombie['Zombie'/284757, l='MpServer', x=-864.50, y=15.00, z=1067.50], EntitySquid['Squid'/282454, l='MpServer', x=-801.30, y=48.37, z=1065.71], EntitySquid['Squid'/282455, l='MpServer', x=-800.11, y=49.26, z=1064.56], EntityCreeper['Creeper'/282193, l='MpServer', x=-816.50, y=25.00, z=1120.50], EntityHippocampus['Hippocampus'/269393, l='MpServer', x=-803.11, y=38.18, z=1157.32], EntitySpider['Spider'/284754, l='MpServer', x=-867.50, y=15.00, z=1064.50], EntityZombie['Zombie'/285011, l='MpServer', x=-827.50, y=23.00, z=1145.50], EntitySquid['Squid'/282460, l='MpServer', x=-823.70, y=54.27, z=1147.80], EntitySquid['Squid'/282461, l='MpServer', x=-818.75, y=54.29, z=1155.91], EntitySquid['Squid'/282462, l='MpServer', x=-816.34, y=55.42, z=1153.80], EntitySquid['Squid'/282463, l='MpServer', x=-823.20, y=56.40, z=1149.09], EntitySquid['Squid'/282456, l='MpServer', x=-803.63, y=50.84, z=1071.69], EntitySkeleton['Skeleton'/284529, l='MpServer', x=-786.50, y=22.00, z=1119.50], EntitySkeleton['Skeleton'/284530, l='MpServer', x=-789.50, y=22.00, z=1118.50], EntitySkeleton['Skeleton'/284531, l='MpServer', x=-789.50, y=22.00, z=1119.50], EntitySquid['Squid'/282492, l='MpServer', x=-826.61, y=58.69, z=1112.85], EntityItem['item.tile.rail'/283260, l='MpServer', x=-914.31, y=22.00, z=1156.13], EntitySquid['Squid'/282493, l='MpServer', x=-827.29, y=60.27, z=1102.54], EntitySquid['Squid'/282494, l='MpServer', x=-823.30, y=59.04, z=1113.88], EntityMinecartChest['Minecart with Chest'/283256, l='MpServer', x=-914.50, y=15.06, z=1081.50], EntityBat['Bat'/283769, l='MpServer', x=-816.51, y=20.81, z=1061.01], EntityMinecartChest['Minecart with Chest'/283257, l='MpServer', x=-916.50, y=27.06, z=1130.50], EntityItem['item.tile.torch'/283258, l='MpServer', x=-914.20, y=22.00, z=1156.13], EntitySquid['Squid'/282491, l='MpServer', x=-821.82, y=60.13, z=1112.31], EntityMinecartChest['Minecart with Chest'/283259, l='MpServer', x=-912.90, y=22.00, z=1156.49], EntitySkeleton['Skeleton'/283525, l='MpServer', x=-810.50, y=22.00, z=1173.50], EntityBat['Bat'/284558, l='MpServer', x=-885.25, y=30.02, z=1179.75], EntityZombie['Zombie'/283028, l='MpServer', x=-791.50, y=21.00, z=1109.50], EntitySkeleton['Skeleton'/283286, l='MpServer', x=-830.50, y=20.00, z=1169.50], EntitySpider['Spider'/283025, l='MpServer', x=-792.50, y=21.00, z=1107.50], EntityZombie['Zombie'/283026, l='MpServer', x=-798.96, y=22.00, z=1099.48], EntityZombie['Zombie'/283027, l='MpServer', x=-790.50, y=21.00, z=1110.50], EntityOtherPlayerMP['jockshocker'/201678, l='MpServer', x=-34.52, y=73.00, z=776.22], EntityPlayerSP['caliban888'/181167, l='MpServer', x=-862.80, y=63.15, z=1107.99], EntityCreeper['Creeper'/283564, l='MpServer', x=-819.50, y=42.00, z=1042.50], EntitySkeleton['Skeleton'/284587, l='MpServer', x=-826.50, y=21.00, z=1066.50], EntityOtherPlayerMP['Inpaladin1'/210673, l='MpServer', x=-12.10, y=75.00, z=786.99], EntityCreeper['Creeper'/283839, l='MpServer', x=-878.50, y=24.00, z=1178.50], EntitySkeleton['Skeleton'/283591, l='MpServer', x=-782.50, y=15.00, z=1096.50], EntityZombie['Zombie'/283086, l='MpServer', x=-814.50, y=21.00, z=1061.50], EntitySkeleton['Skeleton'/283854, l='MpServer', x=-814.70, y=12.00, z=1136.92], EntityZombie['Zombie'/283087, l='MpServer', x=-815.50, y=21.00, z=1062.50], EntitySkeleton['Skeleton'/283592, l='MpServer', x=-783.50, y=15.00, z=1095.50], EntitySquid['Squid'/282569, l='MpServer', x=-827.15, y=60.07, z=1073.31], EntityOtherPlayerMP['jockshocker'/201678, l='MpServer', x=-6.88, y=77.00, z=768.38], EntitySquid['Squid'/282571, l='MpServer', x=-823.35, y=58.87, z=1085.74], EntityBat['Bat'/284116, l='MpServer', x=-840.49, y=21.74, z=1153.75], EntityHellhound['Hellhound'/283607, l='MpServer', x=-923.50, y=65.00, z=1064.50], EntityBat['Bat'/284114, l='MpServer', x=-837.41, y=24.79, z=1144.06], EntityBat['Bat'/284115, l='MpServer', x=-843.96, y=22.67, z=1150.32], EntityItem['item.tile.torch'/283100, l='MpServer', x=-897.22, y=21.00, z=1084.13], EntityItem['item.tile.rail'/283101, l='MpServer', x=-901.25, y=21.00, z=1089.88], EntityItem['item.tile.rail'/283102, l='MpServer', x=-903.24, y=21.00, z=1088.32], EntityUran['Serpent'/283608, l='MpServer', x=-922.50, y=63.00, z=1066.50], EntityUran['Serpent'/283609, l='MpServer', x=-922.50, y=63.00, z=1067.50], EntityItem['item.tile.torch'/283098, l='MpServer', x=-897.13, y=28.00, z=1108.40], EntityItem['item.tile.torch'/283099, l='MpServer', x=-897.66, y=21.00, z=1094.26], EntityItem['item.tile.rail'/283104, l='MpServer', x=-904.24, y=21.00, z=1089.10], EntitySquid['Squid'/282350, l='MpServer', x=-820.29, y=53.33, z=1070.75], EntitySquid['Squid'/282351, l='MpServer', x=-823.50, y=50.17, z=1073.17], EntitySquid['Squid'/282352, l='MpServer', x=-822.21, y=52.82, z=1070.88], EntitySkeleton['Skeleton'/284409, l='MpServer', x=-849.68, y=33.52, z=1082.42]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 810752984 bytes (773 MB) / 3025141760 bytes (2885 MB) up to 3937402880 bytes (3755 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4224m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                      | Source                                            | Signature                                |
	|:------ |:-------------------------------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                       | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                                          | 9.42                         | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                    | forge-1.12.2-14.23.5.2815-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2815                 | forge-1.12.2-14.23.5.2815-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | smoothfontcore                               | mc1.12.2-1.16                | minecraft.jar                                     | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                              | minecraft.jar                                     | None                                     |
	| LCHIJA | openmodscore                                 | 0.12.1                       | minecraft.jar                                     | None                                     |
	| LCHIJA | smoothfont                                   | mc1.12.2-1.16.2              | SmoothFont-mc1.12.2-1.16.2.jar                    | None                                     |
	| LCHIJA | aether_legacy                                | 1.12.2-v1.4.0                | aether_legacy-1.12.2-v1.4.0.jar                   | None                                     |
	| LCHIJA | architecturecraft                            | @VERSION@                    | architecturecraft-1.12-3.80.jar                   | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                        | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | astralsorcery                                | 1.10.11                      | astralsorcery-1.12.2-1.10.11.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | jei                                          | 4.15.0.269                   | jei_1.12.2-4.15.0.269.jar                         | None                                     |
	| LCHIJA | quark                                        | r1.5-146                     | Quark-r1.5-146.jar                                | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-26                       | AutoRegLib-1.3-26.jar                             | None                                     |
	| LCHIJA | betterbuilderswands                          | 0.13.0                       | BetterBuildersWands-1.12.2-0.13.0.267+dc89c58.jar | None                                     |
	| LCHIJA | patchouli                                    | 1.0-18                       | Patchouli-1.0-18.jar                              | None                                     |
	| LCHIJA | llibrary                                     | 1.7.17                       | llibrary-1.7.17-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | bewitchment                                  | @VERSION@                    | Bewitchment-1.12.2-0.0.19.36-indev.jar            | None                                     |
	| LCHIJA | bibliocraft                                  | 2.4.5                        | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHIJA | biomesoplenty                                | 7.0.1.2425                   | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar     | None                                     |
	| LCHIJA | chameleon                                    | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | ctm                                          | MC1.12.2-0.3.3.22            | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCHIJA | chisel                                       | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.42                | Mantle-1.12-1.3.3.42.jar                          | None                                     |
	| LCHIJA | natura                                       | 1.12.2-4.3.2.66              | natura-1.12.2-4.3.2.66.jar                        | None                                     |
	| LCHIJA | rustic                                       | 1.0.6                        | rustic-1.0.6.jar                                  | None                                     |
	| LCHIJA | thaumcraft                                   | 6.1.BETA26                   | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCHIJA | twilightforest                               | 3.8.689                      | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.12.0.115            | TConstruct-1.12.2-2.12.0.115.jar                  | None                                     |
	| LCHIJA | immersiveengineering                         | 0.12-89                      | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | clochecall                                   | 1.1.1                        | ClocheCall-1.1.1.jar                              | None                                     |
	| LCHIJA | conarm                                       | 1.2.3                        | conarm-1.12.2-1.2.3.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked                        | 1.12.2-v4                    | CosmeticArmorReworked-1.12.2-v4.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | tombmanygraves2api                           | 1.12.2-1.0.0                 | tombmanygraves2api-1.12.2-1.0.0.jar               | None                                     |
	| LCHIJA | tombmanygraves                               | 1.12-4.1.0                   | TombManyGraves-1.12-4.1.0.jar                     | None                                     |
	| LCHIJA | cosmeticarmorreworked|tombmanygraves         | 1.12.2-v4                    | CosmeticArmorReworked-1.12.2-v4.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | movingworld                                  | 1.12-6.342                   | movingworld-1.12-6.342-full.jar                   | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@                | davincisvessels-1.12-6.340-full.jar               | None                                     |
	| LCHIJA | endercompass                                 | 1.2.6.2                      | EnderCompass-1.12-1.2.6.2.jar                     | None                                     |
	| LCHIJA | extraalchemy                                 | 0.3.8.6.1-release            | extraalchemy-0.3.8.6.1-release.jar                | None                                     |
	| LCHIJA | fairylights                                  | 2.1.5                        | fairylights-2.1.5-1.12.2.jar                      | None                                     |
	| LCHIJA | forgelin                                     | 1.7.4                        | Forgelin-1.7.4.jar                                | None                                     |
	| LCHIJA | waila                                        | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | iceandfire                                   | 1.6.1                        | iceandfire-1.6.1-1.12.2.jar                       | None                                     |
	| LCHIJA | immersivepetroleum                           | 1.1.9                        | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| LCHIJA | immersivetech                                | 1.3.10                       | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| LCHIJA | inventorytweaks                              | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks                                | 1.12.2-3.0.8-12              | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.44.829            | ironchest-1.12.2-7.0.44.829.jar                   | None                                     |
	| LCHIJA | journeymap                                   | 1.12.2-5.5.3                 | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LCHIJA | librarianlib                                 | 9.4                          | librarianlib-1.12.2-4.9.jar                       | None                                     |
	| LCHIJA | testdummy                                    | 1.12                         | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
	| LCHIJA | moreoverlays                                 | 1.14                         | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
	| LCHIJA | morpheus                                     | 1.12.2-3.5.106               | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
	| LCHIJA | naturescompass                               | 1.5.1                        | NaturesCompass-1.12.2-1.5.1.jar                   | None                                     |
	| LCHIJA | openmods                                     | 0.12.1                       | OpenModsLib-1.12.2-0.12.1.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                                   | 1.8                          | OpenBlocks-1.12.2-1.8.jar                         | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | quickleafdecay                               | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar                 | None                                     |
	| LCHIJA | storagedrawers                               | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.7.jar                   | None                                     |
	| LCHIJA | supersoundmuffler                            | 1.0.2.9                      | supersoundmuffler-1.12.1-1.0.2.9.jar              | None                                     |
	| LCHIJA | tcinventoryscan                              | 2.0.10                       | ThaumicInventoryScanning_1.12.2-2.0.10.jar        | None                                     |
	| LCHIJA | thaumicjei                                   | 1.2.1                        | ThaumicJEI-1.12.2-1.5.5-23.jar                    | None                                     |
	| LCHIJA | tinkersaether                                | 1.2.1                        | tinkersaether-1.2.1.jar                           | None                                     |
	| LCHIJA | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769     | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCHIJA | torchmaster                                  | 1.6.4.62                     | torchmaster_1.12.2-1.6.4.62.jar                   | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | waystones                                    | 4.0.63                       | Waystones_1.12.2-4.0.63.jar                       | None                                     |
	| LCHIJA | librarianliblate                             | 9.4                          | librarianlib-1.12.2-4.9.jar                       | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
  bre.smoothfont.asm.Transformer
LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by itsmeow** [comment]
[EntityMultiSkin's DataManager Key](https://github.com/Um-Mitternacht/Bewitchment/blob/c94c843db212bad29c0e8b0d259a4114c33eb7b0/src/main/java/com/bewitchment/common/entity/living/EntityMultiSkin.java#L16) is not loading correctly. I've observed this in BA+ when registering under the wrong class. Make sure nowhere in the mod is there a non-matching class. May also be caused by other mods- can't be sure.
