### ISSUE TITLE
User reported error on servers

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#305]
https://pastebin.com/raw/kX8vJc87

**Comment by itsmeow** [comment]
Duplicate of #268

**Comment by draeman8** [comment]
i also had this crash :^)
you're great by the way i love you

**Comment by ghost** [comment]
Our server still gets this crash
Is there a fix yet?

**Comment by Sunconure11** [comment]
We're working on a rewrite, a lot of issues should be gone when it's out.
