### ISSUE TITLE
[Suggestion] Creative-only item, for quick testing altar stuff, like Witchery Infinity Egg.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#309]

**Comment by ghost** [comment]
Has this been done yet?

**Comment by ghost** [comment]
If not I can work on it

**Comment by cybercat5555** [comment]
We have plans for this in the rewrite, with the block in question known as the "Blessed Stone," if you want you could offer a hand

**Comment by ghost** [comment]
alright should I just do a pull request?

I can work on the actual block but It might not have a texture.

**Comment by cybercat5555** [comment]
a PR would be fine, just make sure it uses the things in the rewrite over the main branch. A texture for the block has been made as well, for later

**Comment by ghost** [comment]
so put in in the rewrite branch?

**Comment by Sunconure11** [comment]
Implemented, albeit as the blessed stone.
