### ISSUE TITLE
Perhaps, Shinies fortune don't work.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#310]
### Expected Behavior
After activating crystal ball and receive message "Something glimmers in my sight." mine stone and get jewel.

### Actual Behavior
I have just spawned and mined a few stacks of stone, cobblestone, sandstone, and red sandstone with Fortune III diamond pickaxe, and have not received a single jewel.

### Steps to Reproduce
Get fortune Shinies and mine stone.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2
Bewitchment Indev 0.19.38
Fogre 14.23.5.2815 
Patchouli-1.0-18
llibrary-1.7.18-1.12.2
Baubles-1.12-1.5.2

**Comment by zabi94** [comment]
Fortunes activate after a random amount of time. Wait some time or use /activateFortune to force it to become true as soon as possible
