### ISSUE TITLE
Moonbell crashing server during postinit

### ISSUE THREAD

**Issue by draeman8** [Um-Mitternacht/Bewitchment#313]
### Expected Behavior
To Start up with the server

### Actual Behavior
Crashes the server; had an issue with the "IllegalAccessError" that has since been fixed with the newest update, now giving error saying "ArrayIndexOutofBounds"

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Latest

### Screenshots encouraged
N/A

### Logs, in the event of a crash
[crash-2019-03-12_22.59.02-server.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2959621/crash-2019-03-12_22.59.02-server.txt)

**Comment by itsmeow** [comment]
Actual Error:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.util.ArrayList.add(ArrayList.java:463)
	at com.bewitchment.common.block.natural.plants.BlockMoonbell.addValidMoonbellBiome(BlockMoonbell.java:45)
```
I believe @CammiePone wrote the Moonbell? Take a look at this please.
