### ISSUE TITLE
Girdle Of The Dryads lose all charges after save reload.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#314]
### Steps to Reproduce
Get any amount of charges using waiting or potion, then reload.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2
Bewitchment Indev 0.19.40
Fogre 14.23.5.2815
Patchouli-1.0-18
llibrary-1.7.18-1.12.2
Baubles-1.12-1.5.2

### Screenshots encouraged
Before reload.
![2019-03-13_22 47 57](https://user-images.githubusercontent.com/48053759/54310225-efd2b600-45e2-11e9-8f93-e2928678cf18.png)
After reload.
![2019-03-13_22 48 12](https://user-images.githubusercontent.com/48053759/54310278-0c6eee00-45e3-11e9-9315-03d38b22944d.png)

**Comment by itsmeow** [comment]
[BarkCapability.java](https://github.com/Um-Mitternacht/Bewitchment/tree/master/src/main/java/com/bewitchment/common/core/capability/simple/BarkCapability.java) needs write to nbt and read from nbt overriden and the proper values saved.
