### ISSUE TITLE
Mending and Absorbing Brews have the same recipes, but only mending can be brewd. Also, both brews have Enchanted Golden Apple effect, independent of modifiers. Throwable Mending don't work at mycelium.

### ISSUE THREAD

**Issue by Sidnatum** [Um-Mitternacht/Bewitchment#316]
### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft 1.12.2
Bewitchment Indev 0.19.40
Fogre 14.23.5.2815
Patchouli-1.0-18
llibrary-1.7.18-1.12.2
Baubles-1.12-1.5.2

### Screenshots encouraged
![2019-03-14_00 07 58](https://user-images.githubusercontent.com/48053759/54314828-bbb0c280-45ed-11e9-878d-4306a2659dc8.png)

**Comment by Sunconure11** [comment]
Fixed in the next major update.
