### ISSUE TITLE
Forge server error

### ISSUE THREAD

**Issue by darkness3285** [Um-Mitternacht/Bewitchment#324]
The mod bewitchment is expecting signature @FINGERPRINT@ for source Bewitchment-1.12.2-0.0.19.43-indev.jar, however there is no signature matching that description
[09:59:30] [Server thread/WARN] [Bewitchment]: !! WARNING: The mod Bewitchment has an invalid signature, this is likely due to someone messing with the jar without permission!

forge-1.12.2-14.23.5.2772-universal
Patchouli-1.0-18
llibrary-1.7.18-1.12.2
Baubles-1.12-1.5.2
Bewitchment-1.12.2-0.0.19.43-indev

**Comment by Sunconure11** [comment]
Fingerprint system is broken.

Also, use the LATEST build of forge, not the recommended.
