### ISSUE TITLE
Flowers from Flowers Spring effect too aggressive

### ISSUE THREAD

**Issue by daforsyth** [Um-Mitternacht/Bewitchment#326]
### Expected Behavior
Flowers spawn around the player.

### Actual Behavior
Flowers seem to spawn on any dirt regardless of obstacles, causing it to break redstone and salt lines. Occasionally it also attempts to replace a block causing a visual glitch.

### Steps to Reproduce
Drink a flower spring potion IV and stand near redstone.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Versions being used for the most recent update of the Bewitchment pack.

### Screenshots encouraged
N/a

**Comment by Sunconure11** [comment]
I'll see about toning this down once the rewrite is complete.
