### ISSUE TITLE
Tweaks needed for the rewrite

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#328]
- [ ] State what each upgrade does to the altar, in a tooltip on each item. If numbers must be added, make them vague, rounded numbers.
- [ ] Port over the rest of the new names from the docs
- [ ] Natural Tree Gen
- [ ] More to add here later

**Comment by Gabby2805** [comment]
- [ ] Fix mob spawns and mob damage/hitboxes

- [ ] Include a better in-game guide that's more step-by-step and makes objectives clear, something along the lines of the Thaumonomicon in Thaumcraft

**Comment by CammiePone** [comment]
Small problem with that last one, Gabby. Bewitchment isn't as linear as Thaumcraft is. It's extremely open-ended for what you do after you have the basic stuff made, which I believe there's a section for the basic items/tile entities.

**Comment by Gabby2805** [comment]
Yes that's understandable and don't get me wrong its a good trait the mod has. However, I just don't think its features are boasted enough, it doesn't really show you the cool things you can do easily enough. I thought Witchery had the same problem, I remember watching and re-watching videos in a youtube series and having to take notes just to find out what I can and should do with it.
