### ISSUE TITLE
Will not start up

### ISSUE THREAD

**Issue by madlyb2246** [Um-Mitternacht/Bewitchment#330]
### Expected Behavior
To start

### Actual Behavior
Shows the normal forge loading and then stops

### Steps to Reproduce
click play

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
latest

### Logs, in the event of a crash
It said this:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bewitchment (bewitchment)

**Comment by vruska** [comment]
i know this is kinda late but is java updated? i had this exact problem before i updated java.
