### ISSUE TITLE
Server crash using ritual of marks

### ISSUE THREAD

**Issue by NightScythe1987** [Um-Mitternacht/Bewitchment#340]
### Expected Behavior

I performed the ritual of marks on my server (not the first time i used it, which was strange)
### Actual Behavior

Seconds after initiating, the server crashed. It was able to restart again, but whenever i tried to join back it would crash again. Only removing the mod from both server AND client removed the crash, removing it from just the server still caused a crash when joining.
### Steps to Reproduce
Perform ritual of the marks on a server, i haven't been able to attempt a reproduce yet.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used

MInecraft 1.12.2, Bewitchment-1.12.2-0.0.19.44-indev, Forge 1.12.2 14.23.5.2814, Patchouli 1.0-18, LLibrary 1.7.18, Baubles-1.12-1.5.2.jar
### Logs, in the event of a crash
[https://pastebin.com/DVQQMfpg](url)

**Comment by Sunconure11** [comment]
Unable to reproduce, and also the mod is being rewritten.
