### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by AwenKhari** [Um-Mitternacht/Bewitchment#341]
### Expected Behavior
I was simply playing the game, building a house, and not even using any of the features of the mods at all.

### Actual Behavior
The game crashes unexpectedly. The first time was while I was punching grass. The second I was punching a tree.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MInecraft 1.12.2, Bewitchment-1.12.2-0.0.19.44-indev, Forge 1.12.2 14.23.5.2814, Patchouli 1.0-18, LLibrary 1.7.18, Baubles-1.12-1.5.2.jar

### Logs, in the event of a crash
Crash report: https://pastebin.com/HyEe2e8a

**Comment by IssaMeMino** [comment]
I'm having the exact same crash.

**Comment by Sunconure11** [comment]
Unable to reproduce, and also the mod is being rewritten.
