### ISSUE TITLE
Issue with the Book of Shadows

### ISSUE THREAD

**Issue by ItsFadez** [Um-Mitternacht/Bewitchment#344]
### Expected Behavior
When one opens the book there are supposed to be multiples categories to select.

### Actual Behavior
When I open the book however, it says: "bewitchment:patchouli_books/codex_infernalis/en_us/categories/nethers_firstborn.json does not exist." Upon inspecting the log I found it was complaining about other components missing.

### Steps to Reproduce
I had just crafted the book and whenever I open it, it still shows this message.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Minecraft: 1.12.2, Bewitchment: 0.19.47, Forge: 14.23.5.28.38, Patchouli: 1.0-1.9 LLibrary: 1.7.19, Baubles: 1.12-1.5.2

### Screenshots encouraged
![2019-05-20_13 20 07](https://user-images.githubusercontent.com/50841434/58039897-0e34c080-7b02-11e9-8ba8-810e5f63c79d.png)

### Logs, in the event of a crash
[2019-05-20-7.log.gz](https://github.com/Um-Mitternacht/Bewitchment/files/3199009/2019-05-20-7.log.gz) This is the most recent log I have

**Comment by Sunconure11** [comment]
I am unable to replicate this.
