### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by craftyrhenvar** [Um-Mitternacht/Bewitchment#348]
Not sure if this is an issue with Bewitchment or another mod i have installed, but i get this crash on generating a new world.

**Expected Behaviour**
No crash

**Actual Behaviour**
Crashing

**Steps to Reproduce**
Load world

**Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used**
Bewitchment - 0.0.19.47
Forge - 14.23.5.2838
Patchoui - 1.0-19
Llibrary - 1.7.19
Baubles - 1.5.2

**Screenshots encouraged**
**Logs, in the event of a crash**
https://pastebin.com/ZpCrP3yd

[crash-2019-05-28_17.55.10-server.txt](https://github.com/Um-Mitternacht/Bewitchment/files/3232998/crash-2019-05-28_17.55.10-server.txt)

**If this is a question, developer commentary, or a suggestion, ignore this template**

**Comment by craftyrhenvar** [comment]
Update: Seems to be that changing "I:silver_min_vein=1" in the config to "I:silver_min_vein=0" causes the crash.

**Comment by MoriyaShiine** [comment]
And this why you don't allow rand.nextInt(0) :P

This is fixed in the rewrite, but for now, if you're trying to disable silver spawns, set the max and min height to 1, that'll cause it to attempt generating on bedrock and fail.

**Comment by craftyrhenvar** [comment]
Thanks for the tip, and the quick reply :)

**Comment by MoriyaShiine** [comment]
No problem :D
