### ISSUE TITLE
Galacticraft compatibility issue

### ISSUE THREAD

**Issue by jinkhya** [Um-Mitternacht/Bewitchment#368]
Hello !
The server console is spamming this : https://pastebin.com/X78quzTQ 
It doesn't crash and seems to be working fine, the spam worries me though.
Thanks in advance
Jin

**Comment by CammiePone** [comment]
It would be nice if Galacticraft were open sourced, so we could know exactly what is happening. Do you have any other mods installed?

**Comment by jinkhya** [comment]
I do yes, here's the modlist:  
https://pastebin.com/YZsRPwDi
