### ISSUE TITLE
Editing bewitchment_entities.cfg is not working. I cannot step foot in the Nether.

### ISSUE THREAD

**Issue by Gabby2805** [Um-Mitternacht/Bewitchment#370]
As you already know, the spawns are out of control. I was really happy when I came across the config file for the entities so I could reduce their numbers or completely disable them...unfortunately, it does not work.

I literally cannot survive for a few minutes in the nether due to the ridiculous number of serpents (not found in the config file anyway) and the hellhounds and the ridiculous strength and health of the alpha hellhounds. I tried to disable the alpha hellhounds completely, but they are still in my game.

`
```
entityhellhoundalpha {
                            # Disables natural spawning [default: true]
                            B:doSpawning=false
```

                            # Must be greater or equal to min value! [range: 1 ~ 9999, default: 1]
                            I:maxGroup=0

                            # Must be greater than 0 [range: 1 ~ 9999, default: 1]
                            I:minGroup=0

                            # Enter biome Resource Locations. Supports modded biomes. [default: [minecraft:hell]]
                            S:spawnBiomes <
                                minecraft:hell
                             >

                            # The spawn chance compared to other animals (typically between 6-20) [range: 1 ~ 9999, default: 1]
                            I:weight=0
                        }`

I'm sure this will be addressed in the new version but for now I want to keep playing Minecraft and I do not want to break my save by removing or updating the mod. I'm a computer science student so I have some knowledge of programming, so if you can talk me through a DIY method of fixing these spawns, please please tell me. I'm willing to put the effort in.

Thank you

**Comment by Sunconure11** [comment]
Gamerules are per world. I would suggest trying that until the next update, but that might stop spawning of other mobs in the nether.

**Comment by Gabby2805** [comment]
> Gamerules are per world. I would suggest trying that until the next update, but that might stop spawning of other mobs in the nether.

Thanks. Do you know how/where I can figure this for a specified world?

**Comment by Sunconure11** [comment]
Enter the nether and run the command there

**Comment by Gabby2805** [comment]
> Enter the nether and run the command there

I'm sorry, what command? If there's a command that just disables all mobs then its not really a solution, blaze rods are one of the main reasons of going to the nether... thanks for your time though.
