### ISSUE TITLE
[Rewrite - 0.0.20] Witches Oven Smelts Charcoal With Nothing in Input, Mod Conflict With Wizardry

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#373]
### Expected Behavior
Oven should do nothing with only fuel in input slot.

### Actual Behavior
With fuel in oven, it smelts nothing into an output of charcoal.

### Steps to Reproduce
1. Place oven down.
2. Place any kind of fuel into fuel slot.
3. It should start cooking into charcoal, constantly until the fuel runs dry.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW: 0.0.20
Forge: 14.23.5.2838
Baubles: 1.5.2
Patchouli: 1.0-20

**Comment by MoriyaShiine** [comment]
can't seem to reproduce this

**Comment by TechnoMysterio** [comment]
Looks like it's a mod conflict issue of some kind. I'm going through uninstalling and reinstalling mods to see which one was causing it, though I've had no luck so far. I'll report back if I find anything.

**Comment by TechnoMysterio** [comment]
I've found the culprit: it's Wizardry. The one with liquid mana and the customisable magic spells, not to be confused with EB's Wizardry. No idea why that mod in particular is making the oven cooking charcoal all by itself, but it is definitely that one, it's depenencies of LibrarianLib and Forgelin do _not_ cause the issue when installed by themselves, the issue only arises when Wizardry is installed.

**Comment by Sunconure11** [comment]
https://github.com/TeamWizardry/Wizardry/issues/295

**Comment by SaadArdati** [comment]
wtf

**Comment by TechnoMysterio** [comment]
Is this related to #397 in some way? If so, might it be something to do with furance recipes? Wizardry has a new kind of wood log in it, so I'm wondering if it has a wood to charcoal furnace recipe that's interfering with the Oven in some way, and if something similar might be going on with Ice and Fire's Silver Ore/Ingots.

**Comment by SaadArdati** [comment]
I doubt that issue is related.

**Comment by MoriyaShiine** [comment]
Is this still a thing?

**Comment by TechnoMysterio** [comment]
Yep, this is still a problem.

**Comment by TechnoMysterio** [comment]
A further discovery to this unusual issue: with Natural Pledge installed, this exact same issue appears, charcoal appears from nothing in the oven. Natural Pledge uses LibrarianLib as a dependency, so I think that something with LibrarianLib is what's causing the problem here, or maybe with how dependent mods use it.

**Comment by Zygus42** [comment]
Was just going to mention that we're seeing the issue as well, and we are using Natural Pledge, but not using Wizardry.

bewitchment-1.12.2-0.0.20.8
librarianlib-1.12.2-4.19.2-release
NaturalPledge-r3.1.2

**Comment by marklinndsa** [comment]
Had a similar issue with it generating terracotta instead. Don't have Wizardry or Natural Pledge.

Minecraft: 1.12.2
Bewitchment: 0.0.21.4
Forge: 1.12.2-14.23.5.2846
Patchouli: 1.0-20
Baubles: 1.5.2

**Comment by Sunconure11** [comment]
You are using an out of date build of BW.

**Comment by Hate9** [comment]
I'm still having this issue, and I'm using version 0.0.21.6 of Bewitchment and version 4.20 of LibrarianLib.

**Comment by Sunconure11** [comment]
Can you post any kind of log?
