### ISSUE TITLE
[Rewrite - 0.0.20] Book of Shadows, Missing Details and Info Snippets

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#375]
I shan't adhere to the standard bug report format for this, since this is just some observations of things that seemed to be missing from the Book of Shadows. The Codex Infernalis seemed alright, so I'll ignore that for the meantime. Anyway...

- Altar section doesn't say that you need to put a carpet (of any colour) on the altar to complete it.
- Brew section doesn't detail Rustic brew effects, whenever Rustic is installed.
- No mention of Perpetual Ice and Embittered Blocks, what they can do, how to get them etc. Took me a while to figure out how to use the Ice World brew to make them, so detailing this would be useful for players.
- Broom section doesn't detail differences between Brooms, might confuse players if they choose a broom that acts in a way they didn't expect. I also can't find any mention that Brooms need Magic Power from a Grimoire in order to fly.
- Devices section overview says 'needs text'.

**Comment by MoriyaShiine** [comment]
rustic isn't possible, otherwise the book would show an empty recipe with a description that doesn't match.the others have been fixed, aside from the Devices section.
