### ISSUE TITLE
[Rewrite - 0.0.20.1] Eye of Old Used In Both Night Vision and Water Breathing Brews

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#382]
The Eye of Old is used to make both Night Vision and Water Breathing Brews. Is this correct? It doesn't seem like it at first glance at least. When I make a brew using a mandrake and an eye of old I get a brew with Night Vision and Water Breathing on it, which seems odd.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW: 0.0.20.1
Forge: 14.23.5.2838
Baubles: 1.5.2
Patchouli: 1.0-20

**Comment by MoriyaShiine** [comment]
it's intended
