### ISSUE TITLE
[Rewrite - 0.0.20.1] Bird Flying Animation Plays in Strange Ways

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#383]
Birds, so the owl or the raven, play their flying animation at times where it doesn't really make sense. They tend to enter their flying animation when swimming, or if they are pushed right to the edge of a block that drops down a level.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW: 0.0.20.1
Forge: 14.23.5.2838
Baubles: 1.5.2
Patchouli: 1.0-20

### Screenshots encouraged
![2019-07-25_18 34 18](https://user-images.githubusercontent.com/5113920/61895576-e7807500-af0a-11e9-9a7d-f30ad5473df6.png)
![2019-07-25_18 34 30](https://user-images.githubusercontent.com/5113920/61895586-ed765600-af0a-11e9-9ac0-348229e60fb3.png)
![2019-07-25_18 35 32](https://user-images.githubusercontent.com/5113920/61895636-07179d80-af0b-11e9-9895-fc40c4f59739.png)

**Comment by itsmeow** [comment]
Water thing is not an issue, makes sense. This really seems too minor for going through the hassle of hitbox checks every frame- since the checks are handled on the client.
