### ISSUE TITLE
[Suggestion] Entity spawn chance config

### ISSUE THREAD

**Issue by stevesloven** [Um-Mitternacht/Bewitchment#384]
It would be good to have settings for spawn weight of mobs.

**Comment by itsmeow** [comment]
Isn't this a thing, didn't I make this? @MoriyaShiine was this removed?

**Comment by Sunconure11** [comment]
@itsmeow Moriya removed your old system, yes.

**Comment by Gabby2805** [comment]
There is a config file for entities but changing it isn't working for me.

**Comment by itsmeow** [comment]
Why is this being ignored, this is a useful and needed feature

**Comment by MoriyaShiine** [comment]
What part isn't working?

**Comment by MoriyaShiine** [comment]
Closing this since no response
