### ISSUE TITLE
Incompatibility Crash with Abyssalcraft

### ISSUE THREAD

**Issue by MokahTGS** [Um-Mitternacht/Bewitchment#385]
Getting a crash with bewitchment-1.12.2-0.0.20.3 and Abyssalcraft with launching in SP.

Full Mod list: https://paste.dimdev.org/yamobucovu.md

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Forge 2838
Baubles-1.12-1.5.2
bewitchment-1.12.2-0.0.20.3
Patchouli-1.0-20

### Logs, in the event of a crash
https://paste.dimdev.org/kaloqodufe.mccrash

**Comment by MoriyaShiine** [comment]
this is something they need to fix on their end, notify them
