### ISSUE TITLE
[Rewrite - 0.0.20.3] Visual Feedback/Effect Tweaks

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#389]
Visual feedback is an important thing to get right in mods, since it can immediately tell a player if something is connected to something else, if it's working, if something's gone wrong, etc etc. Bewitchment might do with some tweaking for this in a few different areas, since it can be unclear as to why exactly something isn't working properly, or why something is acting the way it is.

- Special particle effect for teleportation Cauldrons. With Dimensional Sand thrown in a Cauldron, it'd be good to have a green swirling effect appear above the cauldron that makes it clear that you're supposed to stand on top of it in order to teleport with it. It'd also be good to clarify how such a cauldron works with/without a nearby altar, since it took me a while to discover that the cauldron mixture turns brown and stops working after teleporting if you don't have an altar nearby.
- Spinning Wheel animation, to make it clear that it's doing something.
- For any MP powered device that has a GUI of some kind (Spinning Wheel, Distillery), have a little status icon in the GUI that shows whether it's receiving power or not, perhaps even making it flash if you try to craft something with the device to show that it needs power in order to start making stuff. Witchery had this, where a little cross appeared such a device didn't have altar power.
- Particle effect or other visual effect that trails from Altars and into MP-using things of any kind. This would include things like a Witches Cauldron, a Distilley, Ritual Circles, players with a Grimoire Magia, that kind of thing. It might also be good to vary this effect based on how the power is being used, so a small faint trail for things that are connected but not using power, a clearer trail for things that are actively using power (devices, active Rituals), and perhaps they can turn either vanish or turn red if they're not getting enough power in order to work. It might also be good to have a way to show the area in which the altar will provide energy to, perhaps this area could be shown when you right-click the altar.
- Particle or other visual effect to show what plants in the area are boosting the altar. This would be best kept fairly subdued, otherwise big farms might get a bit overwhelming. Try to make it clear what's providing a bigger boost, or what's not having much effect, probably via the intensity of the particle effect. It might also be good to have a way to show the area in which the altar will draw energy from, perhaps this area could be shown when you right-click the altar.
- Have items on an altar glow or produce red particles if they're not doing much to boost it, like if another item is already filling the same category.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW: 0.0.20.3
Forge: 14.23.5.2838
Baubles: 1.5.2
Patchouli: 1.0-20

**Comment by PresquePlayed** [comment]
awesome Ideas 
I'd love to see it in the future
