### ISSUE TITLE
I have problem with the one trinket.

### ISSUE THREAD

**Issue by guide-for-you** [Um-Mitternacht/Bewitchment#392]
Hellish Bauble can obtain some damage from explosion and fire by using ME(Grimoire Magicka),but for some reason when I equip this in Bauble menu and take damage from explosion and fire(with fully charged Grimoire Magicka),it's don't obtain.

**Comment by MoriyaShiine** [comment]
???

**Comment by guide-for-you** [comment]
Sorry if I made something stupid.
