### ISSUE TITLE
Belladonna (?) crashing the game.

### ISSUE THREAD

**Issue by Kdschar** [Um-Mitternacht/Bewitchment#394]
### Expected Behavior

Not crashing.

### Actual Behavior

Crashing.

### Steps to Reproduce

I'm not entirely sure what's causing this crash, but if I'm reading the crash report correctly, and there's a very good chance I'm not, I think it might be the belladonna plant reaching maturity on a loamy farmland block. 

I had this crash before, and when I reloaded my game, I went and harvested the belladonna. All seemed well until, I imagine, it was ready to be harvested again, hence another crash. My plan right now is to try farming it on a vanilla dirt block and see if that helps anything.

I was doing different things each time I got a crash, like walking around and just playing the game. I don't remember any specific pattern of behavior before a crash, nor was I interacting with any of the Bewitchment crops when it happened.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2
Bewitchment: 1.12.2-0.0.20.1
Forge: 14.23.5.2838
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

### Logs, in the event of a crash

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  LoadingPlugin (NoNausea-MC1.12-1.0.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/28/19 5:49 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=bewitchment:crop_belladonna, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:227)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:270)
	at com.bewitchment.common.block.crop.BlockCropsSpreading.func_180650_b(BlockCropsSpreading.java:24)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:227)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:270)
	at com.bewitchment.common.block.crop.BlockCropsSpreading.func_180650_b(BlockCropsSpreading.java:24)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)

-- Affected level --
Details:
	Level name: Mo Witches!
	All players: 1 total; [EntityPlayerMP['Ederyn'/295, l='Mo Witches!', x=529.84, y=73.91, z=-634.22]]
	Chunk stats: ServerChunkCache: 914 Drop: 0
	Level seed: -915290079
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (184,64,248), Chunk: (at 8,4,8 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 883258 game time, 2892 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 163938 (now: false), thunder time: 21938 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1496546104 bytes (1427 MB) / 6537871360 bytes (6235 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10g -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                         | Source                                        | Signature                                |
	|:------ |:--------------------------- |:------------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2                          | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42                            | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99                       | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2838                    | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dsurroundcore               | 3.5.4.3                         | minecraft.jar                                 | None                                     |
	| LCHIJA | infinitylib                 | 1.12.2-1.12.0                   | infinitylib-1.12.0.jar                        | None                                     |
	| LCHIJA | agricraft                   | 2.12.0-1.12.0-a6                | AgriCraft-2.12.0-1.12.0-a6.jar                | None                                     |
	| LCHIJA | akashictome                 | 1.2-12                          | AkashicTome-1.2-12.jar                        | None                                     |
	| LCHIJA | aquaculture                 | 1.6.8                           | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCHIJA | autoreglib                  | 1.3-32                          | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | backpack                    | 3.0.2                           | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LCHIJA | baubles                     | 1.5.2                           | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | forgelin                    | 1.8.3                           | Forgelin-1.8.3.jar                            | None                                     |
	| LCHIJA | betterfoliage               | 2.2.0                           | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
	| LCHIJA | patchouli                   | 1.0-20                          | Patchouli-1.0-20.jar                          | None                                     |
	| LCHIJA | bewitchment                 | 0.20                            | bewitchment-1.12.2-0.0.20.1.jar               | None                                     |
	| LCHIJA | bibliocraft                 | 2.4.5                           | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHIJA | biomesoplenty               | 7.0.1.2439                      | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar | None                                     |
	| LCHIJA | birdsnests                  | 2.1.0                           | BirdsNests1.12.2-2.1.0.jar                    | None                                     |
	| LCHIJA | bowinfinityfix              | rv5.1                           | BowInfinityFix-1.12.2-rv5.1.jar               | None                                     |
	| LCHIJA | jei                         | 4.15.0.268                      | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCHIJA | mantle                      | 1.12-1.3.3.55                   | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct                  | 1.12.2-2.12.0.157               | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
	| LCHIJA | ceramics                    | 1.12-1.3.7                      | Ceramics-1.12-1.3.7.jar                       | None                                     |
	| LCHIJA | chameleon                   | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | claybucket                  | 1.1                             | ClayBucket-1.12-1.1.jar                       | None                                     |
	| LCHIJA | creeperconfetti             | 1.4.2                           | creeperconfetti-1.4.2.jar                     | None                                     |
	| LCHIJA | ptrmodellib                 | 1.0.4                           | PTRLib-1.0.4.jar                              | None                                     |
	| LCHIJA | props                       | 2.6.2                           | Decocraft-2.6.2_1.12.2.jar                    | None                                     |
	| LCHIJA | dirt2path                   | 1.7.1                           | dirt2path-1.8.0.jar                           | None                                     |
	| LCHIJA | dynamiclights               | 1.4.9                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_onfire        | 1.0.7                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_creepers      | 1.0.6                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_dropitems     | 1.1.0                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_entityclasses | 1.0.1                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_mobequipment  | 1.1.0                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_flamearrows   | 1.0.1                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_floodlights   | 1.0.3                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_otherplayers  | 1.0.9                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamiclights_theplayer     | 1.1.3                           | DynamicLights-1.12.2.jar                      | None                                     |
	| LCHIJA | dynamictrees                | 1.12.2-0.9.5                    | DynamicTrees-1.12.2-0.9.5.jar                 | None                                     |
	| LCHIJA | dynamictreesbop             | 1.12.2-1.4.1e                   | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCHIJA | earthworks                  | 1.3.4.3                         | Earthworks-1.12-1.3.6.jar                     | None                                     |
	| LCHIJA | ezstorage                   | 2.5.0                           | ezstorage-2.5.0-[1.12.2].jar                  | None                                     |
	| LCHIJA | familiarfauna               | 1.0.11                          | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHIJA | fastleafdecay               | v14                             | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | fenceoverhaul               | 1.3.4                           | FenceOverhaul-1.3.4.jar                       | None                                     |
	| LCHIJA | friendlyfire                | 1.5.10                          | FriendlyFire-1.12.2-1.5.10.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | gardenstuff                 | 1.12-2.1.1                      | GardenStuff-1.12-2.1.1.jar                    | None                                     |
	| LCHIJA | gravestone                  | 1.10.1                          | gravestone-1.10.1.jar                         | None                                     |
	| LCHIJA | roots                       | 1.12.2-3.0.4                    | Roots-1.12.2-3.0.4.jar                        | None                                     |
	| LCHIJA | harvest                     | 1.12-1.2.7-20                   | Harvest-1.12-1.2.7-20.jar                     | None                                     |
	| LCHIJA | hatchery                    | 2.2.2                           | hatchery-1.12.2-2.2.2.jar                     | None                                     |
	| LCHIJA | waila                       | 1.8.26                          | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | journeymap                  | 1.12.2-5.5.4                    | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| LCHIJA | jrftl                       | 1.1                             | JRFTL[1.12.2]-1.1.jar                         | None                                     |
	| LCHIJA | guilib                      | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar    | None                                     |
	| LCHIJA | paintingselgui              | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar    | None                                     |
	| LCHIJA | morepaintings               | $version                        | morepaintings-paintings-1.12.2-5.0.1.1.jar    | None                                     |
	| LCHIJA | mysticalworld               | 1.12.2-1.3.2                    | MysticWorld-1.12.2-1.3.2.jar                  | None                                     |
	| LCHIJA | naturescompass              | 1.5.1                           | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| LCHIJA | nmsot                       | 1.2.2-mc1.12.2                  | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar       | None                                     |
	| LCHIJA | nonausea                    | 1.0                             | NoNausea-MC1.12-1.0.jar                       | None                                     |
	| LCHIJA | roost                       | 2.0.10                          | roost-1.12.2-2.0.10.jar                       | None                                     |
	| LCHIJA | rustic                      | 1.1.1                           | rustic-1.1.1.jar                              | None                                     |
	| LCHIJA | woodenshears                | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar             | None                                     |
	| LCHIJA | signpost                    | 1.06.1                          | signpost-1.12-1.06.1.jar                      | None                                     |
	| LCHIJA | sophisticatedwolves         | 3.13.8                          | SophisticatedWolves-1.12.2-3.13.8.jar         | None                                     |
	| LCHIJA | stg                         | 1.12.2-1.2.3                    | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCHIJA | storagedrawers              | 1.12-5.3.5                      | StorageDrawers-1.12.2-5.3.8.jar               | None                                     |
	| LCHIJA | strawgolem                  | 1.3                             | strawgolem-1.4.1.jar                          | None                                     |
	| LCHIJA | totemic                     | 1.12.2-0.11.6                   | Totemic-1.12.2-0.11.6.jar                     | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| LCHIJA | wildcrops                   | 1.0.1                           | WildCrops-1.12-1.0.1.jar                      | None                                     |
	| LCHIJA | orelib                      | 3.5.2.2                         | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                   | 3.5.4.3                         | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | mysticallib                 | 1.12.2-1.3.1                    | mysticallib-1.12.2-1.3.1.jar                  | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
LoadingPlugin (NoNausea-MC1.12-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Ederyn'/295, l='Mo Witches!', x=529.84, y=73.91, z=-634.22]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-1.0.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 417.22
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Kdschar** [comment]
Edit: sorry! Just saw the commit. I'll look for an update.

Sorry, why was this ticket closed? I'm still having issues with the crashes and I don't know why.

**Comment by Sunconure11** [comment]
Because the build with the fix has not been released yet.
