### ISSUE TITLE
Recipes not returned used Bottles and Jars

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#396]
### Expected Behavior
After the recipe is finished, the jars that once contained fumes are returned, but emptied, so they can be reused, likewise bottled goods (i.e. Snake Venom) should also return the empty bottle.

### Actual Behavior
Fumes are consumed but do not return jars, this effects all types of recipes from circle rites to spinning wheel to normal crafting

### Steps to Reproduce
Find any recipe that calls for a fume. Do it, then you will not get the empty jar back

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Forge .2838
Bewitchment 0.20.6
Patchouli .19
Baubles 1.5.2

### Screenshots encouraged
![2019-07-30_20 38 01](https://user-images.githubusercontent.com/17956808/62175678-8989ce00-b30c-11e9-93ec-b4aa1d5fa662.png)

![2019-07-30_20 38 12](https://user-images.githubusercontent.com/17956808/62175704-9c040780-b30c-11e9-8945-cdddac5f34aa.png)

![2019-07-30_20 39 03](https://user-images.githubusercontent.com/17956808/62175711-a1615200-b30c-11e9-9067-8046596452dc.png)

![2019-07-30_20 39 20](https://user-images.githubusercontent.com/17956808/62175722-a4f4d900-b30c-11e9-94bb-80e705669b86.png)

### Logs, in the event of a crash
N/A

**Comment by Sunconure11** [comment]
Will work on this tomorrow.

**Comment by Sunconure11** [comment]
No responses since. Assuming fixed.
