### ISSUE TITLE
Brooms don't move

### ISSUE THREAD

**Issue by Ranazu** [Um-Mitternacht/Bewitchment#399]
### Expected Behavior
Faster forward motion with a broom than walking.

### Actual Behavior
Forward motion slower than sneaking.

### Steps to Reproduce
Create 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2, Bewitchment 0.0.20.6, Forge 14.23.5.2838, Patchouli 1.0-20, Baubles1.12-1.5.2

**Comment by Tangosucka** [comment]
Hit space to take off

**Comment by MoriyaShiine** [comment]
^ read the book

**Comment by Ranazu** [comment]
Space makes me go up but I still can't move forward and the book doesn't seem to talk about how to control the broom. I can strafe with what I expect is the normal flying speed but I can't fly forward or backwards at that speed. Is there a section of the book I'm missing? The ritual on creating the brooms just talks about the benefits of each broom and the components to the rituals.

**Comment by 123mind123** [comment]
I am also having this problem and can also not find an entry.
