### ISSUE TITLE
Can´t acces discord.

### ISSUE THREAD

**Issue by matyklugDebbuged** [Um-Mitternacht/Bewitchment#4]

**Comment by zabi94** [comment]
You were banned for trolling and then again for ban evasion

**Comment by matyklugDebbuged** [comment]
better description: for no reason. i does nothing. and comes one weird guy. then i get banned. i does nothing.

**Comment by matyklugDebbuged** [comment]
just makes no sense.

**Comment by matyklugDebbuged** [comment]
yeah. ban random people because you wake up too early...

**Comment by Sunconure11** [comment]
You were banned for trolling the suggestions channel, as well as bringing a group of individuals who seemed to spam nothing but memes for the sake of trolling the channel.
