### ISSUE TITLE
Cruel Community

### ISSUE THREAD

**Issue by UnlimitedTurtlez** [Um-Mitternacht/Bewitchment#400]
they banned me from discord for trying to explain i had a disability when a misunderstanding came up, they are very cruel and unfair people, their mod is ok but i wouldn't support them

**Comment by Sunconure11** [comment]
It was pretty clear you were making things up, and trying to excuse rule-breaking behavior on the server. Disability is not an excuse for bad behavior, it is not a get out of jail free card. Please just leave before you embarrass yourself more.
