### ISSUE TITLE
Broom Dupe Glitch

### ISSUE THREAD

**Issue by Tangosucka** [Um-Mitternacht/Bewitchment#402]
### Expected Behavior
Left clicking placed broom picks it up

### Actual Behavior
Left clicking placed broom spawns 2 of them to pick up

### Steps to Reproduce
place broom left click to pick up

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
All of the latest versions and bewitchment-1.12.2-0.0.20.6

### Screenshots encouraged
https://i.imgur.com/5aUqBeH.mp4

### Logs, in the event of a crash
no crash or logs

**Comment by MoriyaShiine** [comment]
Can't seem to reproduce. Try with just Bewitchment?

**Comment by anqingchen** [comment]
Closing, no response
