### ISSUE TITLE
imp ritual wont work with waystone

### ISSUE THREAD

**Issue by SmallEnderman** [Um-Mitternacht/Bewitchment#403]
I wanted a imp to spawn on the coords of the waystone

It didnt even start the ritual after sacrifising the chicken, i putted a waystone in there and didnt know the rite, i tried dropping it while it was doing the ritual but didnt work either

placed the required items in the circle, placed waystone in there. unknown rite

Latest of everything

**Comment by MoriyaShiine** [comment]
small

**Comment by MoriyaShiine** [comment]
you fool

**Comment by MoriyaShiine** [comment]
that's not how the waystone works my dude

**Comment by MoriyaShiine** [comment]
you cast the ritual

THEN right click it with the waystone

**Comment by MoriyaShiine** [comment]
:Budgetts_Frog:
