### ISSUE TITLE
Altar Booster Info/Documentation Improvements

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#407]
The altar system can be a tad confusing to use, mainly in that it's not particularly clear what can be used to boost the altar, for both plants and things like swords or statues. There are a few things listed in the book, but it's not a very exhaustive list, so providing some more info to the players about what works for the altar might be helpful.

One thing to do might be to make a more complete list in the book of what altar boosters there are and what exactly they do, perhaps in a layout like the Brew effects list (one page per item, picture of the item with text underneath). Another thing to do might be to add tooltips to altar booster items that show what booster type they are and how effective they are, I recall that Covens did something like that. The tooltip idea could even be extended to plants, so a very simple tooltip appearing for plants/seeds that will boost the altar when planted.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW - 0.0.20.7
Patchouli - 1.0-20
Baubles - 1.5.2
Forge - 14.23.5.2838
MC - 1.12.2

**Comment by Sunconure11** [comment]
This has since been made a thing, although not all can be listed, due to the amount of things that work on an altar.
