### ISSUE TITLE
"Hellish Bauble" don't work

### ISSUE THREAD

**Issue by guide-for-you** [Um-Mitternacht/Bewitchment#411]
I'm take fully charged Grimoire Magia and outfitted with Hellish Bauble.

![2019-08-18_19 28 04](https://user-images.githubusercontent.com/53404970/63227399-b2580180-c1ee-11e9-9890-7f980cf94e40.png)

![2019-08-18_19 28 09](https://user-images.githubusercontent.com/53404970/63227401-b84de280-c1ee-11e9-968b-503c1a60f719.png)

![2019-08-18_19 28 19](https://user-images.githubusercontent.com/53404970/63227403-bc7a0000-c1ee-11e9-851d-d855e1c8c42d.png)

**Comment by MoriyaShiine** [comment]
It doesn't make you immune, it only reduces it. Of course standing right next to TNT with no armor is going to kill you.

**Comment by guide-for-you** [comment]
Oh, I'm sorry, I'm dumbing something. Now I know that it makes no sense to create it.
P.S.Thank.
