### ISSUE TITLE
Taglocks vanish after use

### ISSUE THREAD

**Issue by cybercat5555** [Um-Mitternacht/Bewitchment#415]
### Expected Behavior
When I hold a taglock and r-click on someone, it takes a sample of their blood as a taglock, which can be used for rites and such.

### Actual Behavior
The Taglock Kit simply vanishes into thin air. I asked the target if they somehow got it, but they did not.

### Steps to Reproduce
1) Get a Taglock Kit
2) Find a target, willing is best but not needed
3) R-click on them with said Taglock
4) Watch in amazement as the Taglock vanishes into thin air

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC 1.12.2
BW 0.20.6
Forge .2838
Patchouli .20
Baubles 1.5.2

### Screenshots encouraged
N/A

### Logs, in the event of a crash
N/A

**Comment by anqingchen** [comment]
been fixed for a while
