### ISSUE TITLE
Conflict with Roots Living Arrows

### ISSUE THREAD

**Issue by squirrelkiller** [Um-Mitternacht/Bewitchment#417]
This is a cross report with an issue found with Roots here: https://github.com/MysticMods/Roots/issues/180

One of you is modifying the arrow entity in a naughty way.

**Comment by noobanidus** [comment]
I'm closing the issue on my side as all I'm doing is [creating a class that extends `EntityTippedArrow` to overrode `getArrowStack`](https://github.com/MysticMods/Roots/blob/master/src/main/java/epicsquid/roots/entity/item/EntityLivingArrow.java). In all other respects it functions precisely as a normal EntityArrow would.

I'd also be curious to see if other custom arrows are affected, i.e., Torch Arrows and Ender Arrows from Quark, etc.

If it does turn out to be something on my end, please make a comment on that issue or create a new issue -- your choice.

**Comment by anqingchen** [comment]
It was an issue on our side, but should be fixed in 4ac4ebda9c3cf40c27176d34e18bea8862e9450e and f47e8614451c00499788c5f6682b672f8aa1ee45 if yall can do more testing, or just wait for our next update!

**Comment by Sunconure11** [comment]
No response since. Closing.
