### ISSUE TITLE
Non-vanilla farmland farming causes crops to unplant themselves.

### ISSUE THREAD

**Issue by squirrelkiller** [Um-Mitternacht/Bewitchment#418]
### Expected Behavior
When planting on non-vanilla farm land I can plant the plants from this mod normally.

### Actual Behavior
Placing a single crop works find. A block update near the crop causes both seeds to unplant themselves, dropping the seeds.

### Steps to Reproduce
Place crops on non-vanilla farm land then trigger a block update beside them.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft Version: 1.12.2 forge-14.23.5.2838, 
bewitchment-1.12.2-0.0.20.7
Patchouli-1.0-20
Baubles-1.12-1.5.2

### Screenshots encouraged
https://clips.twitch.tv/JoyousAntediluvianMouseBrokeBack

### Notes
Confirmed to not be an issue for other modded or vanilla crops.

**Comment by anqingchen** [comment]
Should have been fixed with fdf87d26f3cbec9b87d86d750f6cff4295ba8169, could you try again with the newest release?

**Comment by squirrelkiller** [comment]
Yup, working correctly now.
