### ISSUE TITLE
Where are the other blocks and things from older versions ?

### ISSUE THREAD

**Issue by Arckdash115** [Um-Mitternacht/Bewitchment#420]
### Expected Behavior
A lot of feactures are missing, the apiary, the brasier and another blocks and things are missing from older versions that I saw in tutorials.

### Actual Behavior
The blocks and things misssing must be in the game ? or are disabled for some reason ?

### Steps to Reproduce
1. Checking in the creative menu or JEI the bewitchment part

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 14.23.5.2838
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

### Screenshots encouraged
N/A

### Logs, in the event of a crash
N/A

**Comment by cybercat5555** [comment]
100% intended. Certain things were removed due to them not fitting (apiary), or were temp removed until they have a use, such as the brazier.
