### ISSUE TITLE
Pet Black Dogs!

### ISSUE THREAD

**Issue by SpitefulFox** [Um-Mitternacht/Bewitchment#421]
Would it be possible to find a way to make black dogs stay spawned during the day if you keep them indoors or nametag them?  I really wanted to capture one as a "pet". Feel free to ignore if it breaks the lore too hard.

**Comment by Sunconure11** [comment]
I have them set in the upcoming update to not despawn in rain, but nothing yet involving name tags.

**Comment by anqingchen** [comment]
![2019-11-16_22 29 44](https://user-images.githubusercontent.com/28765626/69003043-9b45b000-08c0-11ea-8b05-ff6c246e83fb.png)
nametag it to keep it from despawning, will be out in the next update. 
70dcaa73b1176c94fd43b21bfcc3c484142ebdad
