### ISSUE TITLE
issue while hovering over items in the book of shadows

### ISSUE THREAD

**Issue by ghostlineage** [Um-Mitternacht/Bewitchment#427]
### Expected Behavior
i saw some items in the book of shadows that i haven't seen in my game before, like not even in the jei library or anything. 

### Actual Behavior
i have hwyla and i hovered over them to see it, but it crashed. the log says its due to rendering a screen thing.

### Steps to Reproduce
go to the book of shadows and hover over some items from crafting recipes / rituals (specific ones are in the screenshots). i'm not sure if you have to have hwyla or not, because i don't know if bewitchment already does the thing where if you hover over it, it'll say what it is. 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
minecraft: 1.12.2
bewitchment: 0.0.20.8
forge: 14.23.5.2838
patchouli: 1.0-20
baubles: 1.5.2

### Screenshots encouraged
specifically, these items (the darker dirt block and the purple gem that isn't from bewitchment). i havent seen them in my game so i hovered over it
https://prnt.sc/p4xaoh
https://prnt.sc/p4xazr

### Logs, in the event of a crash
https://pastebin.com/upHQzBVc

**Comment by Sunconure11** [comment]
This looks like stuff from BoP showing up in our books. Not quite our fault.
