### ISSUE TITLE
Witches Hat/Cowl Still Has Z-Fighting Problems

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#430]
### Behavior
I already made an issue about this in the past, but that one was closed with a bugfix that didn't actually fix the bug, and since I cannot reopen that issue I'll just make a new one instead.

Regardless, wearing a Witches Hat or Cowl can cause really nasty looking Z-fighting, but only if your skin has a hat layer on it (my skin has a mask on it). It's hard to notice in pictures, but it's _really_ bad in motion. It would probably be solvable simply by altering the models a little, make some parts bigger, move others a smidge, that kind of thing.

### Steps to Reproduce
From the previous issue:
1. Use a player skin that has a hat layer on it, one with a hat layer going over the face can show the Z-fighting particularly clearly.
2. Put on a Witches Hat or Cowl, go to third person and start looking/walking about.
3. You should see Z-fighting on the Hat/Cowl, it's most notable on the Hat but it is still present on the sides of the Cowl.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW - 0.0.20.8, but still happens in the test versions from the Discord
Patchouli - 1.0-20
Baubles - 1.5.2
Forge - 14.23.5.2838
MC - 1.12.2

**Comment by Sunconure11** [comment]
Still present, and I can confirm that the robes do not sync to player movements.

The lack of syncing is also present in @Aelpecyem’s Miskatonic Mysteries.
