### ISSUE TITLE
Crash on startup on my server 

### ISSUE THREAD

**Issue by uiytt** [Um-Mitternacht/Bewitchment#433]
### Actual Behavior
Crash on startup...

### Steps to Reproduce
I don't know, it worked fine before but now it always crash.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Mc : 1.12.2
Forge : 14.23.5.2847
Bewitchement : 0.20.8
Patchouli : 1.0-20
Baubles : 1.5.2
### Logs, in the event of a crash
[crash-report](https://hastebin.com/oleyohisil.pl)

**Comment by anqingchen** [comment]
your crash-report isn't working, got another link?

**Comment by anqingchen** [comment]
Should be fixed in the next update, in the mean time, just remove that spinningwheel MCEdit or i think forge has a config called "remove erroring entity"
