### ISSUE TITLE
Black Dogs spawning in lit areas at night

### ISSUE THREAD

**Issue by OsirisKalev** [Um-Mitternacht/Bewitchment#434]
### Expected Behavior
They don't spawn in lit areas like other hostile mobs.

### Actual Behavior
They spawn in lit areas unlike other hostile mobs.

### Steps to Reproduce
Wait until night time and watch them spawn in a lit area.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12, Bewitchment 0.0.20.8, Forge 14.23.5.2846, Patchouli 1.0-20, Baubles 1.12-1.5.2

Don't really see the need for a screenshot on this one, it's pretty self-explanatory.

**Comment by Sunconure11** [comment]
Intended behavior. They don’t operate like other hostiles.

**Comment by OsirisKalev** [comment]
Would have been cool to have actually known that was intended behaviour, didn't see it written anywhere.

Thank you for having config options to limit where they spawn though. That will be very helpful.
