### ISSUE TITLE
Unable to dismount broom

### ISSUE THREAD

**Issue by BloodyDruddigons** [Um-Mitternacht/Bewitchment#437]
### Expected Behavior

Pressing the sneak key should make the player dismount the broom

### Actual Behavior

Pressing the sneak key fails to activate the dismounting action

### Steps to Reproduce

1. Obtain a juniper broom (not sure if other brooms are affected)

2. Fly on it for a while (about 2-5 minutes, possibly shorter)

3. Attempt to dismount broom via the sneak key

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2

Bewitchment: 0.0.20.8

Forge: 14.23.5.2847

Baubles: 1.5.2

### Logs, in the event of a crash

N/A

### If this is a question, developer commentary, or a suggestion, ignore this template

Thanks in advance. Loving the mod!

**Comment by Calanon7** [comment]
I'm experiencing the same issue.

**Comment by BlackJac** [comment]
Still an issue for me as well playing the 0.0.21.10 version.

**Comment by Diamond200512** [comment]
I too have this issue

**Comment by Diamond200512** [comment]
it happens on any broom for me

**Comment by Ayrion** [comment]
Relog, brooms are rather buggy

**Comment by Diamond200512** [comment]
the only way I can find to not have to relog is if you only fly in short bursts , dismounting every 5 - 10 seconds

**Comment by Luicuelo** [comment]
Still an issue for me as well playing the 0.0.21.12 version.

**Comment by akcrittenden** [comment]
Same here. Using MC Eternal modpack. Tried to dismount with L-shift, didn't work. Scrolled to sleeping mat on hotbar and used it, and I dismounted broom and it floated next to me. Waited until dawn, and when I woke up the broom was gone. Not in inventory, not stuck in blocks around where it was, not anywhere. (EDIT: using 1.12.2-0.0.21.10) (EDIT 2: It was the Elder Broom.)

**Comment by Sunconure11** [comment]
Brooms are known to be buggy. If however, someone knows how to fix them, please send over a PR.
