### ISSUE TITLE
Crash connected to Caverns

### ISSUE THREAD

**Issue by happybandit360** [Um-Mitternacht/Bewitchment#438]
### Expected Behavior
Encounter a Cavenic or Crazy Skeleton without issue (also filing this report with Caverns II dev.)

### Actual Behavior
When a Cavenic or Crazy Skeleton attacks, the game crashes

### Steps to Reproduce
Encounter a Cavenic or Crazy Skeleton anywhere.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 1.12.2-0.0.20.8
Forge 14.23.5.2838
Patchouli 1.0-20
Baubles 1.12.1.5.2
Caverns II 1.12.2-v2.2.0

### Logs, in the event of a crash
https://paste.ee/p/1MkwI

**Comment by anqingchen** [comment]
I made some changes to how BW handle arrows, this could be fixed here. Please test if you can.

**Comment by Sunconure11** [comment]
No response. Closing.
