### ISSUE TITLE
Bewitchment Tree Leaves fluctuate between Fancy and Fast when decaying

### ISSUE THREAD

**Issue by Jake-Silver** [Um-Mitternacht/Bewitchment#439]
### Expected Behavior
Bewitchment tree leaves will stay see through as they decay (Fancy Graphics)

### Actual Behavior
They fluctuate between Fast and Fancy randomly each decay tic

### Steps to Reproduce
Breaking the logs of a Bewitchment tree so that the leaves can decay
As the leaves decay random leaves of Bewitchment trees (even non decaying) will swap between fancy and fast.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2, Bewitchment 0.0.20.8, Forge 14.23.5.2846, Patchouli 1.0-20, and Baubles 1.12-1.5.2

### Screenshots encouraged
![2019-10-07_03 01 01](https://user-images.githubusercontent.com/44173444/66353182-49e7ef80-e916-11e9-86d3-8b3a23609a71.png)
![2019-10-07_03 34 38](https://user-images.githubusercontent.com/44173444/66353221-59ffcf00-e916-11e9-8d01-36b0d5d619ca.png)
![2019-10-07_03 37 22](https://user-images.githubusercontent.com/44173444/66353239-697f1800-e916-11e9-9421-14b173f4c97e.png)
![2019-10-07_03 37 27](https://user-images.githubusercontent.com/44173444/66353245-74d24380-e916-11e9-81fb-f9660b1af480.png)
![2019-10-07_03 37 31](https://user-images.githubusercontent.com/44173444/66353262-7bf95180-e916-11e9-8e29-3f3dd120c7f4.png)

Of note, I am using a custom (100 something mods) Modpack, but only Bewitchment Trees show this behavior. Moving around and updating blocks seems to change the blocks as well. The last two images show me destroying the leaf block atop the tree and them all reverting to normal.

I suspect an improvement mods such as Phosphor, Optifine, or Vanillafix may be the issue.

**Comment by Sunconure11** [comment]
Unable to replicate, nor has this been spotted by anyone else. Closing.
