### ISSUE TITLE
Bewitchment crops do not drop anything

### ISSUE THREAD

**Issue by TriageONE** [Um-Mitternacht/Bewitchment#443]
### Expected Behavior
for the crop to drop its expected material upon mature growth, with using a fist as the harvesting tool and left click

### Actual Behavior
nothing happens and the plant breaks

### Steps to Reproduce
install bewitchment and enter a creative world, grow crops with bonemeal and punch them

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2, forge 2847, baubles 1.12-1.5.2, Patchouli 1.0-20

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/28678092/66661435-fe368e00-ec14-11e9-913d-3aa06e252d6b.png)
Here's a gif of me demonstrating the action, as you can see, the crops drop nothing upon full growth. I have no other mods installed, only bewitchment and its latest version. 

### Logs, in the event of a crash
there is no crash

**Comment by TriageONE** [comment]
![ezgif-1-4412d9c54a44](https://user-images.githubusercontent.com/28678092/66661749-87e65b80-ec15-11e9-94a6-f08e599641a2.gif)
That should correct it, for some reason it diddnt upload the gif correctly

**Comment by MoriyaShiine** [comment]
You're in creative.

**Comment by Vazkii** [comment]
absolute bruh moment

**Comment by TriageONE** [comment]
Why cant i break the crop normally in creative? I am doing the same thing in survival for a server i own and it still doesn't work. There are no ops and nobody is in creative either, but nobody can harvest bewitchment crops. All other crops work fine.

**Comment by MoriyaShiine** [comment]
Are you playing 4d chess right now, I can't tell

**Comment by TriageONE** [comment]
I've figured it out, we have a mod called noTreePunching in order to give an extra challenge, as well as others.

When adding this mod in, it nukes all compatibility with your seeds and plants, you absolutely have to add exceptions to this in its config like so:
    S:alwaysBreakable <
        minecraft:leaves
        minecraft:gravel
        minecraft:sand
        minecraft:dirt
        minecraft:grass
        bewitchment:crop_aconitum
        bewitchment:crop_belladonna
        bewitchment:crop_wormwood
        bewitchment:crop_garlic
        bewitchment:crop_white_sage
        bewitchment:crop_hellebore
        bewitchment:crop_mandrake
     >
in order for it to actually work. 

All the other mods do not have this issue, and we have other mods like rustic that add crops too. If it was a crop issue, then it would be more severe, affecting all crops in the entire pack. 

After adding the exceptions, I can break them at will, but this should not have to be done, and should be looked further into.

**Comment by Sunconure11** [comment]
They provided you with a config for a reason.

**Comment by Brentiiiiii** [comment]
how do u canfig somting in a mod i dont know in what folder in the mod folder i should put this all :)
