### ISSUE TITLE
[Question] Version support...

### ISSUE THREAD

**Issue by PresquePlayed** [Um-Mitternacht/Bewitchment#445]
I really love this mod and wanna build a pack around it and I wanted to know how your plans for version supporting are. Developing the mod for 1.12.2 and 1.14+ would slow down development greatly so I dont think that'd be an option. Thus I'd like to know wether you are planing to port the mod to 1.14+ or wether you are going to finish it in 1.12.2 first and then are going to port it the latter would cause the mod to be stuck in 1.12 similar to how witchery is stuck in 1.7.10 sooo what are you planning to do? Maybe you should do a poll where the bewitchment players can vote what they'd prefer? But any way this mod is amazing and thanks for the time you're all putting into it.

**Comment by Sunconure11** [comment]
A 1.14 port is in progress. Don't expect it anytime soon though. It needs some major changes to adapt to the new version.

We're planning on releasing one last update to 1.12.2 (well, one last major one), plus some bugfix builds and what not, before dropping the 1.14.4 build.
