### ISSUE TITLE
[0.020.8] Grimoire looses charge in various ways

### ISSUE THREAD

**Issue by PokeMaserJ** [Um-Mitternacht/Bewitchment#446]
### Expected Behavior
Grimoire not loosing charge

### Actual Behavior
The Grimoire looses charge when being picked up  or opening another inventory besides your personal inventory [this includes baubles]. Strangely enough, if you have your Baubles inventory open and let it charge, then swap back to your personal inventory, it keeps the charge.

### Steps to Reproduce
Build an Altar and let a Grimoire charge from it, pick it up / change what inventory you're in

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 0.020.8
Forge: 14.23.5.28.38
Patchouli: 1.0-20
Baubles: 1.5.2

**Comment by anqingchen** [comment]
Cannot replicate, could you provide more information. Are you on a server or single player? Provide a video if possible?

**Comment by anqingchen** [comment]
Nevermind, just reproduced it, really weird

**Comment by anqingchen** [comment]
should be fixed in 459b9cbf901dd1cbb6f3d838df49d2dd1b5f1a90. Will be released with the next update
