### ISSUE TITLE
Grimorie dont work in lan game

### ISSUE THREAD

**Issue by Luicuelo** [Um-Mitternacht/Bewitchment#447]
I play with other player a local LAN game. His grimorie is always 1000 of 1000 and dont work. Only happend with the other user grimorie, mime works ok

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

bewitchment-1.12.2-0.0.20.8
forge-1.12.2-14.23.5.2847

**Comment by Sunconure11** [comment]
Is this still an issue?

**Comment by Sergey-Lomov** [comment]
I also faced this issue. Host player may use ME from Grimoire, but I can't. Tested issues by start LAN game from 2 windows - same result, only host grimoure works.

bewitchment-1.12.2-0.0.22.44
forge-1.12.2-14.23.5.2854
