### ISSUE TITLE
EntityTippedArrow incompatibility

### ISSUE THREAD

**Issue by stepsword** [Um-Mitternacht/Bewitchment#448]
Hi,

I'm the mod dev for Mahou Tsukai. A user noticed/investigated & found that the projectiles in my mod (swords shot via bow) were being replaced with normal arrows by your mod. I believe your mod is rebuilding all things which extend EntityTippedArrow from scratch in [this class](https://github.com/Um-Mitternacht/Bewitchment/blob/3057743b51ec31e47869242faca84c59ce21f12e/src/main/java/com/bewitchment/common/handler/MiscHandler.java).

I imagine this would break any custom rendering on arrows from other mods as well, if they exist. Would it be possible to either 1) not do this for modded arrows or 2) add a config so that mods or specific entities can be blacklisted from this rebuilding? 

I think these are the most reasonable ways to resolve this incompatibility, but I could imagine more difficult ways..

**Comment by anqingchen** [comment]
Should be fixed in f47e8614451c00499788c5f6682b672f8aa1ee45

**Comment by anqingchen** [comment]
fixed in f47e8614451c00499788c5f6682b672f8aa1ee45 and 4ac4ebda9c3cf40c27176d34e18bea8862e9450e. Will be out in the next update
