### ISSUE TITLE
Cross mod issue with Rats

### ISSUE THREAD

**Issue by PokeMaserJ** [Um-Mitternacht/Bewitchment#449]
### Expected Behavior
When you throw a Vial of Consciousness potion onto a Feral Ratlantean mob it normally turns into a  Neo-Ratlantean mob

### Actual Behavior
When you have Rats and Bewitchment together, when you go to throw the potion, it doesn't convert the mob

### Steps to Reproduce
Find / spawn a Feral Tatlantean
throw the Vial of Consciousness
Notice it not work

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Bewitchment 1.12.2-0.0.20.8
Rats 3.1.0
### Screenshots encouraged
![Without Bewitchment](https://user-images.githubusercontent.com/11018346/68151230-e9dd6c80-ff06-11e9-9a5b-d540423ad625.png)

![With Bewitchment](https://user-images.githubusercontent.com/11018346/68151238-ecd85d00-ff06-11e9-9948-d81056287608.png)

**Comment by anqingchen** [comment]
fixed in f47e8614451c00499788c5f6682b672f8aa1ee45 and 4ac4ebda9c3cf40c27176d34e18bea8862e9450e. Will be out in the next update
