### ISSUE TITLE
[suggestion] Config option to disable Bewitchment trees in certain biomes

### ISSUE THREAD

**Issue by Tulepeeker** [Um-Mitternacht/Bewitchment#450]
I don't want to completely remove Bewitchment trees from overworld but they break the atmosphere of some modded biomes(abyssalcraft for example).

**Comment by Sunconure11** [comment]
This would be better off as a dimension blacklist/whitelist IMO.

**Comment by Sunconure11** [comment]
Mainly since trees from this mod use biome dictionary definitions to spawn.

**Comment by Tulepeeker** [comment]
Dimension blacklist/whitelist would not help my problem as abyssalcraft biomes spawn in overworld and Bewitchment trees really look out of place there.

![2019-11-16_07 22 41](https://user-images.githubusercontent.com/38054549/68988552-0a2ff400-0842-11ea-817b-66362de0479c.png)

**Comment by Sunconure11** [comment]
Why not allow for both then?

**Comment by Tulepeeker** [comment]
> Why not allow for both then?

That would actually be best.

**Comment by anqingchen** [comment]
added in 61c5a792f8c5d1314178e4a4da61fed742211659 will come with Diabolic update
