### ISSUE TITLE
Belladonna Crop Spread - Need configs

### ISSUE THREAD

**Issue by MokahTGS** [Um-Mitternacht/Bewitchment#451]
### Expected Behavior
Belladonna shouldn't spread throughout the garden

### Actual Behavior
Belladonna spreads without any control

Can we please get a config option or belladonna crop spreading.  Seems out of control.

**Comment by anqingchen** [comment]
Belladonna no longer spread as of 51356f5687eb43bacd60594048d9043714110cc7, will be included in the Diabolic Update.
