### ISSUE TITLE
Putting string in Spinning Wheel caused server to permanently crash, no way of reopening world

### ISSUE THREAD

**Issue by rohinshanker** [Um-Mitternacht/Bewitchment#453]
Error: I play on a server with a couple of other people which features multiple mods, including the bewitchment mod. The JEI interface said I would be able to create cobwebs by placing 3 string inside a Spinning Wheel, however upon doing so, the server crashed and I was unable to relaunch the world. 

Attempted fixes: I have tried opening it on 64 bit MCEdit for windows, however the world only appeared as a blue void. I then tried this on my mac, and the file did not open because of incompatible file types (I tried both .dat and .DAT). My friend said he was going to try and update the mods later. 

Other information: The modpack was created on curseforge and launched off of twitch. 

Does anyone have any recommendations or solutions? Attached below is the link to the modpack and a screenshot of the error.  

https://www.curseforge.com/minecraft/modpacks/modpack-for-the-boys-ultimate-edition

<img width="1136" alt="minecraftBewitchmentServerError" src="https://user-images.githubusercontent.com/58312159/69832809-25f1ad80-11e5-11ea-8e38-c2b548dae2d3.png">

**Comment by Sunconure11** [comment]
This should be fixed, now that Diabolic is out.
