### ISSUE TITLE
Tarot Cards Show nothing on servers

### ISSUE THREAD

**Issue by AkiKuneko** [Um-Mitternacht/Bewitchment#454]
### Expected Behavior
Using bound tarot cards on a tarot table show 4 cards relating to bound player

### Actual Behavior
Cards do not appear after clicking on the table 

### Steps to Reproduce
on a server set up a tarot table next to an alter with power and use the bound cards on the table 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft - 1.12.2
Forge - 14.23.5.2847
Patchouli-1.0-20
Baubles - 1.5.2

### Screenshots encouraged
![2019-11-29_03 16 04](https://user-images.githubusercontent.com/58326982/69858009-b9af9200-1256-11ea-86a6-60cf9edd6fff.png)
![2019-11-29_03 16 10](https://user-images.githubusercontent.com/58326982/69858010-b9af9200-1256-11ea-8df8-e206eeaa4695.png)
![2019-11-29_03 16 13](https://user-images.githubusercontent.com/58326982/69858011-b9af9200-1256-11ea-89c1-af74b00836f1.png)

**Comment by anqingchen** [comment]
Fixed in the upcoming version releasing soon

**Comment by AkiKuneko** [comment]
sick just wanted to bring it up in case you guys were not aware of it.
