### ISSUE TITLE
Thaumcraft everfull urn dont fill witches' cauldron

### ISSUE THREAD

**Issue by Luicuelo** [Um-Mitternacht/Bewitchment#456]
Thaumcraft everfull urn dont fill witches' cauldron

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

 Bewitchment 1.12.2-0.0.21.1

**Comment by Sunconure11** [comment]
Known issue. I want to get this working again in another update.

**Comment by Sunconure11** [comment]
See #458
