### ISSUE TITLE
Bewitchment is causing crashes with sponge

### ISSUE THREAD

**Issue by runescapejon** [Um-Mitternacht/Bewitchment#457]
### Expected Behavior

crashing with latest spongeforge 
### Actual Behavior
boot crashing cause conflicting between bewitchment and spongepowered spongeforge jar
EDIT: I'd been able to make a quick fix just by deleting the ASM within bewitchment jar and letting spongeforge latest asm do whatever require in bewitchment. This is just a temporary fix but figure write it here for extra information and if other servers owners if they are having an issue. 
### Steps to Reproduce
Updating from 1.12.2-0.0.20.8 to 1.12.2-0.0.21.1 (latest as of this moment)
With SpongeForge causing crashing.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
all in the version are in the crash report

### Logs, in the event of a crash
https://pastebin.com/raw/tNCDUAgk

**Comment by Sunconure11** [comment]
Is this still an issue?

**Comment by runescapejon** [comment]
It seem it's fixed! I'll go ahead and close this issue. Thank you so much!
