### ISSUE TITLE
Thermal Expansion reservoir won’t interact with Witches’ Cauldron

### ISSUE THREAD

**Issue by LvdT** [Um-Mitternacht/Bewitchment#458]
### Expected Behavior
Right-clicking with a reservoir filled with water on an empty cauldron should pull water from the reservoir and fill the cauldron.
Right-clicking with a reservoir that is either empty or partially filled with water on a full cauldron should empty the cauldron and move the water to the reservoir.

### Actual Behavior
Nothing happens, as if right-clicking with any other held object or an empty hand.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC 1.12.2
Forge 14.23.5.2847

Possibly related to #456

**Comment by Sunconure11** [comment]
Due to how cauldrons are written, this isn’t really possible on 1.12.
