### ISSUE TITLE
Crash on 1.12 due to PotionColorizer?

### ISSUE THREAD

**Issue by ravclaw** [Um-Mitternacht/Bewitchment#459]
### Expected Behavior
Loading up

### Actual Behavior
Crash

### Steps to Reproduce
Load up

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2. Bewitchment 0.0.21.1 Forge 14.23.5.2938 patchouli 1.0-20 baubles 1.5.2

### Screenshots encouraged
https://imgur.com/a/n4wa8y8

### Logs, in the event of a crash
https://paste.dimdev.org/adihocuqox.mccrash

**Comment by anqingchen** [comment]
been fixed for a while now, use newest version.
