### ISSUE TITLE
Snake does not inflict any damage upon attacking a target

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#46]

**Comment by Skyshayde** [comment]
So it's supposed to have an effect similar to thorns, where it does damage and poisons the attacking entity?  How much damage?  Same as the normal attack?

**Comment by Sunconure11** [comment]
Think like the cave spider, but a bit more potent.

**Comment by Sunconure11** [comment]
Snake venom is still broken, in that a snake can never kill a mob.

**Comment by Skyshayde** [comment]
In normal minecraft undead mobs and spiders are immune to poison.  It'd probably be pretty straightforward to duplicate the poison effect without that check, but it'd be inconsistent with the normal minecraft poison effect.
