### ISSUE TITLE
Playerdata file size is increasing from exploredChunks

### ISSUE THREAD

**Issue by runescapejon** [Um-Mitternacht/Bewitchment#460]
### Expected Behavior
Playerdata is holding too much data that is cause by consistent chunk loading when a player load a new chunk 

### Actual Behavior
Playerdata size is going well over 100,000 bytes

### Steps to Reproduce
Really don't know how to reproduce since this happen once when i updated the mod. Sorry but will provide as much detail as possible.
https://github.com/Um-Mitternacht/Bewitchment/blob/0c7eb2aa7ca582aafa3b20fecb4089f056388692/src/main/java/com/bewitchment/api/capability/extendedplayer/ExtendedPlayer.java#L47
Here it's putting this information into a playerdata here is the result of that (down below)

Since this is increasing players ingame either lag very intensively or wont be able to login into the server because it's minecraft playerdata size limitation. 
Also, if you want to do some investigation of the actual playerdata I'll put the actual file down below 

[e23b034b-c2d2-4ae5-ba7a-93fb08de9c69.zip](https://github.com/Um-Mitternacht/Bewitchment/files/3914154/e23b034b-c2d2-4ae5-ba7a-93fb08de9c69.zip)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Mc - 1.12.2
forge-1.12.2-14.23.5.2847
Baubles-1.12-1.5.2
Patchouli-1.0-20
bewitchment-1.12.2-0.0.21.1
### Screenshots encouraged
![913010002f0fdec2eba7d76018b0f8f1](https://user-images.githubusercontent.com/10858509/70014055-9da63c00-1547-11ea-87fa-1455eab387b1.png)
![f93a6d4ad8430cf1bb0252ad7a79058a](https://user-images.githubusercontent.com/10858509/70014088-b6aeed00-1547-11ea-9f7c-60b391a51268.png)

**Comment by Sunconure11** [comment]
This bug needs urgent attention.
