### ISSUE TITLE
Spinning wheel crashes game

### ISSUE THREAD

**Issue by seniorfluffy** [Um-Mitternacht/Bewitchment#464]
### Expected Behavior
The spinning wheel input 3 string, expected witchery string

### Actual Behavior
Crashes

### Steps to Reproduce
put 3 string into a spinning wheel

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
Heavily custom modded
### Logs, in the event of a crash
--- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  FutureMC (future-mc-0.1.13.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 12/7/19 4:21 PM
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4815)
	at com.bewitchment.api.registry.SpinningWheelRecipe.isValid(SpinningWheelRecipe.java:30)
	at com.bewitchment.common.block.tile.entity.TileEntitySpinningWheel.func_73660_a(TileEntitySpinningWheel.java:68)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Collections$SingletonList.get(Collections.java:4815)
	at com.bewitchment.api.registry.SpinningWheelRecipe.isValid(SpinningWheelRecipe.java:30)
	at com.bewitchment.common.block.tile.entity.TileEntitySpinningWheel.func_73660_a(TileEntitySpinningWheel.java:68)

-- Block entity being ticked --
Details:
	Name: bewitchment:spinning_wheel // com.bewitchment.common.block.tile.entity.TileEntitySpinningWheel
	Block type: ID #900 (tile.bewitchment.spinning_wheel // com.bewitchment.common.block.BlockSpinningWheel // bewitchment:spinning_wheel)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-46,68,260), Chunk: (at 2,4,4 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #900 (tile.bewitchment.spinning_wheel // com.bewitchment.common.block.BlockSpinningWheel // bewitchment:spinning_wheel)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 626 Drop: 0
	Level seed: -4485833776313061061
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-32,64,244), Chunk: (at 0,4,4 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 671 game time, 671 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63898 (now: false), thunder time: 64000 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 935293584 bytes (891 MB) / 2786590720 bytes (2657 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                          | Signature                                |
	|:------ |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | forge                 | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | futuremccore          | 0.1.12                   | minecraft.jar                                   | None                                     |
	| LCHIJA | antiqueatlas          | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                   | None                                     |
	| LCHIJA | antiqueatlasoverlay   | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                   | None                                     |
	| LCHIJA | astikorcarts          | 1.12.2-0.1.2.7           | astikorcarts-1.12.2-0.1.2.7.jar                 | None                                     |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | astralsorcery         | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | jei                   | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                       | None                                     |
	| LCHIJA | quark                 | r1.6-177                 | Quark-r1.6-177.jar                              | None                                     |
	| LCHIJA | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
	| LCHIJA | battletowers          | 1.6.5                    | BattleTowers-1.12.2.jar                         | None                                     |
	| LCHIJA | betterbuilderswands   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHIJA | patchouli             | 1.0-20                   | Patchouli-1.0-20.jar                            | None                                     |
	| LCHIJA | bewitchment           | 0.20.8                   | bewitchment-1.12.2-0.0.20.8.jar                 | None                                     |
	| LCHIJA | guideapi              | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
	| LCHIJA | bloodmagic            | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                 | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.0.29        | CTM-MC1.12.2-1.0.0.29.jar                       | None                                     |
	| LCHIJA | roots                 | 1.12.2-3.0.21            | Roots-1.12.2-3.0.21.jar                         | None                                     |
	| LCHIJA | mysticalworld         | 1.12.2-1.5.0             | mysticalworld-1.12.2-1.5.0.jar                  | None                                     |
	| LCHIJA | chisel                | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                    | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCHIJA | twilightforest        | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                | None                                     |
	| LCHIJA | bloodarsenal          | 1.12.2-2.2.0-29          | BloodArsenal-1.12.2-2.2.1-29.jar                | None                                     |
	| LCHIJA | botania               | r1.10-362                | Botania r1.10-362.jar                           | None                                     |
	| LCHIJA | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJA | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                        | None                                     |
	| LCHIJA | defiledlands          | 1.4.2                    | defiledlands-1.12.2-1.4.2.jar                   | None                                     |
	| LCHIJA | dimdoors              | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                  | None                                     |
	| LCHIJA | dldungeonsjbg         | 1.12.10                  | DoomlikeDungeons-1.12.10-MC1.12.2.jar           | None                                     |
	| LCHIJA | embers                | 1.13-hotfix2             | EmbersRekindled-1.13-hotfix2.jar                | None                                     |
	| LCHIJA | fairylights           | 2.1.9                    | fairylights-2.1.9-1.12.2.jar                    | None                                     |
	| LCHIJA | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| LCHIJA | minecraftfuture       | 0.1.13                   | future-mc-0.1.13.jar                            | None                                     |
	| LCHIJA | gravestone            | 1.10.3                   | gravestone-1.10.3.jar                           | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | improvedbackpacks     | 1.12.2-1.4.0.0           | ImprovedBackpacks-1.12.2-1.4.0.0.jar            | None                                     |
	| LCHIJA | infernalmobs          | 1.7.6                    | InfernalMobs-1.12.2.jar                         | None                                     |
	| LCHIJA | inspirations          | 1.12.2-0.2.8             | Inspirations-1.12.2-0.2.8.jar                   | None                                     |
	| LCHIJA | levelup2              | ${version}               | Level Up! 2-1.1.23-1.12.jar                     | None                                     |
	| LCHIJA | lootbags              | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                     | None                                     |
	| LCHIJA | psi                   | r1.1-77                  | Psi-r1.1-77.jar                                 | None                                     |
	| LCHIJA | magipsi               | 1.3                      | MagicalPsi-1.3.2.jar                            | None                                     |
	| LCHIJA | moreoverlays          | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                | None                                     |
	| LCHIJA | multimob              | 1.0.5                    | multimob-1.0.5.jar                              | None                                     |
	| LCHIJA | primitivemobs         | 1.2.3a                   | primitivemobs-1.2.3a.jar                        | None                                     |
	| LCHIJA | signpost              | 1.06.1                   | signpost-1.12-1.06.1.jar                        | None                                     |
	| LCHIJA | spartanweaponry       | beta 1.3.5               | SpartanWeaponry-1.12.2-beta-1.3.5.jar           | None                                     |
	| LCHIJA | spartanweaponryarcana | beta 1.0.3               | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar     | None                                     |
	| LCHIJA | storagedrawers        | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
	| LCHIJA | thaumictinkerer       | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar          | None                                     |
	| LCHIJA | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LCHIJA | vc                    | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                     | None                                     |
	| LCHIJA | waystones             | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                     | None                                     |
	| LCHIJA | wearablebackpacks     | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar              | None                                     |
	| LCHIJA | llibrary              | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mysticallib           | 1.12.2-1.4.0             | mysticallib-1.12.2-1.4.0.jar                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)
		- TwilightForestPlugin (Enabled/Not Forced)

	[Psi] Active spell: None
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6446
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Sunconure11** [comment]
boi this got fixed in the latest builds of the mod
