### ISSUE TITLE
Entity spawning not checking for biomedictionary

### ISSUE THREAD

**Issue by Calanon7** [Um-Mitternacht/Bewitchment#465]
Creatures should be spawning in appropriate biomedictionary biomes.

Creatures entities are only spawn in vanilla biomes.

I'm using biomes o' plenty and they do not spawn in those biomes.

Bewitchment: v0.0.21.2
Forge: v14.23.5.2847

**Comment by Sunconure11** [comment]
Can someone test this?

**Comment by Sunconure11** [comment]
No response. Closing.
