### ISSUE TITLE
Hydrophobia hasn't its right recipe.

### ISSUE THREAD

**Issue by bombsonmonday** [Um-Mitternacht/Bewitchment#466]
### this is the recipe to hydrophobia
![download](https://user-images.githubusercontent.com/58704526/70463869-8530a700-1a9c-11ea-9908-abb49e6b68d8.png)
### this is the recipe to overheating
![download (1)](https://user-images.githubusercontent.com/58704526/70463900-937ec300-1a9c-11ea-9e18-f16f92041d2f.png)

**Comment by anqingchen** [comment]
fixed now, will be out in the next update.
