### ISSUE TITLE
Poppets are not working like they should...

### ISSUE THREAD

**Issue by EnvyingGolem47** [Um-Mitternacht/Bewitchment#469]
### Expected Behavior
Affect the bound player by transferring damage to them

### Actual Behavior
Getting kicked from server with "Internal Server Error" or being told that entity cannot be found

### Steps to Reproduce
1. Make Poppet
2. Get taglock of another player
3. Bind Poppet to taglock
4. Try to use the intended function of the poppet on that player
Result: "Internal Server Error"/That person cannot be found

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 14.23.5.2847
Bewitchment: 0.0.21.2
Patchouli: 1.0-20
Baubles: 1.5.2

### Screenshots encouraged
https://imgur.com/a/xZvJX36

(Sorry for the weird aspect ratios in advanced)

### Logs, in the event of a crash

Server Log: https://pastebin.com/kvXknAnJ

(The client log just said "disconnected: Internal Server Error")

**Comment by anqingchen** [comment]
just pushed out a new version, think it's fixed there, please test it and see if it works. Thank you!

**Comment by EnvyingGolem47** [comment]
Sorry for the delayed response. I had to take care of somethings before I was able to test it...
As far as I can tell, it works. I was only able to test the Death Poppet and other protection poppets as the other players went to go play other games. I will be able to tell you about it either later tonight or tomorrow evening. Thank you for being active and a quick response! :D

**Comment by EnvyingGolem47** [comment]
I am able to stick needles and damage the target with Voodoo poppets but I cannot toss them around without the needles and just says "The target of this poppet is not found" even though I can damage them with needles

**Comment by anqingchen** [comment]
no tossing around function yet, and ill fix that "not found" thing later

**Comment by deathbycanon** [comment]
Playing MC eternal, voodoo poppet not working. When binding I get the error that the target is not found, however it does bind using up the tag lock kit and changing color, saying who it's bound to when mousing over it...  I get the same "not found" error when trying to stick with pins or shaking. It doesn't work at all as far as I can tell. The vampiric one works fine.

**Comment by Sunconure11** [comment]
Is this still an issue?

**Comment by TheOnlyChora** [comment]
As of today it's still an issue unfortunately
