### ISSUE TITLE
(SUGGESTION) Additional Rustic Compat - Tables

### ISSUE THREAD

**Issue by Aeonsteel** [Um-Mitternacht/Bewitchment#470]
Simply put, I would like to see new Tables from the wood added from this mod. I thought of this when I saw that this mod had Rustic compat, and immediately thought of Rustic Thaumaturgy's new tables. I understand that this will be very low priority if it does ever happen.

**Comment by Sunconure11** [comment]
This is indeed planned, along with stuff made from our metals and what not. Also, booze.

I had actually started on the compat, but I've been feeling sluggish for the past few days. Assigning @anqingchen to look at this. While you're at it, see if you can also figure out why I struggled with the biome changing rite.

**Comment by anqingchen** [comment]
rustic compat has been handled in a separate mod: https://www.curseforge.com/minecraft/mc-mods/rusticwitchcraft
