### ISSUE TITLE
Dynamic Trees Compat Issue (Oak Apple Gall)

### ISSUE THREAD

**Issue by Timeslice42** [Um-Mitternacht/Bewitchment#476]
### Expected Behavior
When cutting down or breaking the leaves of a Dynamic Trees Oak tree there should be a chance to get Oak Apple Gall drops.

### Actual Behavior
Currently the only way to obtain oak apple gall from DT oak trees is to shear the leaves, place them down, and then break them.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 0.0.21.3
Forge: 2847
Patchouli: 1.0-20
Baubles: 1.5.2
Dynamic Trees: 0.9.6

Also, what is the drop rate for Oak Apple Gall? Is it 1 in 200 like the vanilla apples?

**Comment by anqingchen** [comment]
They should drop now in the newest update.
