### ISSUE TITLE
Lingering harvest potion crashes game

### ISSUE THREAD

**Issue by stargaze44** [Um-Mitternacht/Bewitchment#480]
### Expected Behavior
Potion lingers with "Harvest" effect and continually grows crops 

### Actual Behavior
Game crashes when brew is thrown (Presumably due to this effect being instantaneous- I'm obviously not a developer but I assume it's because the effect executes instantly and tries to execute constantly when in a lingering brew)

### Steps to Reproduce
Brew a potion of lingering with the harvest effect (Example- x1 Mandrake root, x1 Gunpowder, x1 Owlet Wing, x1 Pumpkin)

Throw produced brew onto seed planted on hydrated farmland

Game will freeze, then crash. When world is attempted to load again, it will get stuck on "Building Terrain" step.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
bewitchment-1.12.2-0.0.21.1.jar
Baubles-1.12-1.5.2.jar
Patchouli-1.0-20.jar
Forge 14.23.5.2847

I have a number of other mods installed but I believe this is chiefly a Bewitchment issue.

**Comment by anqingchen** [comment]
please post crashlog

**Comment by Sunconure11** [comment]
Due to a lack of any logs, closing.
