### ISSUE TITLE
Rustic Thaumaturgy Seeds Sold By Hedge Witch

### ISSUE THREAD

**Issue by BoyarRex** [Um-Mitternacht/Bewitchment#481]
### Expected Behavior
 Already expected behavior, but unbalanced as the seeds normally require research and infusions beforehand.

### Actual Behavior
Hedge Witches are able to trade Shimmerpetal Bulb, Viscap Spores, and Cindermote Seeds.

### Steps to Reproduce
Find or summon a Hedge Witch with 1 of the Rustic Thaumaturgy seed trades, in the same spot as the 1-2 emerald trade for Mandrake Seeds, Nether Wart, Hellebore Seeds, etc.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2, Bewitchment: 1.12.2-0.0.21.5, Forge:  1.12.2-23.5.2847, Patchouli: 1.0-20, Baubles: 1.12-1.5.2

### Screenshots encouraged
![2019-12-28_23 36 51](https://user-images.githubusercontent.com/39660839/71553071-c3075800-29d6-11ea-99d7-98766595341e.png)

**Comment by Sunconure11** [comment]
It's intended for various seeds to be sold by hedge witches, yes, including modded ones, but we need a black list for certain seeds.

**Comment by Sunconure11** [comment]
This has since been fixed.
