### ISSUE TITLE
Issue with spinning wheel

### ISSUE THREAD

**Issue by Robonics** [Um-Mitternacht/Bewitchment#484]
### Expected Behavior
Recipe is put in spinning wheel and product is spun

### Actual Behavior
Recipe is put in spinning wheel but the wheel does not begin to spin

### Steps to Reproduce
Using [This](https://drive.google.com/drive/folders/1WPtRzuP07XopLoRr6B47Bgu08krxXGrw?usp=sharing) modpack

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC Ver 1.12.2
Forge Ver 1.12.2 - 14.23.5.2847
Bewitchment Ver 0.0.21.5.jar
Patchouli Ver 1.0-20
Baubles Ver 1.5.2

### Screenshots
![2020-01-04_18 06 07](https://user-images.githubusercontent.com/56417942/71772679-09037500-2f1d-11ea-807d-635af1c49c98.png)
No spinning action is taking place

**Comment by Sunconure11** [comment]
The spinning wheel requires an altar to run.

**Comment by anqingchen** [comment]
also, please do not redistribute mods like that, make a pack on curse!
