### ISSUE TITLE
Gridle of Dryads Not Working

### ISSUE THREAD

**Issue by mxnmnm** [Um-Mitternacht/Bewitchment#485]
### Expected Behavior
Bark should grow and as it grows it should fill in your empty armor slots

### Actual Behavior
The bark grows visually but the armor slots never get filled

### Steps to Reproduce
Wear armor that doesn't fill your armor bar
Wear gridle with the creative grimoire magia (unless there is no creative one and the one full of mp in jei is just a normal one filled to the max in which case there might be another part of the issue)
Wait for bark to grow
See bark grow without impacting armor bar

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
0.0.21.5
14.23.5.2847
1.0-20
1.5.2

### Screenshots encouraged
![2020-01-06_23 25 22](https://user-images.githubusercontent.com/8508976/71876617-0307c280-30dc-11ea-97d3-23d7b1bdd9e2.png)

**Comment by mxnmnm** [comment]
So after testing I've found that there is no creative mode grimoire magia which means that the girdle either gives back the magic used or it doesn't actually use up any magic and it's just visual (which would fit in the whole I can only see my wooden shell but it doesn't change anything on my armor bar thing) probably some weird syncing issue or something idk

**Comment by Sunconure11** [comment]
This still an issue?

**Comment by Mizque** [comment]
Does not show a change to armor, does grow on tinkers armor though which is nice.  Costs 20 EM from grim of magia per growth.  What exactly does the wood armor do, act as armor, or act as absorption?

**Comment by MoriyaShiine** [comment]
It doesn't add armor, it negates hits when there's wood on you.

**Comment by davmar0119** [comment]
wait it only does a chestplate(area thingy)

**Comment by davmar0119** [comment]
i thought it was a full body thing
