### ISSUE TITLE
Candle Visual Bug Better Foliage Compat Issue

### ISSUE THREAD

**Issue by mxnmnm** [Um-Mitternacht/Bewitchment#486]
### Expected Behavior
A candle being placed and looking normal

### Actual Behavior
You can see underneath the candle when it is placed

### Steps to Reproduce
Place candle on grass block (it might happen with other blocks idk)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
0.0.21.5
14.23.5.2847
1.0-20
1.5.2

### Screenshots encouraged
![2020-01-07_18 06 28](https://user-images.githubusercontent.com/8508976/71944477-ba521700-3178-11ea-8b95-8472b6c41492.png)

**Comment by anqingchen** [comment]
what other mods do you have installed? I don't have it on my end at the moment.

**Comment by mxnmnm** [comment]
I have a lot of other mods so I'm gonna try to find out which mod is causing the conflict and I'll let you know

**Comment by mxnmnm** [comment]
better foliage was the culprit

**Comment by MrGraphic** [comment]
To be exact the issue lies within connected grass textures. Just turn the feature off :) .
