### ISSUE TITLE
Mixin crash

### ISSUE THREAD

**Issue by bigenergy** [Um-Mitternacht/Bewitchment#487]
https://github.com/SpongePowered/SpongeCommon/issues/2458
Bewitchment does not work on latest versions SpongeForge 1.12.2-2838-7.1.9-RC3977+
[latest.log](https://github.com/Um-Mitternacht/Bewitchment/files/4048890/latest.log)

**Comment by bigenergy** [comment]
@Sunconure11 pls update mixin

**Comment by anqingchen** [comment]
Mixin update in 71211a3, Will come out with next update.
