### ISSUE TITLE
Dedicated server crash with Quark, Farseek, and world gen

### ISSUE THREAD

**Issue by katubug** [Um-Mitternacht/Bewitchment#488]
### Description of Issue
I run a server that has the MC.Eternal modpack (version 1.2) on it. Today my players received a crash during normal play. I have seen the same crash in the MC Eternal discord, and they reported that nothing was happening aside from exploration, which I suspect was the same case here.

If I'm reading the report correctly, I think I should report this to you? It seems that while attempting to generate terrain, something breaks a Quark Roots block, and the game gets hung up trying to calculate how many roots drop, modified by a Bewitchment attribute? I'm not at all positive about this, but that's my guess.

I am attempting a workaround by disabling Quark's Roots from generating, but since I'm not positive that's the problem, I thought it was best to report it as well. Please let me know if I should take this to the Quark team (or somewhere else?)

### Steps to Reproduce
It's difficult to reproduce, as the server has been running fine for about a week now, with this being the first instance of this crash. However, I believe that it would be replicatable by exploring the world with Quark, Farseek and Bewitchment installed.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 2847
Bewitchment: 0.0.21.5
Baubles: 1.5.2
Patchouli: 1.0-20
Quark: 1.6-177
AutoRegLib: 1.3-32
Farseek: 2.4

### Logs, in the event of a crash
Crash log: https://pastebin.com/4xLzR6ME
Latest.log: https://paste.ee/p/K5AIU
I do also have a debug.log from the same time, but it's enormous so I'd have to upload the file somewhere. Let me know if it would be helpful.

**Comment by Sunconure11** [comment]
It appears to be a crash between Quark and Farseek. Not us.

**Comment by Sunconure11** [comment]
Wait hold on, this is something I think got fixed in 0.21.6. Try the latest build from curse.

**Comment by katubug** [comment]
Ah, I'm not the pack author, but I will recommend it to them! Thank you very much. :)
