### ISSUE TITLE
Boline at less than 100% durability causes crashes on mouseover

### ISSUE THREAD

**Issue by OpenlyFay** [Um-Mitternacht/Bewitchment#492]
### Expected Behavior

Mousing over a boline brings up its tooltip

### Actual Behavior

Mousing over a boline at less than 100% durability, while in survival and in a Mystcraft age, causes the game to freeze and crash

### Steps to Reproduce

Use a boline while in survival. Make a Mystcraft age and enter it. Mouse over the boline in inventory while in survival.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2, Bewitchment: 1.12.2-0.0.21.6, Forge: 14.23.5.2847, Patchouli: 1.0-20, Baubles: 1.12.2-1.5.2

Mystcraft: 0.13.7.04

### Logs, in the event of a crash

[crash-2020-01-16_08.26.27-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4067686/crash-2020-01-16_08.26.27-client.txt)

**Comment by anqingchen** [comment]
Cannot replicate, please provide more detail

**Comment by OpenlyFay** [comment]
On top of Mystcraft, I also have the addons Pages (1.3.3), Linking Through The Ages (1.4.0), and More Mystcraft (0.8.5) installed, though I didn't think they were important enough to mention the first time. I don't think any of the other 120+ mods I have installed are interfering, as the bug only occurs in Mystcraft ages, not in the overworld.

Given that apparently it's a rendering error specifically, More Mystcraft seems to be the cause, as it has a feature that adds coloured suns, something that would probably have weird rendering/lighting code.

**Comment by Sunconure11** [comment]
Since it appears to not be us, closing.
