### ISSUE TITLE
Bewitchment/Quark Cave Root Crash

### ISSUE THREAD

**Issue by theceige** [Um-Mitternacht/Bewitchment#493]
### Expected Behavior
Breaking cave roots drops sprouts or cave root

### Actual Behavior
Nothing drops, VanillaFix reports an issue between Quark and Bewitchment. No other immediate issues, however this may be because Vanillafix prevents a CTD in Minecraft. After a period of time (I was just randomly exploring the world not interacting with anything) the game crashed and VanillaFix claims it is an interaction between quark and bewitchment. 

### Steps to Reproduce
Use quark and bewitchment, smack some cave roots (with vanillafix installed?)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 14.23.5.2847
Bewitchment: 0.0.21.5
Patchouli: 1.0-20
Baubles: 1.5.2

### Logs, in the event of a crash
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2020-01-16 20:37:56 EST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.func_181617_a(Util.java:531)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
    at java.util.AbstractList.add(AbstractList.java:148)
    at net.minecraft.util.NonNullList.add(SourceFile:58)
    at java.util.AbstractList.add(AbstractList.java:108)
    at com.bewitchment.common.item.equipment.baubles.ItemFortuneFavor.onBlockDrop(ItemFortuneFavor.java:36)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1300_ItemFortuneFavor_onBlockDrop_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
    at net.minecraft.block.Block.func_180653_a(Block.java:572)
    at net.minecraft.block.Block.func_176226_b(Block.java:564)
    at net.minecraft.block.Block.func_180657_a(Block.java:735)
    at vazkii.quark.world.block.BlockRoots.func_180657_a(BlockRoots.java:295)
    at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:216)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693)
    at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3391827336 bytes (3234 MB) / 5771362304 bytes (5504 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 103 mods loaded, 103 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                | Source                                          | Signature                                |
       |:------ |:------------------------ |:---------------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                 | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                      | 9.42                   | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                      | 8.0.99.99              | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
       | LCHIJA | forge                    | 14.23.5.2847           | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                  | minecraft.jar                                   | None                                     |
       | LCHIJA | opencomputers|core       | 1.7.5.192              | minecraft.jar                                   | None                                     |
       | LCHIJA | jei                      | 4.15.0.291             | jei_1.12.2-4.15.0.291.jar                       | None                                     |
       | LCHIJA | abyssalcraft             | 1.9.15                 | AbyssalCraft-1.12.2-1.9.15.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | mantle                   | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCHIJA | quark                    | r1.6-177               | Quark-r1.6-177.jar                              | None                                     |
       | LCHIJA | baubles                  | 1.5.2                  | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | thaumcraft               | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
       | LCHIJA | botania                  | r1.10-363              | Botania+r1.10-363.jar                           | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                  | Forgelin-1.8.4.jar                              | None                                     |
       | LCHIJA | librarianlib             | 4.20                   | librarianlib-1.12.2-4.20-release.jar            | None                                     |
       | LCHIJA | autoreglib               | 1.3-32                 | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCHIJA | psi                      | r1.1-77                | Psi-r1.1-77.jar                                 | None                                     |
       | LCHIJA | rpsideas                 | 2.4.2                  | rpsideas-2.4.2.jar                              | None                                     |
       | LCHIJA | tconstruct               | 1.12.2-2.13.0.171      | TConstruct-1.12.2-2.13.0.171.jar                | None                                     |
       | LCHIJA | acintegration            | 1.9.0                  | AbyssalCraft+Integration-1.12.2-1.9.0.jar       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | aiimprovements           | 0.0.1.3                | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
       | LCHIJA | guideapi                 | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
       | LCHIJA | bloodmagic               | 1.12.2-2.4.3-105       | BloodMagic-1.12.2-2.4.3-105.jar                 | None                                     |
       | LCHIJA | theoneprobe              | 1.4.28                 | theoneprobe-1.12-1.4.28.jar                     | None                                     |
       | LCHIJA | animus                   | 1                      | Animus-1.12-2.1.6.jar                           | None                                     |
       | LCHIJA | appleskin                | 1.0.9                  | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
       | LCHIJA | arcanearteries           | 0.0.1 - Beta           | ArcaneArteries-1.12.2-1.0.0.jar                 | None                                     |
       | LCHIJA | astralsorcery            | 1.10.20                | astralsorcery-1.12.2-1.10.20.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | backpack                 | 3.0.2                  | backpack-3.0.2-1.12.2.jar                       | None                                     |
       | LCHIJA | base                     | 3.13.0                 | base-1.12.2-3.13.0.jar                          | None                                     |
       | LCHIJA | patchouli                | 1.0-20                 | Patchouli-1.0-20.jar                            | None                                     |
       | LCHIJA | bewitchment              | 0.21.5                 | bewitchment-1.12.2-0.0.21.5.jar                 | None                                     |
       | LCHIJA | bibliocraft              | 2.4.5                  | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | LCHIJA | bloodarsenal             | 1.12.2-2.2.0-29        | BloodArsenal-1.12.2-2.2.1-29.jar                | None                                     |
       | LCHIJA | conarm                   | 1.2.5.3                | conarm-1.12.2-1.2.5.3.jar                       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | bloodtinker              | 1.0.5                  | bloodtinker-1.0.5.jar                           | None                                     |
       | LCHIJA | bookshelf                | 2.3.590                | Bookshelf-1.12.2-2.3.590.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | hammercore               | 2.0.6.4                | HammerCore-1.12.2-2.0.6.4.jar                   | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | botanicadds              | 4r                     | BotanicAdditions-1.12.2-4r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | bmtr                     | 0.4                    | BringMeTheRings-0.4.jar                         | None                                     |
       | LCHIJA | chameleon                | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | LCHIJA | chunkanimator            | 1.2                    | ChunkAnimator-MC1.12-1.2.jar                    | None                                     |
       | LCHIJA | clumps                   | 3.1.2                  | Clumps-3.1.2.jar                                | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358              | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux             | 2.1.0                  | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                 | 4.6.3                  | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
       | LCHIJA | cofhworld                | 1.3.1                  | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | doggytalents             | 1.15.1.4               | DoggyTalents-1.12.2-1.15.1.4-universal.jar      | None                                     |
       | LCHIJA | ebwizardry               | 4.2.7                  | ElectroblobsWizardry-4.2.7-MC1.12.2.jar         | None                                     |
       | LCHIJA | eplus                    | 5.0.176                | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enchantingwiththaumcraft | 1.2                    | enchantingwiththaumcraft-1.2.jar                | None                                     |
       | LCHIJA | enhancedarmaments        | 1.3.17                 | enhancedarmaments-1.3.17.jar                    | None                                     |
       | LCHIJA | minerva                  | 1.0.13                 | minerva-library-1.0.13.jar                      | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | extraalchemy             | 0.5.2                  | extraalchemy-0.5.2.jar                          | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | extrabotany              | 56                     | ExtraBotany-r1.1-56.jar                         | None                                     |
       | LCHIJA | fastfurnace              | 1.3.1                  | FastFurnace-1.12.2-1.3.1.jar                    | None                                     |
       | LCHIJA | fastbench                | 1.7.3                  | FastWorkbench-1.12.2-1.7.3.jar                  | None                                     |
       | LCHIJA | foamfix                  | 0.10.10-1.12.2         | foamfix-0.10.10-1.12.2.jar                      | None                                     |
       | LCHIJA | cfm                      | 6.3.1                  | furniture-6.3.1-1.12.2.jar                      | None                                     |
       | LCHIJA | jeiintegration           | 1.5.1.36               | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
       | LCHIJA | jeresources              | 0.9.2.60               | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
       | LCHIJA | libnine                  | 1.1.5                  | libnine-1.12.2-1.1.5.jar                        | None                                     |
       | LCHIJA | lostmagic                | 1.0                    | lostmagic-1.0.1.jar                             | None                                     |
       | LCHIJA | mcjtylib_ng              | 3.5.4                  | mcjtylib-1.12-3.5.4.jar                         | None                                     |
       | LCHIJA | roots                    | 1.12.2-3.0.21          | Roots-1.12.2-3.0.21.jar                         | None                                     |
       | LCHIJA | mysticalworld            | 1.12.2-1.6.1           | mysticalworld-1.12.2-1.6.1.jar                  | None                                     |
       | LCHIJA | opencomputers            | 1.7.5.192              | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
       | LCHIJA | parrotpower              | 1.12.2                 | parrotpower-1.3.4.jar                           | None                                     |
       | LCHIJA | placebo                  | 1.6.0                  | Placebo-1.12.2-1.6.0.jar                        | None                                     |
       | LCHIJA | thermalfoundation        | 2.6.3                  | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | plustic                  | 7.1.6.1                | plustic-7.1.6.1.jar                             | None                                     |
       | LCHIJA | psicosts                 | 1.0.1                  | psio-1.12.2-1.0.1.jar                           | None                                     |
       | LCHIJA | randomenchantments       | @VERSION@              | randomenchants-0.1.4.jar                        | None                                     |
       | LCHIJA | rangedpumps              | 0.5                    | rangedpumps-0.5.jar                             | None                                     |
       | LCHIJA | refinedstorage           | 1.6.15                 | refinedstorage-1.6.15.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | rftools                  | 7.72                   | rftools-1.12-7.72.jar                           | None                                     |
       | LCHIJA | rftoolsdim               | 5.71                   | rftoolsdim-1.12-5.71.jar                        | None                                     |
       | LCHIJA | roguelike                | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
       | LCHIJA | rustic                   | 1.1.2                  | rustic-1.1.2.jar                                | None                                     |
       | LCHIJA | rusticthaumaturgy        | 4.4a                   | Rustic+Thaumaturgy-4.4a.jar                     | None                                     |
       | LCHIJA | rusticwitchcraft         | 1.0.2                  | rusticwitcraft-1.0.2.jar                        | None                                     |
       | LCHIJA | storagedrawers           | 1.12.2-5.4.0           | StorageDrawers-1.12.2-5.4.0.jar                 | None                                     |
       | LCHIJA | thaumadditions           | 22r                    | ThaumicAdditions-1.12.2-22r.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | thaumicbrewing           | 1.0.2                  | thaumicbrewing-1.0.2.jar                        | None                                     |
       | LCHIJA | thaumcomp                | 0.5.1                  | ThaumicComputers-MC1.12.2-0.5.1.jar             | None                                     |
       | LCHIJA | tcinventoryscan          | 2.0.10                 | ThaumicInventoryScanning_1.12.2-2.0.10.jar      | None                                     |
       | LCHIJA | thaumicjei               | 1.6.0                  | ThaumicJEI-1.12.2-1.6.0-27.jar                  | None                                     |
       | LCHIJA | thaumicperiphery         | 0.3.1                  | thaumicperiphery-0.3.1.jar                      | None                                     |
       | LCHIJA | thermalexpansion         | 5.5.4                  | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermaldynamics          | 2.5.5                  | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tinkersjei               | 1.2                    | tinkersjei-1.2.jar                              | None                                     |
       | LCHIJA | tinkersoc                | 0.6                    | tinkersoc-0.6.jar                               | None                                     |
       | LCHIJA | topaddons                | 1.12.2-1.12.0          | topaddons-1.12.2-1.12.0.jar                     | None                                     |
       | LCHIJA | vampirism                | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                      | None                                     |
       | LCHIJA | teamlapen-lib            | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                      | None                                     |
       | LCHIJA | vampirism_integrations   | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0.jar          | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT        | VanillaFix-1.0.10-99.jar                        | None                                     |
       | LCHIJA | weirdinggadget           | 1.0                    | weirdinggadget-1.12.2-2.1.16-universal.jar      | None                                     |
       | LCHIJA | xaerominimap             | 1.19.6                 | Xaeros_Minimap_1.19.6_Forge_1.12.jar            | None                                     |
       | LCHIJA | xaeroworldmap            | 1.5.4                  | XaerosWorldMap_1.5.4_Forge_1.12.jar             | None                                     |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.6           | phosphor-1.12.2-0.2.6+build50-universal.jar     | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | librarianliblate         | 4.20                   | librarianlib-1.12.2-4.20-release.jar            | None                                     |
       | LCHIJA | mysticallib              | 1.12.2-1.4.0           | mysticallib-1.12.2-1.4.0.jar                    | None                                     |
  Loaded coremods (and transformers): LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      HCASM (HammerCore-1.12.2-2.0.6.4.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.5.jar)
                                        
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.20.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  HammerCore Debug Information: Dependent Mods:
                                    -Botanic Additions (botanicadds) @4r
                                    -Thaumic Additions: Reconstructed (thaumadditions) @22r
  [Psi] Active spell: None
  Suspected Mods: Bewitchment (bewitchment), Quark (quark)

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/bewitchment/files/2859072

Try this build, please.
