### ISSUE TITLE
Dynamic Trees Compat/Seeds

### ISSUE THREAD

**Issue by BoyarRex** [Um-Mitternacht/Bewitchment#496]
Technically a suggestion, so no template(?)
 
![2020-01-19_12 01 51](https://user-images.githubusercontent.com/39660839/72685404-bc40a200-3ab7-11ea-936e-0145ae78d761.png)
![2020-01-19_11 45 51](https://user-images.githubusercontent.com/39660839/72685407-bea2fc00-3ab7-11ea-8716-e5b86a8c4017.png)
 Naturally spawning Bewitchment trees and seeds work, but villager trades and loot chests contain saplings instead of seeds/berries. Would be a bit more consistent/less awkward to use if these were changed upon detecting dynamic trees.

**Comment by BoyarRex** [comment]
Druden drop saplings as well.

**Comment by Sunconure11** [comment]
Bump

**Comment by Sunconure11** [comment]
I have an idea for solving this for the most part. Will execute it in a few days.
