### ISSUE TITLE
Crashing during startup

### ISSUE THREAD

**Issue by coke505** [Um-Mitternacht/Bewitchment#497]
### Expected Behavior
Game loads up properly without crashing during boot up screen

### Actual Behavior
Game crashed during boot up screen

### Steps to Reproduce
I'm thinking this is a mod conflict issue since when I remove bewitchment it loads fine

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft = 1.12.2
Bewitchment = 0.0.21.6
Forge = 14.23.5.2768
Patchouli = 1.10-20
Baubles = 1.5.2
### Logs, in the event of a crash
https://pastebin.com/gzbgNGzR

**Thank you for taking the time to look at this, all help is appreciated.**

**Comment by Sunconure11** [comment]
wat

**Comment by anqingchen** [comment]
update forge
