### ISSUE TITLE
Terracotta generation

### ISSUE THREAD

**Issue by marklinndsa** [Um-Mitternacht/Bewitchment#498]
### Expected Behavior

Witch's oven should not produce anything without ingredients

### Actual Behavior

If there is fuel in the oven but no other ingredients oven will burn fuel and produce terracotta blocks ex nihilo

### Steps to Reproduce

Put fuel (I used coal) in a witch's oven with no other ingredients.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2
Bewitchment: 0.0.21.4
Forge: 1.12.2-14.23.5.2846
Patchouli: 1.0-20
Baubles: 1.5.2

**Comment by marklinndsa** [comment]
Just saw a similar bug covered by #397

**Comment by anqingchen** [comment]
Update the mod
