### ISSUE TITLE
Memory leak while rendering custom bewitchment armor

### ISSUE THREAD

**Issue by samakotleta** [Um-Mitternacht/Bewitchment#500]
### Expected Behavior
no leak

### Actual Behavior
leak

### Steps to Reproduce
Put on witch robe, pants and hood, then press f5 or open inventory window. Task manager will show you constant memory leaking. Maybe same issue with other custom armor models.

I must say this trouble is absolutely equivalent to this (already resolved) issue with Roots mod:
https://github.com/MysticMods/Roots/issues/154

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Issue was noticed this summer while bewitchment was in beta state, same behavior now with latest release version. Decided to report this just now.

**Comment by Sunconure11** [comment]
Fixed in dev... possibly.
