### ISSUE TITLE
Placing a statue with /setblock crashes the game 

### ISSUE THREAD

**Issue by DashingViridian** [Um-Mitternacht/Bewitchment#502]
Expected Behavior: The lower half of the block is placed normally?

Actual Behavior: The game crashes and the world loads briefly before crashing again if Minecraft is closed and reopened.

Steps to Reproduce: Do /setblock ~ ~ ~ bewitchment:stone_leonard_statue

Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used:
Minecraft 1.12.2, BW 0.0.21.6, Baubles 1.5.2, Patchouli 1.0-20, Forge 14.23.5.2847

Logs
https://paste.dimdev.org/otufiyehen.mccrash

**Comment by Sunconure11** [comment]
Just place them down manually. They aren’t meant to be placed via setblock.
