### ISSUE TITLE
Vanilla Fix picks up an issue with Bewitchment

### ISSUE THREAD

**Issue by MannyInTheMix** [Um-Mitternacht/Bewitchment#504]
### Logs, in the event of a crash
https://paste.dimdev.org/reduvabitu.mccrash

**Comment by Water-Moon** [comment]
`public IMessage onMessage(SpawnBubble message, MessageContext ctx) `
Personal opinion: Looks like the "message" parameter can be null...?
probably a `message != null` might be good...?

**Comment by Sunconure11** [comment]
Known issue. Trying to look into this. See #616
