### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by Zack7292** [Um-Mitternacht/Bewitchment#506]
### Expected Behavior

my game to lunch
### Actual Behavior

he game loading screen doesn't even load, it just immediately crash
### Steps to Reproduce
open your game

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

latest of each (1.12.2)
### Logs, in the event of a crash
there no crashlog since it dosn't even lunch, but there a log: https://pastebin.com/HDRYnHmV

**Comment by anqingchen** [comment]
Did not find lunch in my game, going to starve without further instructions
