### ISSUE TITLE
1.12.2-0.0.21.7 Mixin related crash on client

### ISSUE THREAD

**Issue by aking4125** [Um-Mitternacht/Bewitchment#507]
### Expected Behavior
Minecraft should launch normally

### Actual Behavior
Minecraft crashes with an error related to mixin.

### Steps to Reproduce
Updated Bewitchment from 0.0.21.7 from 0.0.21.6 and gets this crash. 

0.0.21.6 doesn't crash. Pack loads fine.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment-1.12.2-0.0.21.7
Baubles-1.12-1.5.2
Forge 1.12.2 - 14.23.5.2847
Patchouli-1.0-20.jar

### Logs, in the event of a crash
https://paste.dimdev.org/irazavatar.mccrash

**Comment by bigenergy** [comment]
i get same crash

**Comment by samakotleta** [comment]
can confirm

**Comment by MoriyaShiine** [comment]
I've archived 0.21.7 for now, use 0.21.6 while waiting for a fix. :)

**Comment by aking4125** [comment]
You got it. We'll be using 0.21.6 for the time being.
