### ISSUE TITLE
The golem press in thaumcraft 6 does not work

### ISSUE THREAD

**Issue by Dalenir** [Um-Mitternacht/Bewitchment#509]
### Expected Behavior

Golem press in thaumcraft 6 not works in multiplayer.

### Actual Behavior

Golem press in thaumcraft 6 does not work in multiplayer. Green button for start is clicks, but the the process does not begin at all, all items are not taken. In case of removal of Bewitchment, then everything works as it should.

### Steps to Reproduce

Start server with spongeforge, bewitchment and thaumcraft.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft 1.12.2 
Bewitchment 0.0.21.6 
Patchouli-1.0-20
Forge - 14.23.5.2838

### If this is a question, developer commentary, or a suggestion, ignore this template

It's an old bug with Thaumcraft 6 compatibility. It sometimes appeared in other mods, but then it was fixed in updates.

**Comment by Sunconure11** [comment]
Link to an example of a mod that fixed this. I have no troubles with the press at all.

**Comment by Dalenir** [comment]
For example, [here ](https://www.reddit.com/r/Thaumcraft/comments/aiyufw/golem_press_problem/)it is engineered golems, but I remember that I had a similar problem with some other mod.

I'm sorry, I looked for a reason of this bug yesterday for a very long time and before writing here, I did not check on a clean build with thaumcraft and bewitchment. It seems that the problem is caused by the presence of bewitchment AND some other mod in my modpack (now I tried to disable all the thaumcraft-related mods, but I can’t boast of any successes). 

So far, only a clean build with bewitchment and removal of bewitchment from the modpack is fixing the golem press on my server.

**Comment by Dalenir** [comment]
Okay, I'm close to giving up. This time, a clean installation did not help. In the attached screenshot, the contents of the mods folder. As you can see, there is only thaumcraft, bewitchment and what they need. 

![image](https://user-images.githubusercontent.com/60537405/73607488-9b07a780-45c7-11ea-8769-91c635f0ddb4.png)

This is very strange, because earlier I tried the same modpack (same sponge and forge also) and the press worked fine (revious post). And without bewitchment, the press functioned again. 

Please note that this happends only in multiplayer. Maybe only on forge, idk. I'm afraid that I cannot provide more useful information.

**Comment by Sunconure11** [comment]
@Aelpecyem Can you investigate this?

**Comment by Sunconure11** [comment]
I had someone replicate this on a server. This issue did not pop up.
