### ISSUE TITLE
New Golems/Name Issues

### ISSUE THREAD

**Issue by BoyarRex** [Um-Mitternacht/Bewitchment#511]
### Expected Behavior
Silver and Cold Iron plates are displayed in the Golemancy research tab, Silver plate names are displayed correctly, "Blessed" golem trait (Silver) description displayed correctly.

### Actual Behavior
Silver and Cold Iron ingots are displayed in the Golemancy research tab, Silver plate names aren't displaying properly, "Blessed" golem trait (Silver) description isn't displayed properly.

### Steps to Reproduce
Not a crash or major gameplay bug, so does this apply?

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2, Bewitchment: 1.12.2-0.0.21.8, Forge: 1.12.2-23.5.2847, Patchouli: 1.0-20, Baubles: 1.12-1.5.2

### Screenshots encouraged
![Issue1](https://user-images.githubusercontent.com/39660839/73806844-a0681c00-4798-11ea-9b47-11569a51bd3a.png)
![2020-02-04_21 44 59](https://user-images.githubusercontent.com/39660839/73806849-a78f2a00-4798-11ea-8ab6-e0cca8a665d3.png)
![2020-02-04_21 45 01](https://user-images.githubusercontent.com/39660839/73806858-ae1da180-4798-11ea-98a1-898865396428.png)

**Comment by Sunconure11** [comment]
Will fix tomorrow

**Comment by Sunconure11** [comment]
Fixed in dev.
