### ISSUE TITLE
Lizardpocalypse still going on in 21.9, might be biome specific now?

### ISSUE THREAD

**Issue by estradus** [Um-Mitternacht/Bewitchment#513]
So, I decided to clean up the lizards around my base (due to a mishap with the Champions mod, the lizards all had the plague and were constantly spreading poison between each other so this became a big deal to solve).  I went in and started killing them by the hundred.  I have a box with 5000 lizard legs in it.  

The lizards I killed in the field didnt seem to respawn.  It took a few goes to be completely certain, but the lizards I killed in the forest were back almost instantly.

Minecraft 1.12.2, bewitchment 21.9, forge 14.23.5.2847, baubles 12.15.2.  Yes, I deleted my default config before I started the game up with 21.9.

**Comment by MokahTGS** [comment]
Confirmed.  Lizards everywhere!  New config for us and that's when the problem started.

**Comment by Sunconure11** [comment]
Fixed in dev. Expect the update tomorrow.
