### ISSUE TITLE
Crash during game launch - .NoSuchMethodError on ReflectionHelper.findField()

### ISSUE THREAD

**Issue by Juko8** [Um-Mitternacht/Bewitchment#517]
### Expected Behavior
Loading and launching the game

### Actual Behavior
Crash back to launcher

### Steps to Reproduce
1. Press play in launcher with forge installation chosen
2. Crashes right at the end of 2/7 initializing mods

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2 Minecraft, 
tried both Bewitchment 0.0.21.9 and 0.0.21.10,
Forge 14.23.5.2768
Patchouli 1.0-20
Baubles 1.5.2

### Logs, in the event of a crash
https://pastebin.com/rViKg7Y5

**Comment by Sunconure11** [comment]
Install latest build of forge for 1.12.2.
