### ISSUE TITLE
Add a thing in the config to allow user defined alter items.

### ISSUE THREAD

**Issue by Mizhok** [Um-Mitternacht/Bewitchment#519]
Having candles from this mod, Thaumcraft, Quark, Rustic and Harvestcraft, and only Bewitchment candles only work on alters is pretty annyoing. Can we get some user defined alter addons?

**Comment by Sunconure11** [comment]
Bring this to moretweaker.

https://www.curseforge.com/minecraft/mc-mods/moretweaker
