### ISSUE TITLE
Crashing with LiteLoader (have logs)

### ISSUE THREAD

**Issue by RedXStone** [Um-Mitternacht/Bewitchment#520]
### Actual Behavior
Just crushed and nothing, in case MultiMC can save logs and that may saw (details you may see in logs)

### Steps to Reproduce
nothing happened, just crashing with exit code: 1, until launching MC and when was saw "Settings user: Nickname"
That log contain spongepowered.org, but I haven't sponge in my client

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: **1.12.2**
Forge: **14.23.5.2847**
Bewitchment: **1.12.2_0.0.21.9**
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

### Screenshots encouraged
![trick](https://user-images.githubusercontent.com/46400591/75096609-5f527300-55b2-11ea-8e04-bdd7ffb9f81c.png)

### Logs, in the event of a crash
https://paste.ee/p/90007

**Comment by Sunconure11** [comment]
The paste expired. I can’t help unless you still have the issue on hand.
