### ISSUE TITLE
Witches oven bug

### ISSUE THREAD

**Issue by bigenergy** [Um-Mitternacht/Bewitchment#521]
Bug with a witches oven - if you throw some fuel in them, and do not put anything in other slots, then charcoal will automatically appear (1: 2 - 1 coal = 2 charcoal). So you can "double" the amount of coal

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment-1.12.2-0.0.21.10
forge-1.12.2-14.23.5.2847

**Comment by bigenergy** [comment]
Any ideas?

**Comment by pterolatypus** [comment]
Seems the same as #373. What other mods do you have?

**Comment by Sunconure11** [comment]
Known issue. If someone knows a way to fix it, feel free to submit a PR.
