### ISSUE TITLE
Cannot have farms due to Bewitchment mobs

### ISSUE THREAD

**Issue by Rithenar** [Um-Mitternacht/Bewitchment#523]
### Expected Behavior
There should be a way to avoid ghosts and black dogs from spawning whether is with a device or by configs. When creating an animal farm (in this case FluidCows), the ghosts and dogs kill the cows. I can fix sometimes by sleeping but if I am not in my base or there is a Blood Moon I cannot babysit the farm and avoid these pests to kill the animals

### Actual Behavior
See above

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC: 1.12.2
Forge: 14.23.5.2847
Bewitchment: 0.0.21.10
Patchouli: 1.0-20
Baubles: 1.5.2

**Comment by Rithenar** [comment]
Never mind. I added a few more Mega Torches and that seems to have stopped them

**Comment by Sunconure11** [comment]
There's a device planned soon that will help. Salt can keep out the black dogs.
