### ISSUE TITLE
[BUG] Cauldron teleport doesn't add text to Chat History

### ISSUE THREAD

**Issue by Shazuli** [Um-Mitternacht/Bewitchment#524]
### Expected Behavior
When writing in chat it should add the text string to the history just like regular text messages and commands.

### Actual Behavior
It doesn't add it to the message history. I like it doesn't send an actual message in chat as that would be a bit annoying on servers (and a potential breach to your base).

### Steps to Reproduce
1. Stand in Cauldron with teleport brew bubbling in it.
2. Open chat and type the desired location and press enter.
3. The message wasn't added to chat history.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Mod | Version
------ | ---------
Baubles | 1.12-1.5.2
Bewitchment | 1.12.2-0.0.21.10
Forge | 14.23.5.2847
Minecraft | 1.12.2
Patchouli | 1.0-20

**Comment by Sunconure11** [comment]
This is intentional.
