### ISSUE TITLE
This visual effect that greys your screen will not go away until you relog.

### ISSUE THREAD

**Issue by ProsperCraft** [Um-Mitternacht/Bewitchment#525]
### Expected Behavior
Effect wears off.

### Actual Behavior
You have to relog to get rid of it.

### Steps to Reproduce
Get the visual effect from a ghost or mandrake, then it never goes away until you relog.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
forge-1.12.2-14.23.5.2847-universal
bewitchment-1.12.2-0.0.21.10

### Screenshots encouraged
![2020-03-03_17 12 30](https://user-images.githubusercontent.com/4427684/75832330-39c42700-5d73-11ea-8ae8-3ef6de4a4cfe.png)

**Comment by anqingchen** [comment]
We did not add any visuals in this mod, it's probably something else causing this effect.
