### ISSUE TITLE
Not getting cloudy oil from jungle sapling or cactus

### ISSUE THREAD

**Issue by melodious1963** [Um-Mitternacht/Bewitchment#529]
### Expected Behavior
Receiving cloudy oil after smelting the sapling or cactus in the witches' oven.

### Actual Behavior
Getting only wood ash or cactus green.

### Steps to Reproduce
Put the sapling or the cactus in the oven.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Forge 1.12.2-14.23.5.2847
Bewitchment 1.12.2-0.0.21.10
Patchouli 1.0-20
Baubles 1.12-1.5.2

**Comment by Ayrion** [comment]
You did remember to put clay jars in the oven right?

**Comment by melodious1963** [comment]
Yes, I also tried it without the clay jars

**Comment by Ayrion** [comment]
Works on my end but it's not a 100% chance to get the oil

**Comment by melodious1963** [comment]
Wait, it isn't?
Could that be specified somewhere maybe then?
