### ISSUE TITLE
Recipe issue related to compatibility with Dynamic Trees.

### ISSUE THREAD

**Issue by Lawrence-Wolf** [Um-Mitternacht/Bewitchment#532]
Using latest version of the mods, I have noticed there is no recipe to turn the Dynamic Trees version of "saplings" into the Bewitchment version, and any attempt to plant the normal Bewitchment version of said saplings, to get the normal type, turns them immediately into the Dynamic Trees one, causing you to never get the saplings that are needed for things such as the broom rituals, unless you are lucky to find in say, a chest, or traded for. The biggest issue, in my opinion, is the Dragon's Blood tree, as that takes forever, and unless you nametag the Alchemist, they will despawn, and you must keep finding them, all so you can get a simple sapling. Now, on an unrelated topic really, I noticed the Discord invite on wiki is expired, so if someone can send it to me, and maybe fix the one on the wiki, that would be amazing.

**Comment by Sunconure11** [comment]
Working on a commit that should fix most of this.

**Comment by Sunconure11** [comment]
Was unable to get around to this, but I’ll look into it in the next few days. I have an idea, but it will need a bit of testing.
