### ISSUE TITLE
[Visual] Cauldron is bugged with Faithful x32

### ISSUE THREAD

**Issue by drakray** [Um-Mitternacht/Bewitchment#533]
Similar to #134 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC 1.12.2
Bewitchment 0.0.21.10
Forge 2847
Patchouli 1.0-20
Baubles 1.5.2
[Faithful 1.12.2-rv4](https://www.curseforge.com/minecraft/texture-packs/faithful-32x/files/2480942)
[Custom ModdedFaithful](http://www.drakray.com/MC/ModdedFaithful%201.12.2-rv1.zip) (might not be necessary)

### Screenshots encouraged
![2020-03-18_11 41 18](https://user-images.githubusercontent.com/4303126/76978907-a875b880-690d-11ea-9539-cab27aec67b5.png)

**Comment by Sunconure11** [comment]
Get them to add compat with BW. This isn’t our fault.
