### ISSUE TITLE
Oven automation issues

### ISSUE THREAD

**Issue by Teibidh** [Um-Mitternacht/Bewitchment#536]
### Expected Behavior
By connecting EnderIO Item Conduits (or whatever flavor of this you prefer) to the appropriate sides of the oven one is able to feed items to the appropriate slots within the entity.

### Actual Behavior
Insert actions on any side of the block aside from the bottom insert the item in to the fuel slot resulting in burning up saplings. The bottom reliably extracts items from the output slot, but also inserts to the output slot.

### Steps to Reproduce
Connect a chest to an EnderIO item conduit.
Set conduit face on chest to "Extract" and "Always On".
Run conduit to any given face on oven.
Set conduit face on oven to "insert".
Profit.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
0.0.2.1
14.23.5.2847
1.0-20
1.5.2

**Comment by Sunconure11** [comment]
This still a problem?
