### ISSUE TITLE
Client crash when creating alter in magic kingdom biome.

### ISSUE THREAD

**Issue by NickTimmermans26** [Um-Mitternacht/Bewitchment#537]
### Expected Behavior
Started a base in a biome from the magic kingdom mod, was expecting the alter to just form on right click with a carpet

### Actual Behavior
On right click the world crashed. Could reproduce this in several of magic kingdom's biome in different worlds with and without other mods. The altar creation does work in vanilla biomes with the mod installed so it might be an issue with how magic kingdom generates their biomes? Posted it here first because the crash, as far as I can tell is due to bewitchment's behavior.

### Steps to Reproduce
Load up bewitchment and dependencies with the magic kindom mod, place down a 2x3 altar and right click it with a (white) carpet

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12
Bewitchment: 1.12.2-0.0.21.10.jar
Forge: forge-14.13.4.2847
Patchouili: Patchouli-1.0-20.jar
Baubles:: Baubles-1.12-1.5.2.jar
Magic Kingdom MK1.12.2-1.2.10.jar

### Logs, in the event of a crash
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.10.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/22/20 4:20 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=axis, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, y, z]} as it does not exist in BlockStateContainer{block=som:log_pine, properties=[axis]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:215)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.convert(TileEntityWitchesAltar.java:194)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.registerToMap(TileEntityWitchesAltar.java:208)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.scan(TileEntityWitchesAltar.java:133)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.forceScan(TileEntityWitchesAltar.java:123)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.onLoad(TileEntityWitchesAltar.java:78)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_175690_a(World.java:2463)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:624)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at com.bewitchment.common.block.BlockWitchesAltar.createAltar(BlockWitchesAltar.java:221)
	at com.bewitchment.common.block.BlockWitchesAltar.func_180639_a(BlockWitchesAltar.java:141)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:215)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.convert(TileEntityWitchesAltar.java:194)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.registerToMap(TileEntityWitchesAltar.java:208)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.scan(TileEntityWitchesAltar.java:133)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.forceScan(TileEntityWitchesAltar.java:123)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.onLoad(TileEntityWitchesAltar.java:78)
	at net.minecraft.world.World.func_175700_a(World.java:1924)
	at net.minecraft.world.World.func_175690_a(World.java:2463)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:624)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at com.bewitchment.common.block.BlockWitchesAltar.createAltar(BlockWitchesAltar.java:221)
	at com.bewitchment.common.block.BlockWitchesAltar.func_180639_a(BlockWitchesAltar.java:141)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MushWolf'/1811, l='MpServer', x=-183.63, y=101.00, z=-710.33]]
	Chunk stats: MultiplayerChunkCache: 386, 386
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (256,64,200), Chunk: (at 0,4,8 in 16,12; contains blocks 256,0,192 to 271,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1498 game time, 1498 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 141 total; [EntityZombie['Zombie'/14337, l='MpServer', x=-181.50, y=15.00, z=-785.50], EntityZombie['Zombie'/14338, l='MpServer', x=-182.50, y=15.00, z=-784.50], EntityZombie['Zombie'/14339, l='MpServer', x=-174.75, y=16.00, z=-790.50], EntitySkeleton['Skeleton'/14381, l='MpServer', x=-204.52, y=33.00, z=-733.28], EntityZombie['Zombie'/14401, l='MpServer', x=-175.77, y=15.00, z=-779.49], EntityZombie['Zombie'/14402, l='MpServer', x=-187.68, y=13.00, z=-782.20], EntityZombie['Zombie'/14403, l='MpServer', x=-179.50, y=14.00, z=-776.50], EntityCreeper['Creeper'/14404, l='MpServer', x=-179.38, y=14.00, z=-779.83], EntityCreeper['Creeper'/14406, l='MpServer', x=-258.50, y=68.00, z=-780.50], EntityZombie['Zombie'/14441, l='MpServer', x=-175.82, y=57.00, z=-771.50], EntityZombie['Zombie'/14442, l='MpServer', x=-177.50, y=57.00, z=-773.50], EntitySkeleton['Skeleton'/14443, l='MpServer', x=-170.50, y=57.00, z=-772.50], EntityCreeper['Creeper'/14456, l='MpServer', x=-187.49, y=29.00, z=-733.21], EntitySkeleton['Skeleton'/14457, l='MpServer', x=-185.50, y=26.00, z=-727.50], EntityZombie['Zombie'/14475, l='MpServer', x=-214.50, y=46.00, z=-790.50], EntityZombie['Zombie'/14476, l='MpServer', x=-209.78, y=51.00, z=-786.56], EntityPlayerSP['MushWolf'/1811, l='MpServer', x=-183.63, y=101.00, z=-710.33], EntitySkeleton['Skeleton'/14578, l='MpServer', x=-199.50, y=26.00, z=-724.50], EntitySkeleton['Skeleton'/14585, l='MpServer', x=-189.50, y=27.00, z=-744.50], EntityZombie['Zombie'/14586, l='MpServer', x=-234.50, y=29.00, z=-790.50], EntitySkeleton['Skeleton'/14597, l='MpServer', x=-187.50, y=11.00, z=-779.50], EntityZombie['Zombie'/14605, l='MpServer', x=-178.50, y=19.00, z=-772.50], EntityCreeper['Creeper'/14621, l='MpServer', x=-117.20, y=29.00, z=-710.46], EntityZombie['Zombie'/14622, l='MpServer', x=-205.50, y=33.00, z=-758.50], EntitySkeleton['Skeleton'/14635, l='MpServer', x=-184.50, y=60.00, z=-767.50], EntitySkeleton['Skeleton'/14650, l='MpServer', x=-205.50, y=19.00, z=-714.50], EntitySkeleton['Skeleton'/14651, l='MpServer', x=-204.50, y=19.00, z=-718.50], EntityZombie['Zombie'/14652, l='MpServer', x=-202.50, y=19.00, z=-719.50], EntityZombie['Zombie'/14653, l='MpServer', x=-204.50, y=19.00, z=-714.50], EntitySpider['Spider'/14665, l='MpServer', x=-253.50, y=30.00, z=-761.50], EntitySkeleton['Skeleton'/14667, l='MpServer', x=-255.50, y=30.00, z=-760.50], EntitySkeleton['Skeleton'/14668, l='MpServer', x=-256.50, y=30.00, z=-760.50], EntityCreeper['Creeper'/14686, l='MpServer', x=-143.50, y=17.00, z=-773.50], EntityZombie['Zombie'/14687, l='MpServer', x=-145.56, y=18.00, z=-780.26], EntityCreeper['Creeper'/14704, l='MpServer', x=-195.50, y=57.00, z=-739.50], EntityCreeper['Creeper'/14705, l='MpServer', x=-196.50, y=57.00, z=-738.50], EntitySkeleton['Skeleton'/14727, l='MpServer', x=-226.29, y=20.00, z=-776.48], EntitySkeleton['Skeleton'/14742, l='MpServer', x=-256.50, y=66.00, z=-780.50], EntityZombie['Zombie'/14743, l='MpServer', x=-258.50, y=66.00, z=-775.50], EntityZombie['Zombie'/14755, l='MpServer', x=-175.50, y=18.00, z=-781.50], EntityZombie['Zombie'/14801, l='MpServer', x=-129.50, y=18.00, z=-694.50], EntitySkeleton['Skeleton'/14807, l='MpServer', x=-261.50, y=48.00, z=-767.50], EntityItem['item.tile.sapling.oak'/14820, l='MpServer', x=-142.44, y=69.00, z=-757.13], EntityItem['item.tile.plant_beanstalk'/14829, l='MpServer', x=-143.29, y=66.00, z=-729.52], EntityItem['item.tile.plant_beanstalk'/14836, l='MpServer', x=-217.04, y=69.00, z=-762.86], EntityCow['Cow'/13468, l='MpServer', x=-133.81, y=78.00, z=-636.42], EntityCow['Cow'/13469, l='MpServer', x=-136.50, y=78.00, z=-634.33], EntityCow['Cow'/13470, l='MpServer', x=-136.50, y=78.00, z=-633.36], EntityCow['Cow'/13471, l='MpServer', x=-139.50, y=79.00, z=-637.50], EntityCow['Cow'/13472, l='MpServer', x=-260.50, y=70.00, z=-647.50], EntityCow['Cow'/13473, l='MpServer', x=-260.50, y=70.00, z=-645.50], EntityCow['Cow'/13474, l='MpServer', x=-258.50, y=70.00, z=-644.50], EntityCow['Cow'/13475, l='MpServer', x=-262.50, y=68.01, z=-647.50], EntityLizard['Lizard'/13486, l='MpServer', x=-126.50, y=64.00, z=-659.50], EntityLizard['Lizard'/13487, l='MpServer', x=-125.50, y=63.00, z=-662.50], EntityLizard['Lizard'/13488, l='MpServer', x=-127.50, y=64.00, z=-660.50], EntityLizard['Lizard'/13489, l='MpServer', x=-130.50, y=64.00, z=-661.50], EntityCow['Cow'/13494, l='MpServer', x=-163.50, y=66.00, z=-664.50], EntityWolf['Wolf'/13495, l='MpServer', x=-153.50, y=64.00, z=-675.50], EntityWolf['Wolf'/13496, l='MpServer', x=-156.50, y=63.00, z=-676.50], EntityWolf['Wolf'/13497, l='MpServer', x=-157.50, y=63.00, z=-676.50], EntityCow['Cow'/13505, l='MpServer', x=-244.62, y=71.00, z=-666.42], EntityCow['Cow'/13506, l='MpServer', x=-247.22, y=72.00, z=-667.49], EntityCow['Cow'/13507, l='MpServer', x=-236.82, y=74.00, z=-676.36], EntityCow['Cow'/13508, l='MpServer', x=-244.50, y=72.00, z=-671.50], EntityCow['Cow'/13510, l='MpServer', x=-265.23, y=68.00, z=-678.48], EntityCow['Cow'/13511, l='MpServer', x=-263.50, y=68.00, z=-676.50], EntityCow['Cow'/13512, l='MpServer', x=-263.50, y=68.00, z=-676.50], EntityCow['Cow'/13513, l='MpServer', x=-262.50, y=67.00, z=-679.50], EntityCow['Cow'/13518, l='MpServer', x=-232.22, y=70.00, z=-686.49], EntityCow['Cow'/13519, l='MpServer', x=-222.82, y=68.00, z=-682.50], EntityCow['Cow'/13520, l='MpServer', x=-221.50, y=64.00, z=-679.45], EntityCow['Cow'/13521, l='MpServer', x=-221.50, y=64.00, z=-680.41], EntityCow['Cow'/13534, l='MpServer', x=-178.54, y=102.00, z=-707.20], EntityCow['Cow'/13535, l='MpServer', x=-177.50, y=100.00, z=-697.50], EntityCow['Cow'/13536, l='MpServer', x=-173.51, y=103.00, z=-708.23], EntityCow['Cow'/13537, l='MpServer', x=-164.39, y=64.00, z=-704.17], EntityCow['Cow'/13561, l='MpServer', x=-191.50, y=76.00, z=-740.50], EntityCow['Cow'/13562, l='MpServer', x=-190.80, y=77.00, z=-736.48], EntityCow['Cow'/13563, l='MpServer', x=-192.50, y=76.00, z=-739.50], EntityCow['Cow'/13564, l='MpServer', x=-183.82, y=78.00, z=-739.50], EntityCow['Cow'/13565, l='MpServer', x=-136.50, y=67.00, z=-739.50], EntityCow['Cow'/13566, l='MpServer', x=-137.50, y=67.00, z=-739.50], EntityCow['Cow'/13567, l='MpServer', x=-138.50, y=68.00, z=-742.50], EntityCow['Cow'/13568, l='MpServer', x=-139.50, y=67.00, z=-740.50], EntityChicken['Chicken'/13574, l='MpServer', x=-125.50, y=67.00, z=-743.50], EntityChicken['Chicken'/13575, l='MpServer', x=-127.19, y=67.00, z=-742.34], EntityChicken['Chicken'/13576, l='MpServer', x=-125.50, y=67.00, z=-738.50], EntityChicken['Chicken'/13577, l='MpServer', x=-125.50, y=67.00, z=-739.50], EntityNobleTree['Noble Tree Spirit'/13582, l='MpServer', x=-200.50, y=70.00, z=-745.50], EntityNobleTree['Noble Tree Spirit'/13583, l='MpServer', x=-200.50, y=65.00, z=-747.50], EntityNobleTree['Noble Tree Spirit'/13584, l='MpServer', x=-200.50, y=70.00, z=-743.50], EntityNobleTree['Noble Tree Spirit'/13585, l='MpServer', x=-200.50, y=71.00, z=-743.50], EntityNobleTree['Noble Tree Spirit'/13586, l='MpServer', x=-197.50, y=70.00, z=-744.50], EntityNobleTree['Noble Tree Spirit'/13587, l='MpServer', x=-200.50, y=65.00, z=-747.50], EntityNobleTree['Noble Tree Spirit'/13588, l='MpServer', x=-199.50, y=68.00, z=-747.50], EntityDryad['Dryad'/13589, l='MpServer', x=-200.50, y=68.00, z=-745.50], EntityPig['Pig'/13590, l='MpServer', x=-192.50, y=71.00, z=-747.45], EntityPig['Pig'/13591, l='MpServer', x=-184.00, y=71.00, z=-748.50], EntityPig['Pig'/13592, l='MpServer', x=-182.80, y=71.00, z=-748.50], EntityPig['Pig'/13593, l='MpServer', x=-189.50, y=67.00, z=-750.50], EntityItem['item.tile.mushroom'/13599, l='MpServer', x=-208.48, y=32.00, z=-771.32], EntityItem['item.tile.mushroom'/13600, l='MpServer', x=-204.90, y=29.00, z=-765.49], EntityItem['item.tile.mushroom'/13601, l='MpServer', x=-201.34, y=28.00, z=-766.13], EntityBat['Bat'/13732, l='MpServer', x=-204.26, y=47.22, z=-773.50], EntityBat['Bat'/13762, l='MpServer', x=-204.01, y=19.56, z=-713.28], EntityBat['Bat'/13763, l='MpServer', x=-200.00, y=22.86, z=-738.75], EntityZombie['Zombie'/13773, l='MpServer', x=-207.50, y=20.00, z=-760.50], EntitySquid['Squid'/13805, l='MpServer', x=-214.51, y=62.05, z=-704.34], EntitySquid['Squid'/13806, l='MpServer', x=-211.40, y=61.00, z=-707.69], EntityBat['Bat'/13936, l='MpServer', x=-123.08, y=17.01, z=-671.62], EntityBat['Bat'/13937, l='MpServer', x=-129.79, y=16.09, z=-673.12], EntityBat['Bat'/13971, l='MpServer', x=-133.66, y=61.10, z=-682.25], EntityBat['Bat'/13972, l='MpServer', x=-126.07, y=60.00, z=-680.65], EntityZombie['Zombie'/13982, l='MpServer', x=-143.50, y=26.00, z=-665.50], EntitySkeleton['Skeleton'/13995, l='MpServer', x=-216.50, y=23.00, z=-717.50], EntitySkeleton['Skeleton'/13996, l='MpServer', x=-211.79, y=24.00, z=-711.50], EntityZombie['Zombie'/13997, l='MpServer', x=-217.50, y=23.00, z=-718.50], EntityZombie['Zombie'/13998, l='MpServer', x=-215.50, y=23.00, z=-718.50], EntitySkeleton['Skeleton'/14001, l='MpServer', x=-137.50, y=36.00, z=-691.50], EntityBat['Bat'/14003, l='MpServer', x=-201.25, y=30.00, z=-735.48], EntityEnderman['Enderman'/14061, l='MpServer', x=-224.50, y=55.00, z=-791.50], EntityBat['Bat'/14069, l='MpServer', x=-149.20, y=27.27, z=-688.67], EntityZombie['Zombie'/14081, l='MpServer', x=-202.50, y=26.00, z=-744.50], EntityZombie['Zombie'/14082, l='MpServer', x=-202.50, y=26.00, z=-743.50], EntityZombie['Zombie'/14178, l='MpServer', x=-156.50, y=25.00, z=-658.50], EntitySpider['Spider'/14180, l='MpServer', x=-146.99, y=25.00, z=-660.95], EntityBat['Bat'/14188, l='MpServer', x=-178.77, y=15.64, z=-788.20], EntityBat['Bat'/14189, l='MpServer', x=-178.30, y=15.00, z=-789.48], EntitySkeleton['Skeleton'/14228, l='MpServer', x=-124.50, y=15.00, z=-677.50], EntitySkeleton['Skeleton'/14229, l='MpServer', x=-127.50, y=15.00, z=-675.50], EntitySkeleton['Skeleton'/14230, l='MpServer', x=-121.71, y=16.00, z=-676.49], EntityCreeper['Creeper'/14231, l='MpServer', x=-126.50, y=15.00, z=-680.50], EntityBat['Bat'/14236, l='MpServer', x=-187.39, y=56.10, z=-753.90], EntityBat['Bat'/14238, l='MpServer', x=-201.25, y=53.76, z=-750.14], EntityCreeper['Creeper'/14245, l='MpServer', x=-197.50, y=58.00, z=-776.50], EntityZombie['Zombie'/14249, l='MpServer', x=-203.50, y=29.00, z=-752.50], EntityBat['Bat'/14259, l='MpServer', x=-182.06, y=25.36, z=-731.31], EntityBat['Bat'/14260, l='MpServer', x=-204.94, y=26.07, z=-722.56], EntityBat['Bat'/14262, l='MpServer', x=-198.59, y=24.10, z=-728.43], EntityBat['Bat'/14263, l='MpServer', x=-260.72, y=58.59, z=-740.63]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 314120200 bytes (299 MB) / 973078528 bytes (928 MB) up to 7247757312 bytes (6912 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6912m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version         | Source                           | Signature |
	|:------ |:-------------- |:--------------- |:-------------------------------- |:--------- |
	| LCHIJA | minecraft      | 1.12.2          | minecraft.jar                    | None      |
	| LCHIJA | mcp            | 9.42            | minecraft.jar                    | None      |
	| LCHIJA | FML            | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar    | None      |
	| LCHIJA | forge          | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar    | None      |
	| LCHIJA | baubles        | 1.5.2           | Baubles-1.12-1.5.2.jar           | None      |
	| LCHIJA | patchouli      | 1.0-20          | Patchouli-1.0-20.jar             | None      |
	| LCHIJA | bewitchment    | 0.21.10         | bewitchment-1.12.2-0.0.21.10.jar | None      |
	| LCHIJA | gbook_snapshot | 2.9.1.s5        | Guidebook-1.12.2-2.9.1.s5.jar    | None      |
	| LCHIJA | som            | 1.2.10-mc1.12.2 | MK1.12.2-1.2.10.jar              | None      |
	| LCHIJA | gbook          | 2.9.2           | Guidebook-1.12.2-2.9.2.jar       | None      |

	Loaded coremods (and transformers): 
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.10.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: forge-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz`

**Comment by MoriyaShiine** [comment]
They're using the log block but are removing the axis property for some reason. This is on their end, they should be making logs correctly.
