### ISSUE TITLE
Pact:Ignition is bugged

### ISSUE THREAD

**Issue by Toritos01** [Um-Mitternacht/Bewitchment#542]
### Expected Behavior
In the book of shadows, it is stated that ores will be auto-smelted upon being mined when a player gets the Ignition demon pact.

### Actual Behavior
The auto-smelt effect applies not only to ores, but to other types of blocks, with any tool (breaking trees with an axe gives you charcoal).
Additionally, certain blocks will drop a huge amount of items when broken (breaking cobblestone or coal ore drops 48 stone or coal respectively). This seems game breaking as you could essentially have infinite stone, and I'm not yet sure what other items it applies to.

### Steps to Reproduce
Summon one of the demons (I used Lord Baphomet), and form a pact with them. Right click the demon (while having xp levels) until you get pact of ignition. Try breaking a cobblestone, coal, or log block. Check how many items you get

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 0.0.21.10
Forge 1.12.2 - 14.23.5.2847
Patchouli 1.0-20
Baubles 1.12-1.15.2

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/13680493/78089512-ac85e980-7395-11ea-9e6d-7c10de31f44f.png)
Charcoal is seen as the wood block is broken.

![image](https://user-images.githubusercontent.com/13680493/78089595-ed7dfe00-7395-11ea-83b6-7c66985b3213.png)
If you look closely, you can see multiple stone blocks coming out of one broken cobblestone block.

### Logs, in the event of a crash
No crash

**Comment by Sunconure11** [comment]
I’ll look into this.
