### ISSUE TITLE
Bewitchment mobs don't spawn in other modded nether biomes from BOP or NetherEX

### ISSUE THREAD

**Issue by BugmanBugman** [Um-Mitternacht/Bewitchment#543]
### Expected Behavior
For the nether mobs in BW to spawn in other modded biomes

### Actual Behavior
They only spawn in the vanilla Hell biome

### Steps to Reproduce
1. load up BW with BOP or NEX
2. search for biomes from either mod
3. take notice of how nothing spawns there

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 0.0.21.10
Forge 1.12.2 - 14.23.5.2847
Patchouli 1.0-20
Baubles 1.12-1.15.2

**Comment by Sunconure11** [comment]
Strange. They use the biomedict for the nether so they should be spawning there.

Only two spawn there though, the feuerwurm and the hellhound. A few more will be added in the next 1.12.2 update.

**Comment by anqingchen** [comment]
Do you have in control (mod) installed?

**Comment by Unhook** [comment]
https://github.com/LogicTechCorp/NetherEx/issues/211

**Comment by LogicTechCorp** [comment]
I believe this issue is caused by adding spawns using EntityEntryBuilder. It adds the spawns before any mod has had the chance to add their biomes to the biome dictionary. To fix this you'd have to add the entity spawns during post init.

**Comment by Sunconure11** [comment]
@LogicTechCorp Any ideas on how to do that? I’m going over old issues and cleaning out the repo a bit.

**Comment by LogicTechCorp** [comment]
The EntityRegistry class has an addSpawn method which can be used in place of the EntityEntryBuilder's spawn method. Calling it during post init will fix the issue. It can be called during init as well, but will require for BOP and NetherEx to be loaded first.
