### ISSUE TITLE
Vanilla Fix and Bewitchment . Bug

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Um-Mitternacht/Bewitchment#544]
There seems to be an issue with Vanilla Fix and Bewitchment. I notified the author of VF, and he/she pointed at you. Hopefully, it will be solved easily! :)

Thank you in advanced for your response!

Here is a link to his/her comment:
 
- https://github.com/DimensionalDevelopment/VanillaFix/issues/245#issuecomment-607582139

Here is a link to the thread I created:

- https://github.com/DimensionalDevelopment/VanillaFix/issues/245#event-3190309464

**Comment by ZombieHDGaming** [comment]
Ignore this, I just looked and saw you guys updated after I sent my comment XD hopefully you guys push an update so people will chill out :P
