### ISSUE TITLE
Bewitchment silver ore still spawns after being disabled

### ISSUE THREAD

**Issue by Unhook** [Um-Mitternacht/Bewitchment#545]
### Expected Behavior
Disabling silver ore in the config disables silver ore from spawning.

### Actual Behavior
Silver ore still spawns after being disabled in the config.

### Steps to Reproduce
Disabling silver ore and starting up a world.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 0.0.21.10
Forge 1.12.2 - 14.23.5.2847
Patchouli 1.0-20
Baubles 1.12-1.15.2

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/58952619/78360586-542e3200-75b7-11ea-9cef-198722d31434.png)

**Comment by anqingchen** [comment]
How exactly are you disabling silver ores?

**Comment by Unhook** [comment]
![image](https://user-images.githubusercontent.com/58952619/79008701-3a17c500-7b5e-11ea-8975-68a9666525e4.png)

**Comment by anqingchen** [comment]
That **should** work, at least it works for me. Maybe you are on an older version of config file? Have you tried deleting the config, starting up your game to generate a fresh one and set those values (while the game is closed)

**Comment by Sunconure11** [comment]
Is this still a problem?
