### ISSUE TITLE
Initializing game crash

### ISSUE THREAD

**Issue by saltedcoffii** [Um-Mitternacht/Bewitchment#546]
[crash-2020-04-05_22.17.26-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4435582/crash-2020-04-05_22.17.26-client.txt)

If crash reports need to be submitted in another way, I apologise.

**Comment by Sunconure11** [comment]
I think this is IC’s fault.

**Comment by saltedcoffii** [comment]
What's the IC mod, and when I downgraded Bewitchment to 0.0.21.10, it worked fine.

**Comment by Sunconure11** [comment]
It's blaming industrialcraft. Or something that uses it's API.
