### ISSUE TITLE
Random crash when logout from server

### ISSUE THREAD

**Issue by SAIANBY** [Um-Mitternacht/Bewitchment#551]
### Expected Behavior
No crash

### Actual Behavior
Random crash when logout from server

### Steps to Reproduce
1. Logout from my own minecraft server

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
minecraft 1.12.2
bewitchment-1.12.2-0.0.21.11.jar
Forge version 1.12.2-14.23.5.2847
Patchouli-1.0-20.jar
Baubles-1.12-1.5.2.jar

### Logs, in the event of a crash
[crash-2020-04-12_03.03.41-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4465531/crash-2020-04-12_03.03.41-client.txt)

**Comment by Sunconure11** [comment]
Pastebin please.
