### ISSUE TITLE
Crash when trying to load mods

### ISSUE THREAD

**Issue by ninetailsjr101** [Um-Mitternacht/Bewitchment#552]
### Expected Behavior
load and start up

### Actual Behavior
crashes when about to start step 2 / 7

 

### Logs, in the event of a crash
[crash-2020-04-14_22.54.53-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4479053/crash-2020-04-14_22.54.53-client.txt)

**Comment by Sunconure11** [comment]
Nothing in this states it’s us.

**Comment by ninetailsjr101** [comment]
idk what is causing it then, because it only crashes when bewitchment is added into it

**Comment by ninetailsjr101** [comment]
> Nothing in this states it’s us.

idk what is causing it then, because it only crashes when bewitchment is added into it
