### ISSUE TITLE
Fillled Goblet

### ISSUE THREAD

**Issue by HeavyDeception** [Um-Mitternacht/Bewitchment#553]
### Expected Behavior
Filled Goblet is created by filling a Cauldron with Honey, then throwing in 3 Redstone Dust, a Ghast Tear, a Cloudy Oil, and finally the Empty Goblet. After a few seconds, the Filled Goblet will be spat out of the Cauldron
*Copied from the wiki Honey was removed so used water.*

### Actual Behavior
made a red liquid but did not give goblet

### Steps to Reproduce
Did it 3 times.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2 minecraft. Bewichment. 1.12.2-0.0.21.10, forge 14.23.5.2847, Patchouli 1.0-20, Baubles 1.12-1.5.2

### Screenshots encouraged
woud be of a filled witches' cauldron

### Logs, in the event of a crash
no crash

**Comment by anqingchen** [comment]
Please reference the in game guide book instead of the wiki. The wiki is severely out of date.

**Comment by alexgurrola** [comment]
@anqingchen I used the in-game book and nothing works.
