### ISSUE TITLE
Cannot Start w/ Bewitchment

### ISSUE THREAD

**Issue by TassieRebel** [Um-Mitternacht/Bewitchment#554]
Basically, issue starting forge 1.12.2-14.23.5.2768 with Bewitchment 1.12.2-0.0.21.11, Baubles 1.5.2 and Patchouli 1.0-20. Don't know which mod is incorrect, but thought I should put it here, as bewitchment is the core mod. Crash popup says: Error: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;  
Already removed all other mods excluding these three to check for incompatibilities, but no luck. 
Crash log attached
[crash-2020-04-16_13.45.58-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4484800/crash-2020-04-16_13.45.58-client.txt)

**Comment by Sunconure11** [comment]
Downgrade to the previous build. 0.21.11 was created for a few individuals who kept having some niche issues.
