### ISSUE TITLE
Voodoo Poppet doesn't work correctly

### ISSUE THREAD

**Issue by Margatroidd** [Um-Mitternacht/Bewitchment#555]
### Expected Behavior
Voodoo poppet damages the victim with bone needles regardless of the victim's inventory

### Actual Behavior
It only deals damage if the victim has bone needles in their inventory

### Steps to Reproduce
1. Make a voodoo poppet
2. Link it to someone with a taglock
3. Right click with bone needles

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 14.23.5.2847
Bewitchment: 0.0.21.11
Patchouli: 1.0-20
Baubles: 1.5.2

**Comment by Sunconure11** [comment]
Is this still a thing?

**Comment by Margatroidd** [comment]
I'd have to try it out but I'm currently unable. Will it be ok if I confirm it in a few days?

**Comment by Sunconure11** [comment]
Yes, that's fine.

**Comment by Margatroidd** [comment]
I've tried it and it works fine, thanks
