### ISSUE TITLE
Altar range is currently incorrect.

### ISSUE THREAD

**Issue by Krakatoah** [Um-Mitternacht/Bewitchment#556]
### Expected Behavior

Altars are supposed to draw in ME from plants in a 32 square radius and distribute it in a 16 square radius to anything that requires ME to function.

### Actual Behavior

The altar's range is quite a ways off, the range on my version is 8 blocks to the south and east, roughly 22 blocks to the north and west.

### Steps to Reproduce

Place down a functioning altar, then use a sapling or other plant to check if the altar is recieving any ME from it, repeat until the full range is found.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2
Bewitchment: 0.21.10
Forge: 8.0.99.99
Patchouli: 1.0-20
Baubles: 1.5.2

### Screenshots encouraged

https://i.imgur.com/vzTkp29.jpg
(The yellow/blue wool blocks represent the maximum range on the altars as far as I am aware, the chests are used to force a block update.)

### Logs, in the event of a crash

This doesn't cause any crashes as far as I know.

**Comment by ghost** [comment]
Same issue here, replicated in a single player flat world.

**Comment by MayliSong** [comment]
Measured as best I can with tall flowers for gathering and spinning wheels for distributing. Grey/white is gathering range, yellow/red  is distributing range, the arrow points north of the world. Version 0.21.12 of Bewitchment
http://prntscr.com/s9x3h5

**Comment by Krakatoah** [comment]
I've done another measurement adding in the Y axis along with the X and Z axis for both gathering (lime & green wool) and distributing (cyan and blue wool), this was the result given as I was looking northward: https://i.imgur.com/sxxKz06.jpg

Seems like the range for distributing ME is 24 blocks out from the altar in all directions, 8 blocks larger than what the book says but at least it's centered correctly. :D

This is on a different version of bewitchment, (0.21.12) all other mods are on the same version as the original comment.

**Comment by pterolatypus** [comment]
I expect that [this](https://github.com/Um-Mitternacht/Bewitchment/blob/e430595fe1086ba03fc1c6d61c9c8441e7a59411/src/main/java/com/bewitchment/common/block/tile/entity/TileEntityWitchesAltar.java#L133) offset should be 16 instead of 8.
