### ISSUE TITLE
Light blue screen crash in MC Eternal?

### ISSUE THREAD

**Issue by oddynuff59** [Um-Mitternacht/Bewitchment#557]
### Expected Behavior
I was just trying to change the biome around with the biome staff, when it gave me a crash from Bewitchment, and I don't know why.

### Actual Behavior
        I wasn't doing anything in relation to Bewitchment at the time, and I was the only one on the server. I was using the biome staff (from the biome staff mod) and started changing the biome to Enchanted Forest from Twilight Forest, and I think I hit a tall grass block and I got a light blue screen and crashed. This wasn't the first time this light blue screen crash happened, the owner of the server said something about the statues from Bewitchment causing it, so we got rid of all of them. I got the owner to restart it since then but I don't know if anyone has been on since. Every time I log on now I load in for a split second, get a light blue screen and then crash back to title screen, and it says mod causing the potential problem was Bewitchment.
        Sorry if this was too much!

### Steps to Reproduce
Just log into the server, and load in for a split second, not enough for me to even move and I get a light blue screen and crash to title screen.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Playing on MC Eternal,
Bewitchment is 1.12.2
Version: 1.3.5b
Minecraft Version: 1.12.
(modded) forge-14.23.5.2847

### Screenshots encouraged
![bewitchmentcrashscreen]  https://user-images.githubusercontent.com/64086733/79876103-9974a100-83b8-11ea-84ea-d422e14ac00e.png

### Logs, in the event of a crash

https://paste.dimdev.org/kejalosanu.mccrash

Thanks for looking this over!

**Comment by oddynuff59** [comment]
I went on with an alt, and everything was fine when I logged in (for the first time) in spawn, and warped to the house. Everything was fine until I was walking around outside the base and I looked at a tall invisible block of a Scorned Brick Baphomet Statue. The second I looked at it I crashed, and it was completely invisible.

**Comment by Sunconure11** [comment]
When you can, can you post the crash report on pastebin? I’m getting connection issues with the site you have it on.

**Comment by Sunconure11** [comment]
MC Eternal is using an outdated build. Get them to update if they haven't already.
