### ISSUE TITLE
Thermal Expansion/Foundation integration

### ISSUE THREAD

**Issue by melodious1963** [Um-Mitternacht/Bewitchment#558]
Suggestion

Integration with Thermal Expansion/Foundation.
Specifically, making the potions   compatible with the potion liquids from TF etc.

**Comment by Sunconure11** [comment]
I haven't played with that mod in a long time. You would need to post here examples of this in action.

**Comment by melodious1963** [comment]
Well, the Thermal Foundation mod has a potion liquid, which can assume all vanilla potions effects and all implemented by the mod itself. It can be created by putting a potion bottle in a fluid transposer (transfers liquids to other containers). This potion can then be stored in a tank for later use, or put in a hypoinfuser (from Thermal Innovation) which can apply the potion to the player automatically or by sneak right clicking the item.

**Comment by Sunconure11** [comment]
After some discussion with other devs, it has been deemed impossible to pull off. Sorry.
