### ISSUE TITLE
Textures: "bounty board"

### ISSUE THREAD

**Issue by zabi94** [Um-Mitternacht/Bewitchment#56]
Refer to our discord server for general instructions on style and such.
Icons are added as they are needed

All these textures are needed urgently:
- [x] Blood reservoire (see [here](https://github.com/Um-Mitternacht/Bewitchment/wiki/Vampires#level-4))
- [x] Subjugate ability icon
- [x] Hypnotize ability icon
- [x] Call casket ability icon

All these textures will be probably needed sometimes in the future:

- [ ] Paper message

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Bewitchment/issues/99
