### ISSUE TITLE
[Suggestion] Display required altar power for cauldron recipes

### ISSUE THREAD

**Issue by melodious1963** [Um-Mitternacht/Bewitchment#561]
Suggestion - the ability to see how much altar power a cauldron recipe is going to cost in the books, jei and the cauldron itself (maybe with an item)?
And if a cauldron recipe is performed without sufficient power, the ability to gain the required power and receive the item anyway, this could also be done with an extra item

**Comment by Sunconure11** [comment]
There might be something like this planned for 1.16 or so.
