### ISSUE TITLE
Wrong links in build.gradle

### ISSUE THREAD

**Issue by Vitoldik** [Um-Mitternacht/Bewitchment#563]
Could not get resource 'https://minecraft.curseforge.com/api/maven/net/ilexiconn/llibrary/1.7.9-1.12.2/llibrary-1.7.9-1.12.2.pom'.
> Could not GET 'https://minecraft.curseforge.com/api/maven/net/ilexiconn/llibrary/1.7.9-1.12.2/llibrary-1.7.9-1.12.2.pom'. Received status code 503 from server: Service Temporarily Unavailable

And so with every library

**Comment by Sunconure11** [comment]
Looks like an old connection issue.
