### ISSUE TITLE
Conflict with other mods

### ISSUE THREAD

**Issue by ghost** [Um-Mitternacht/Bewitchment#568]
Hello, I am playing modded Minecraft and I recently added Bewitchment but it crashes on loading. I don't know what part of it conflicts but here is the crash report! Danke schön mein Freund!

Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.5.2856
Bewitchment version: 1.12.2-0.0.21.12
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

[crash-2020-05-01_23.46.59-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4566712/crash-2020-05-01_23.46.59-client.txt)

**Comment by sixtymillionsqrd** [comment]
I get the same error!

https://paste.dimdev.org/oyibutuzic.mccrash

**Comment by Sunconure11** [comment]
Update all mods using mixin

**Comment by jtgibson01** [comment]
For others having this issue, I found that the following mods in my carefully-tuned setup were also using "mix-ins":

* ChickenBones' Forge Multipart CBE
* JustEnoughIDs
* LibrarianLib
* MovingWorld
* Phosphor
* VanillaFix

(There are likely other mods that are using them -- but I'm not using those mods, of course. ;-))

Try updating **VanillaFix** and **JustEnoughIDs**, which are generally important mods to keep up to date as much as possible.  I also updated JustEnoughItems (technically unrelated to JEIDs) as a matter of best practice.  **This worked for me!**

I did not have to update LibrarianLib to 4.20 (Dec 2019), but it's going in my next boot.

If this doesn't help you (perhaps you have a mod with mixins that I don't), unfortunately, many 1.12.2 mods are reaching end of life and will most likely not see updates; you may have to revert to an older Bewitchment version.
