### ISSUE TITLE
Distillery not distilling

### ISSUE THREAD

**Issue by Diamond200512** [Um-Mitternacht/Bewitchment#570]
### Expected Behavior
put ingredients in the distillery and get the product

### Actual Behavior
ingredients go activate the distillery but no product is ever made and blaze powder is consumed

### Steps to Reproduce
1: get a distillery
2:put ingredients in distillery
3:put blaze powder in distillery
4:powder consumed and product is never made
### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft:1.12.2
Forge:14.23.5.2847
Bewitchment:0.0.21.11
Patchouli:1.0-20
Baubles:1.5.2
### Screenshots encouraged

![Screen Shot 2020-05-08 at 8 08 35 AM](https://user-images.githubusercontent.com/54332468/81408905-b7097080-9103-11ea-9461-f5a6cc899866.png)

**Comment by Ayrion** [comment]
You do have altar power right?

**Comment by Diamond200512** [comment]
I have like 1300 altar power

**Comment by Diamond200512** [comment]
that made me realize I needed to put it closer

**Comment by Diamond200512** [comment]
it worked in end once so I thought it could work anywhere

**Comment by ubergarm** [comment]
Thanks for opening this issue, my distillery wasn't working but consuming blaze so I just assumed it was a bug. Turns out I need an Altar! I'll read the book before just going through the JEI next time! xD  Thanks!
