### ISSUE TITLE
Can't dismount brooms in the End.

### ISSUE THREAD

**Issue by gavros963** [Um-Mitternacht/Bewitchment#571]
### Expected Behavior
Lshift dismounts the broom

### Actual Behavior
In the end, Lshift does nothing on a broom, you have to fully exit the end on the broom to to dismount.

### Steps to Reproduce
Ride a broom in the End, try to dismount.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC version 1.12.2, Bewitchment ver 1.12.2-0.0.21.12, Patchouli ver 1.0-20, Baubles ver 1.12-1.5.2

**Comment by gavros963** [comment]
![Screenshot from 2020-05-09 02-42-37](https://user-images.githubusercontent.com/60665550/81467563-0a7ccc80-919f-11ea-84fd-85aa11fb26c7.png)
Figured just in case, I'll post my full mod list just in case it's a conflict caused by another mod.
Doubt it, but figured might as well.
I'm pretty sure none of them mess with mounts in the end though...

**Comment by Sunconure11** [comment]
Brooms in general are known to be bugged. Multiple attempts were made at fixing them. If you know someone who can actually fix them, feel free to direct them here.
