### ISSUE TITLE
Perpetual Ice Issues

### ISSUE THREAD

**Issue by Azuriuz** [Um-Mitternacht/Bewitchment#578]
### Expected Behavior
Perpetual Ice should work with other blocks, vanilla (and modded if possible)

### Actual Behavior
Perpetual Ice slabs have a top/bottom block culling issue. Perpetual Ice slabs and stairs do not cull when placed beside eachother. Perpetual Ice does not cull sides when near vanilla ice, or modded ice (that I've tested).

### Steps to Reproduce
Slabs Culling: top slab will cull above blocks. Bottom slabs cull the blocks underneath which means people can likely find a way to abuse this for x-ray hacks. (This is the priority bug here, the rest is cosmetic.)
Slabs and Stairs not Culling: Just place 2 Perpetual Ice slabs or stairs beside eachother, images below.
Ice Block not Culling: Place Perpetual Ice Block beside a vanilla ice block, this also happens with modded (tested with Light the Night's Infernal Ice Block).

The bottom 2 bugs may be intended, but I find it odd when Perpetual Ice fence culls just fine with itself, as does the block itself; but stair and slab do not. It's also odd that you can't place Perpetual Ice next to real ice, which kinda makes sense, except it also won't place next to other infinately frozen ice blocks from mods (at least the one I tested). 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
minecraft-1.12.2, bewitchment-1.12.2-0.0.21.12, forge-14.23.5.2847, Patchouli-1.0-20, and Baubles-1.12-1.5.2

### Screenshots encouraged
Double Slab Culling - [https://ibb.co/W2QPNQ7](url)
![2020-05-17_23 59 29](https://user-images.githubusercontent.com/50718369/82177311-0f303780-98a7-11ea-99c0-bfbfcd44fe69.png)
Slabs and Stairs not Culling - [https://ibb.co/Lgk3LNB](url)
![2020-05-17_23 59 54](https://user-images.githubusercontent.com/50718369/82177313-0f303780-98a7-11ea-9965-60de567da79f.png)
Perpetual Ice not Culling with other Ice - [https://ibb.co/jZFmLyF](url)
![2020-05-17_23 59 22](https://user-images.githubusercontent.com/50718369/82177310-0e97a100-98a7-11ea-8b6c-176be6024b4a.png)

### Logs, in the event of a crash
no crash

I think people will want to use the Perpetual Ice in alot of builds, but these cosmetic issues might discourage them, as you have to come up with creative ways to use the blocks. I hope this might be fixed in a future update!

**Comment by Sunconure11** [comment]
Transparent blocks in general are kind of weird, but I have an idea.

**Comment by Azuriuz** [comment]
Awesome! I hope one day this can be fixed, as these are fantastic building blocks that I wish I could use more!

**Comment by Sunconure11** [comment]
I can't seem to get it to cull with normal ice, but I fixed a lot of culling issues it had otherwise, including x-raying. I'd advise checking it out yourself.
