### ISSUE TITLE
Crash while loading mods

### ISSUE THREAD

**Issue by Quadruplay** [Um-Mitternacht/Bewitchment#582]
### Expected Behavior
Minecraft works

### Actual Behavior
Minecraft crashes

### Steps to Reproduce
I added bewitchment to my mods and the game stopped working

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
![Zrzut ekranu (105)](https://user-images.githubusercontent.com/61585172/82729902-eb804d80-9cfb-11ea-9a11-554d06038b19.png)
![Zrzut ekranu (106)](https://user-images.githubusercontent.com/61585172/82729904-ecb17a80-9cfb-11ea-9c89-1aa89727b85a.png)
![Zrzut ekranu (104)](https://user-images.githubusercontent.com/61585172/82729905-ed4a1100-9cfb-11ea-936e-80890eb83662.png)

### Logs, in the event of a crash
[crash-2020-05-23_13.44.30-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4671698/crash-2020-05-23_13.44.30-client.txt)

**Comment by Sunconure11** [comment]
Update forge + all mods that use mixin

**Comment by Quadruplay** [comment]
how do I know which mods use mixin

**Comment by Sunconure11** [comment]
Just update all of them, as well as forge. Closing.
