### ISSUE TITLE
Brooms Fly forward slowly, Sometimes crash the game when broken and drop a duplicate broom when broken

### ISSUE THREAD

**Issue by 123mind123** [Um-Mitternacht/Bewitchment#583]
### Expected Behavior
For Brooms to fly forward at a fast speed, drop only 1 broom when broken and not crash the game.

### Actual Behavior
Brooms fly fast when trying to strafe left or right making the broom movement look a bit weird. While when moving forward or back it is slower than sneaking. 

When broken two brooms are dropped and sometimes the game crashes.

### Steps to Reproduce
Slow broom movement:
Create a broom.
Place it on the ground.
Get on the broom.
press space to levitate to a high point.
Press forwards and move very slowly.

2 brooms dropping and crash.
Place the broom.
Left click to break the broom.

(Crash does not always happen. Still testing to see when might be causing it.)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft 1.12.2
bewitchment-1.12.2-0.0.21.12.jar
forge 1.12.2-14.23.5.2847

### Screenshots encouraged
![Bewitch01](https://user-images.githubusercontent.com/5164825/82754594-bc361300-9dc5-11ea-9048-34ddcfeb937a.jpg)
![Bewitch02](https://user-images.githubusercontent.com/5164825/82754597-bd674000-9dc5-11ea-9f95-95f4efba75dc.jpg)

### Logs, in the event of a crash
A crash log did not occur on the event of a crash. It appears that what ever happens causes the whole back end of the engine to freeze up.

Thanks in advance.

**Comment by Sunconure11** [comment]
Brooms are known to be bugged. If you know someone who can fix them, please direct them here.
