### ISSUE TITLE
Bewitchment breaks Malisisdoors' big doors

### ISSUE THREAD

**Issue by SoldierKucha** [Um-Mitternacht/Bewitchment#584]
### Expected Behavior
For big doors to work properly

### Actual Behavior
When big doors arent in loaded chunks/when I rejoin the world big doors core block gets replaced with lower part of bewitchment's dragon blood door

### Steps to Reproduce
Place a Malisisdoors' big doors and exit/enter the world

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 0.0.21.12
Forge 1.12.2 - 14.23.5.2847
Patchouli 1.0-20
Baubles 1.12-1.5.2

### Screenshots encouraged
https://imgur.com/a/XvyUzOy

### Logs, in the event of a crash
https://pastebin.com/syg7UwsF

**Comment by SoldierKucha** [comment]
Turns out it also transforms Malisisdoors' Door Factory into Embittered Brick Slabs
https://imgur.com/a/OPYhWqN

**Comment by Sunconure11** [comment]
That link is broken. Please post a proper one.

**Comment by SoldierKucha** [comment]
Should work now

**Comment by Sunconure11** [comment]
I'm not sure why this would be happening TBH

**Comment by SoldierKucha** [comment]
Neither do I. VanillaFix just pointed in Bewitchment direction and I did the report.

**Comment by Sunconure11** [comment]
Is this still a problem?

**Comment by Sunconure11** [comment]
No response.
