### ISSUE TITLE
Incompability with Ice and Fire & Tinkers

### ISSUE THREAD

**Issue by Esseit** [Um-Mitternacht/Bewitchment#585]
### Expected Behavior
Launch Normally

### Actual Behavior
Immediate crash during loading 

### Steps to Reproduce
Put tinkers construct 2.12.0 and or ice and fire 1.9.1 in to launch with bewitchment 0.0.21.12

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Bewitchment 0.0.21.12, latest on all others as of 6/9/2020 

### Logs, in the event of a crash
no logs formed, tested through trial and error

### If this is a question, developer commentary, or a suggestion, ignore this template

EDIT:Got a report finally, tried it with a pack ive been building and got a little further in the loading process this time. 
https://docs.google.com/document/d/1CTq429ocIUO6Iy_1QByWECR7ch2UO0nso0qWjo0bSE4/edit?usp=sharing

**Comment by Sunconure11** [comment]
Weird, because I run this alongside ice and fire fine. And tinkers in another pack as well. I'd suggest updating your forge to the latest build possible. See if you can generate any kind of crash.

**Comment by Esseit** [comment]
> Weird, because I run this alongside ice and fire fine. And tinkers in another pack as well. I'd suggest updating your forge to the latest build possible. See if you can generate any kind of crash.

I've updated to the latest build of forge but its still instantly crashing with no log. As ive browsed through here ive seen other people using tinkers and ice and fire as well so im very confused as well
