### ISSUE TITLE
Incompatible with EigenCraft Unofficial Patch (MUP)

### ISSUE THREAD

**Issue by DarianLStephens** [Um-Mitternacht/Bewitchment#586]
### Expected Behavior
That I can launch the game hassle-free with both Bewitchment and MUP.

### Actual Behavior
The game crashes if Bewitchment is enabled.
No crashes when all dependencies are enabled, Bewitchment is what breaks it.
I have also attempted to disable everything in MUP's config, with no change in crash.

### Steps to Reproduce
Install Bewitchment and MUP, then attempt to launch the game.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
The latest currently available on Curseforge, at the time of writing this.
Specifically:
Baubles-1.12-1.5.2
bewitchment-1.12.2-0.0.21.12
Patchouli-1.0-20

### Logs, in the event of a crash
https://paste.ee/p/ErZ2E

**Comment by DarianLStephens** [comment]
I was able to get the game to work by changing the 'required' value in 'mixins.bewitchment.json' within the .jar from 'true' to 'false'.
So far, I've been able to use potions and such normally, including splash ones that affect blocks.
No clue if anything's broken, but nothing appears to be, and I can use this alongside MUP, which is a big win.

EDIT: Ah, wait, I think I see what's broken; the effects apply if it hits an entity nearby, but not to the blocks themselves.
Even though it would be a lot better if that worked, it's a small price to pay for having this essential bugfixing mod; regularly having invisible items, even from simply breaking blocks, was really getting on my nerves.

**Comment by Sunconure11** [comment]
So does this fully apply to us or the mod you’re using?

**Comment by DarianLStephens** [comment]
It has to do with conflicting mixins, I believe.
I would love to see the incompatibility fixed, because I have grown quite irritated at the 1.12 bug that causes many items to be invisible randomly, which this mod solves.

**Comment by Sunconure11** [comment]
Try and convince them to update to mixin 0.8, then. Only advise I can give, since I don't work on EigenCraft, nor have I heard of it until this issue was brought up.
