### ISSUE TITLE
Duplication bugs

### ISSUE THREAD

**Issue by SSKirillSS** [Um-Mitternacht/Bewitchment#587]
### Steps to Reproduce
See the videos:
1. https://www.youtube.com/watch?v=1UPvPK8CK9c (check distance from player to tile)
2. https://www.youtube.com/watch?v=Znb-cgc4nQs (tool poppet dupe)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC: 1.12.2
bewitchment-1.12.2-0.0.21.12
forge-1.12.2-14.23.5.2847
Patchouli-1.0-20
Baubles-1.12-1.5.2

**Comment by pingvikin** [comment]
Hey!
Also, if you put a broom on the ground and break it, two brooms will fall

**Comment by Sunconure11** [comment]
Won't be fixing the tool poppet dupe, but I can see about fixing the broom dupe.

**Comment by Sunconure11** [comment]
Unable to replicate the broom dupe.
