### ISSUE TITLE
Broom issues: Dismounting in Nether and Enerman ignorance

### ISSUE THREAD

**Issue by the-pieman** [Um-Mitternacht/Bewitchment#588]
### Expected Behavior
1. Press LShift to dismount a broom, getting off of it and proceeding on foot
2. Reticle being centered on an Enderman's head and torso angering it into attacking

### Actual Behavior
1. Pressing LShift after taking damage on the broom while in the Nether prevents one from dismounting indefinitely.
2. Enderman completely ignores you while on a broom

### Steps to Reproduce
1. Get hit by anything at all (even one point of suffocation damage) while riding a broom in the Nether. Only way to get off is to log out/disconnect from the game and log back in. Broom will be next to you on the ground, available for pickup
2. Get on a broom and aim the reticle directly at an Enderman

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 0.21.12
Forge: 14.23.5.2854
Patchouli: 1.0-20
Baubles: 1.5.2

### Screenshots encouraged
Logically cannot get a picture of a person trying to hit LShift to no effect, but I can post a pic of an Enderman being completely oblivious to direct "eye contact"
https://imgur.com/jPcW8yg

### Logs, in the event of a crash
No crashing, just bugs.

**Comment by the-pieman** [comment]
Update: The bug that prevents one from dismounting after taking damage also applies to the overworld, I just hadn't had it happen until now.

**Comment by Sunconure11** [comment]
Brooms are known for bugs. However, see #589.
