### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by israpps** [Um-Mitternacht/Bewitchment#591]
I had an error at minecraft launch
---- Minecraft Crash Report ----
// You're mean.

Time: 2020-06-17 11:54:54 ART
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1131)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 237535592 bytes (226 MB) / 481955840 bytes (459 MB) up to 3207856128 bytes (3059 MB)
  JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 92 mods loaded, 92 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                        | Version                 | Source                                        | Signature |
       |:----- |:------------------------- |:----------------------- |:--------------------------------------------- |:--------- |
       | L     | minecraft                 | 1.12.2                  | minecraft.jar                                 | None      |
       | L     | mcp                       | 9.42                    | minecraft.jar                                 | None      |
       | L     | FML                       | 8.0.99.99               | forge-1.12.2-14.23.5.2847.jar                 | None      |
       | L     | forge                     | 14.23.5.2847            | forge-1.12.2-14.23.5.2847.jar                 | None      |
       | L     | multihotbarcore           | 1.12.2-1.0.1-build-T22  | minecraft.jar                                 | None      |
       | L     | foamfixcore               | 7.7.4                   | minecraft.jar                                 | None      |
       | L     | deconstruction            | 3.0.4                   | [MC1.12.2]DeconTable-3.0.4.jar                | None      |
       | L     | anvilfix                  | 1.0.5                   | AnvilFix-1.12.2-1.0.5.jar                     | None      |
       | L     | jei                       | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                     | None      |
       | L     | appleskin                 | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                    | None      |
       | L     | quark                     | r1.6-178                | Quark-r1.6-178.jar                            | None      |
       | L     | autoreglib                | 1.3-32                  | AutoRegLib-1.3-32.jar                         | None      |
       | L     | backpacks16840            | 3.5.6                   | backpacks+1.12.2+-+3.5.6.jar                  | None      |
       | L     | baubles                   | 1.5.2                   | Baubles-1.12-1.5.2.jar                        | None      |
       | L     | baubleofundying           | 1.0.1                   | BaubleOfUndying-1.12-1.0.1.jar                | None      |
       | L     | betteradvancements        | 0.1.0.77                | BetterAdvancements-1.12.2-0.1.0.77.jar        | None      |
       | L     | patchouli                 | 1.0-20                  | Patchouli-1.0-20.jar                          | None      |
       | L     | bewitchment               | 0.21.12                 | bewitchment-1.12.2-0.0.21.12.jar              | None      |
       | L     | buildcraftlib             | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftcore            | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftbuilders        | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcrafttransport       | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftsilicon         | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftcompat          | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftenergy          | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftfactory         | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | buildcraftrobotics        | 7.99.24.6               | buildcraft-all-7.99.24.6.jar                  | None      |
       | L     | chunkpregenerator         | 2.1                     | Chunk+Pregenerator+V1.12-2.2.jar              | None      |
       | L     | clumps                    | 3.1.2                   | Clumps-3.1.2.jar                              | None      |
       | L     | codechickenlib            | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None      |
       | L     | controlling               | 3.0.7                   | Controlling-3.0.7.jar                         | None      |
       | L     | cookingforblockheads      | 6.5.0                   | CookingForBlockheads_1.12.2-6.5.0.jar         | None      |
       | L     | extendedrenderer          | v1.0                    | coroutil-1.12.1-1.2.37.jar                    | None      |
       | L     | coroutil                  | 1.12.1-1.2.37           | coroutil-1.12.1-1.2.37.jar                    | None      |
       | L     | configmod                 | v1.0                    | coroutil-1.12.1-1.2.37.jar                    | None      |
       | L     | cyclopscore               | 1.6.2                   | CyclopsCore-1.12.2-1.6.2.jar                  | None      |
       | L     | endercore                 | 1.12.2-0.5.73           | EnderCore-1.12.2-0.5.73.jar                   | None      |
       | L     | enderio                   | 5.1.55                  | EnderIO-base-1.12.2-5.1.55.jar                | None      |
       | L     | enderioconduits           | 5.1.55                  | ender io conduits.jar                         | None      |
       | L     | enderioendergy            | 5.1.55                  | ender io [endergy].jar                        | None      |
       | L     | enderiopowertools         | 5.1.55                  | ender io conduits.jar                         | None      |
       | L     | endercompass              | 1.0                     | EnderCompass-1.12.2-1.0.jar                   | None      |
       | L     | enderiointegrationtic     | 5.1.55                  | EnderIO-integration-tic-1.12.2-5.1.55.jar     | None      |
       | L     | enderiobase               | 5.1.55                  | EnderIO-base-1.12.2-5.1.55.jar                | None      |
       | L     | mantle                    | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                      | None      |
       | L     | tconstruct                | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar              | None      |
       | L     | enderiointegrationticlate | 5.1.55                  | EnderIO-integration-tic-1.12.2-5.1.55.jar     | None      |
       | L     | enderiomachines           | 5.1.55                  | EnderIO-machines-1.12.2-5.1.55.jar            | None      |
       | L     | enderiozoo                | 5.1.55                  | EnderIO-zoo-1.12.2-5.1.55.jar                 | None      |
       | L     | enderstorage              | 2.4.6.137               | EnderStorage-1.12.2-2.4.6.137-universal.jar   | None      |
       | L     | equaldragons              | 1.1                     | EqualDragons-1.1.jar                          | None      |
       | L     | evilcraft                 | 0.10.78                 | EvilCraft-1.12.2-0.10.78.jar                  | None      |
       | L     | evilcraftcompat           | 1.0.0                   | EvilCraft-1.12.2-0.10.78.jar                  | None      |
       | L     | minerva                   | 1.0.13                  | minerva-library-1.0.13.jar                    | None      |
       | L     | extraalchemy              | 0.5.3                   | extraalchemy-0.5.3.jar                        | None      |
       | L     | extrautils2               | 1.0                     | extrautils2-1.12-1.9.9.jar                    | None      |
       | L     | fantasticlib              | 1.12.2.034              | FantasticLib-1.12.2.034.jar                   | None      |
       | L     | fastbench                 | 1.7.3                   | FastWorkbench-1.12.2-1.7.3.jar                | None      |
       | L     | foamfix                   | 0.10.10-1.12.2          | foamfix-0.10.10-1.12.2.jar                    | None      |
       | L     | forgeendertech            | 1.12.2-4.5.1.0          | ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar  | None      |
       | L     | forgelin                  | 1.8.4                   | Forgelin-1.8.4.jar                            | None      |
       | L     | fpsreducer                | mc1.12.2-1.12.4         | FpsReducer-mc1.12.2-1.12.4.jar                | None      |
       | L     | overlord                  | 2.4.14                  | Overlord-1.12.2-2.4.14.jar                    | None      |
       | L     | guideapi                  | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                   | None      |
       | L     | gunpowderlib              | 1.12.2-1.0              | GunpowderLib-1.12.2-1.0.jar                   | None      |
       | L     | waila                     | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                   | None      |
       | L     | ichunutil                 | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                    | None      |
       | L     | infinitefluids            | 1.2.0                   | infinitefluids-1.11-1.2.0.jar                 | None      |
       | L     | ironchest                 | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar               | None      |
       | L     | lootcapacitortooltips     | 1.3                     | lootcapacitortooltips-1.3.jar                 | None      |
       | L     | mjrlegendslib             | 1.12.2-1.1.9            | MJRLegendsLib-1.12.2-1.1.9.jar                | None      |
       | L     | multihotbar               | 1.12.2-4.0.1-build-T116 | multihotbar-1.12.2-4.0.1-build-T116.jar       | None      |
       | L     | mutantbeasts              | 1.12.2-0.7.2            | MutantBeasts-1.12.2-0.7.2.jar                 | None      |
       | L     | naturescompass            | 1.5.1                   | NaturesCompass-1.12.2-1.5.1.jar               | None      |
       | L     | nbtmanipulator            | 1.12.2.003              | NBTManipulator-1.12.2.003.jar                 | None      |
       | L     | nei                       | 2.4.3                   | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | None      |
       | L     | reborncore                | 3.18.0                  | RebornCore-1.12.2-3.18.1.514-universal.jar    | None      |
       | L     | simplevoidworld           | 1.2.0.9                 | simple void world.jar                         | None      |
       | L     | simplefluidtanks          | 1.12.2-1.7.1.2          | simplefluidtanks-1.12.2-1.7.1.2.jar           | None      |
       | L     | storagenetwork            | 1.7.10                  | SimpleStorageNetwork-1.12.2-1.7.10.jar        | None      |
       | L     | lemonlib                  | 1.2.0                   | lemonlib-1.12.2-1.2.0.jar                     | None      |
       | L     | statues                   | 1.0.1                   | statues-rechiseled-1.12.2-1.0.1.jar           | None      |
       | L     | vampirism                 | 1.6.2                   | Vampirism-1.12.2-1.6.2.jar                    | None      |
       | L     | teamlapen-lib             | 1.6.2                   | Vampirism-1.12.2-1.6.2.jar                    | None      |
       | L     | vampirism_integrations    | vampirism_integrations  | VampirismIntegrations-1.12.2-1.3.0.jar        | None      |
       | L     | vanillafix                | 1.0.10-SNAPSHOT         | VanillaFix-1.0.10-99.jar                      | None      |
       | L     | villagerinventory         | 1.0.5                   | VillagerInventory-1.12-1.0.5.jar              | None      |
       | L     | wailaharvestability       | 1.1.12                  | WailaHarvestability-mc1.12-1.1.12.jar         | None      |
       | L     | xaerominimap              | 1.19.7                  | Xaeros_Minimap_1.19.7_Forge_1.12.jar          | None      |
       | L     | xaeroworldmap             | 1.5.4                   | XaerosWorldMap_1.5.4_Forge_1.12.jar           | None      |
       | L     | zombieawareness           | 1.12.1-1.11.16          | zombieawareness-1.12.1-1.11.16.jar            | None      |
       | L     | phosphor-lighting         | 1.12.2-0.2.6            | phosphor-1.12.2-0.2.6+build50-universal.jar   | None      |
  Loaded coremods (and transformers): CorePlugin (ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar)
                                        
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.12.jar)
                                        
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      FmlLoadingPlugin (multihotbarcore-1.12.2-1.0.1-build-T22.jar)
                                        com.rolandoislas.multihotbar.asm.transformer.Transformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      BCModPlugin (backpacks+1.12.2+-+3.5.6.jar)
                                        brad16840.core.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 3000'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4459, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Español (España)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz

**Comment by Sunconure11** [comment]
Update all of your mods.
