### ISSUE TITLE
Crash when loading up server with the latest version

### ISSUE THREAD

**Issue by BugmanBugman** [Um-Mitternacht/Bewitchment#595]
### Expected Behavior
to load up properly

### Actual Behavior
it crashed

### Steps to Reproduce
load up bewitchment on a server

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2 Forge 14.23.5.2854
Bewitchment 0.0.22.0
Patchouli 1.0-20
Bauble 1.12 1.5.2

### Logs, in the event of a crash
https://hastebin.com/equbijuzil.rb

**Comment by Sunconure11** [comment]
I can't make heads or tails of this.

**Comment by Sunconure11** [comment]
Can you provide more details on this crash? The log is not even complete.

**Comment by Sunconure11** [comment]
Something isn't being client-sided properly, but the log is too incomplete to tell what.

**Comment by BugmanBugman** [comment]
not sure what you mean, the rest of the log just showed how many mods i have on the server and my server pc specs. didnt give any more besides that.

**Comment by Sunconure11** [comment]
I was able to replicate it. The crash provides too little info to work on.

**Comment by Sunconure11** [comment]
Fixed in dev.
