### ISSUE TITLE
Owls cant fly

### ISSUE THREAD

**Issue by Bananbaronen** [Um-Mitternacht/Bewitchment#601]
### Expected Behavior
The owls is supposed to fly after me when tamed, allso wild owls to fly around

### Actual Behavior
Both tamed and wild owls just sit there. If i walk away from a tamed owl it just teleport after me. 

### Steps to Reproduce
I have no idea why this happens

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2 for all

**Comment by Sunconure11** [comment]
Owls fly fine for me.
