### ISSUE TITLE
Crash on launch with new update for 1.12.2

### ISSUE THREAD

**Issue by OuroborosBoy** [Um-Mitternacht/Bewitchment#602]
### Expected Behavior
The game should start when it is launched.

### Actual Behavior
It crashes. 

### Steps to Reproduce
Unknown. 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 1.12.2-0.0.22.4
Patchouli 1.0-20
Baubles 1.12-1.5.2

### Logs, in the event of a crash
https://pastebin.com/CaxDLZAT

**Comment by Sunconure11** [comment]
Either delete some mods or use JEID. You ran out of block IDs.
