### ISSUE TITLE
Getting a crash after updating to version 0.0.22.

### ISSUE THREAD

**Issue by rudugampola** [Um-Mitternacht/Bewitchment#603]
Version 0.0.21 was fine. But after updating to version 0.0.22 I m getting a crash when loading the mods in the beginning. I updated forge to the latest. Im using the java that is shipped with the twitch launcher, java version 51. Not sure if that's the culprit. 
Crash report attached: 

[crash-2020-06-23_17.47.58-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4828384/crash-2020-06-23_17.47.58-client.txt)

**Comment by Sunconure11** [comment]
You have a mod that is out of date with it's mixins.

**Comment by Sunconure11** [comment]
Try updating many of your mods.

**Comment by rudugampola** [comment]
Ooof there are too many mods. Some mods definitely need updating, but everything works find until I add bewitchment.

**Comment by Orinai** [comment]
Having the same issue, but all other mods are their latest edition. Is there a simple way to determine which mods are using the outdated mixins? Or will this be a case of "unload every mod one at a time until it works" as the only method?

**Comment by Sunconure11** [comment]
EnderIO, try updating that. I see it using mixin.

**Comment by rudugampola** [comment]
I tracked it down to VanillaFix. Incompat mixins

**Comment by Sunconure11** [comment]
That would do it. VanillaFix uses mixins.

**Comment by Shibva** [comment]
Found a simple solution... 
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

This mod will make 2 different versions of Mixin to work

I was having issue with mixin pulling up .7.11 but then plugged in this mod and it fixed it
