### ISSUE TITLE
Witches' Brews instantly failing

### ISSUE THREAD

**Issue by MaskedElephant** [Um-Mitternacht/Bewitchment#605]
### Expected Behavior
After throwing in a mandrake root, a cookie, and gunpowder, you take three bottles and pull the brew out

### Actual Behavior
After throwing in a mandrake root and then a cookie, it instantly turns brown and fails

### Steps to Reproduce
Get a cauldron with enough power for the brew. Throw in a mandrake root and any brew ingredient and try to take the brew out.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
The most recent version of Bewitchment on Sun's Server

**Comment by MaskedElephant** [comment]
Additionally, to give some clarification, I am making it within 15 seconds, and the cauldron is within two blocks of the altar and that altar has over 3k power.

**Comment by SmallEnderman** [comment]
Ayrion And I (SmallEnderman) Witnessed this at first hand that the first brew he made was successfull and then the second brew fails and this goes on even after breaking the cauldran/throwing wood ash. When throwing in the mandrake it just instantly fails.

- SmallEnderman [M]

**Comment by SmallEnderman** [comment]
Did further investigation... this bug cannot be replicated in singleplayer/solo server with bewitchment only. User who reported it was on Sunconure11 modpack server while demonstrating it, might be a modpack issue

**Comment by Sunconure11** [comment]
The mod performant is to blame.
