### ISSUE TITLE
Gold Statues White Screen Crash

### ISSUE THREAD

**Issue by DarkRift3r** [Um-Mitternacht/Bewitchment#607]
### Expected Behavior

Break the Statue and get it back

### Actual Behavior

White Screen Upon Breaking then Crash

### Steps to Reproduce

Break Any Golden Statue

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

1.12.2 / 0.0.22.12 and 0.0.21.12 / 14.23.5.2854 / 1.0-20 / 2.0.3

### Screenshots encouraged

Can't Really Provide one

### Logs, in the event of a crash

https://paste.ee/p/zuUJk#s=0

**Comment by MaskedElephant** [comment]
I have also recently experienced this crash. It might also be a statue thing in general, as it was a nether brick statue that I broke.

**Comment by Sunconure11** [comment]
I am unable to replicate this, but I do have an idea as to why this is happening. Could one of you remove mods, one by one, until the issue stops?

**Comment by Sunconure11** [comment]
Also, keep notes of the mods you pull.

**Comment by DarkRift3r** [comment]
It was a bunch of mods we put together for a custom modpack for a private server, we did change to ConquestReforged now and we added Bewitchment back into the mix again, but everyone stopped messing around with those Statues.

**Comment by Sunconure11** [comment]
I still need you to pull that off anyways. I can’t fix it if I don’t know what mod is fucking with the statues.

**Comment by DarkRift3r** [comment]
These are the Mods in the old modpack
![image](https://user-images.githubusercontent.com/67730840/87234051-ea9f9a00-c3d5-11ea-84cd-a1a9d8c89c70.png)

And These are our Current Mods

**Comment by DarkRift3r** [comment]
Whoops i think i screwed that up i never used GitHub Before
old mod list
![image](https://user-images.githubusercontent.com/67730840/87234077-1cb0fc00-c3d6-11ea-8a4a-a8ad9daa4885.png)

New mod list
![image](https://user-images.githubusercontent.com/67730840/87234085-318d8f80-c3d6-11ea-8dc8-9c69f0d9036e.png)

**Comment by Sunconure11** [comment]
Remove mods, one at a time, until the statue no longer gives you a crash. I've discussed this with the others. We're in agreement that another mod is at fault. If you find the mod at fault, please tell me, so I can inform the dev of it.

**Comment by Sunconure11** [comment]
This was never resolved. Closing.
