### ISSUE TITLE
Biome Shift Ritual Not Working

### ISSUE THREAD

**Issue by MaskedElephant** [Um-Mitternacht/Bewitchment#608]
### Expected Behavior
After choosing a biome with right click with boline in hand, and setting up and starting the ritual, the biome would change to the chosen biome.

### Actual Behavior
After the ritual starts, it starts taking power and after 15 seconds or so, it stops, and the boline will have a bit of durability gone, and all ingrediants are there with the biome not having been changed

### Steps to Reproduce
Attempt the biome shift ritual

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
This is the most recent version of Bewitchment (I believe) and is on Sun's Server

**Comment by Sunconure11** [comment]
Resolved in later builds of the mod.
