### ISSUE TITLE
Fence Gate Crashing Game

### ISSUE THREAD

**Issue by GabuSilver** [Um-Mitternacht/Bewitchment#609]
I have tried every single fence gate added by Bewitchment, all of them are crashing the game. I tried to check if there were a recent update in the mod (Im using bewitchment-1.12.2-0.0.22.15.jar) but as you can see, is the same version you guys... team has. Thx for the attention :D Have a nice day.

**Comment by Sunconure11** [comment]
Can you post a crash report?

**Comment by Sunconure11** [comment]
Closing due to a lack of a crash report. If one is given, this will be reopened.

**Comment by Sunconure11** [comment]
Issue spotted, and fixed in dev.
