### ISSUE TITLE
Game Crash Upon Start-up, linked to latest version of mod

### ISSUE THREAD

**Issue by Ikedadel** [Um-Mitternacht/Bewitchment#612]
### Expected Behavior
Game installs itself/mods normally.

### Actual Behavior
Game crashes upon startup, specifically when loading in entity sounds.

### Steps to Reproduce
Unsure, maybe a mod conflict?

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment: 0.0.22.15
Forge: Latest/14.23.5.2854
Patchouli: 1.0-20
Baubles: 1.5.2

### Logs, in the event of a crash
https://pastebin.com/an6nyB6a

**Comment by Sunconure11** [comment]
Update your mods. This happens with mods using out of date mixins.
