### ISSUE TITLE
Crash upon mod loading segment of game

### ISSUE THREAD

**Issue by Ikedadel** [Um-Mitternacht/Bewitchment#614]
### Expected Behavior
Game sets itself up and Forge loads in all mods.

### Actual Behavior
Game starts up on 'Mojang' screen, gets to first step of mod loading via Forge and crashes when it starts to load in minecraft:entities sound files, specifically at the Shulker one. Screenshots provided.

### Steps to Reproduce
Run game as normal with all mods.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
Latest/0.0.22.18
Latest/1.12.2-forge-14.23.5.2854
Latest/1.0-21
Latest/1.12-1.5.2

### Screenshots encouraged
![Screenshot_194](https://user-images.githubusercontent.com/68084570/87255696-12851100-c45b-11ea-825c-7c565cdba7d8.png)
![FF21BZj](https://user-images.githubusercontent.com/68084570/87255700-1ca70f80-c45b-11ea-8a5f-86f6ce059325.png)
Above images are immediately proceeding and preceding the crash.

### Logs, in the event of a crash
https://pastebin.com/YkSzXCGH
Most, if not all of my mods are updated. The only one that isn't is CraftStudioAPI but the update link takes me to their GitHub and I have no idea where to go from there. This crash only happens with this version of Bewitchment and the only version that a crash hasn't occurred was for ver. 0.0.21.10. Anything past that version and the game crashes.

**Comment by th4umiel** [comment]
Hi, I solved this updating vanillafix, quark and autoreglib.

**Comment by Sunconure11** [comment]
Th4umiel gave a good response to this. Just update forge and all your mods to the latest. Closing.
