### ISSUE TITLE
[Suggestion] Please add an option to disable mobs from spawning

### ISSUE THREAD

**Issue by WaterMonitor** [Um-Mitternacht/Bewitchment#615]
I love this mod and so do the players on my server. However, bewitchment mobs cause a lot of fps lag for clients(assuming due to their advanced AI) and when I try to set the spawn weights to 0 they continue to spawn. They actually seem to spawn more when set to 0.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft 1.12.2, bewitchment-1.12.2-0.0.22.15, Forge version 14.23.5.2837, Patchouli-1.0-20

**Comment by Sunconure11** [comment]
This is already possible. Just set the weight, min value, and max values to 0 for the mob in question.
