### ISSUE TITLE
Long lasting network issue

### ISSUE THREAD

**Issue by trilexcom** [Um-Mitternacht/Bewitchment#616]
### Expected Behavior
vanillafix says their a crashlog but i didn't crash the game

### Actual Behavior
crash

### Steps to Reproduce
install the latest update we have a modpack called GT Voyage 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Forge 2854
bewitchment-1.12.2-0.0.22.18
Patchouli-1.0-21
Baubles-1.12-1.5.2

### Logs, in the event of a crash

https://pastebin.com/xXpfH4HH

**Comment by Sunconure11** [comment]
Were you doing anything special that caused this to fire?

**Comment by trilexcom** [comment]
No nothing special uploaded to the server and connected to server made sure pack was updated than disconnected i got this error msg i didnt test it on single player

**Comment by Sunconure11** [comment]
Could you try the deductive approach of removing one mod at a time until this stops? I haven’t encountered this error myself, so I’m inclined to believe another mod may be causing issues.

**Comment by Sunconure11** [comment]
Keep notes of the mods you pull. Do it one at a time, but if needed, pull its dependencies as well. When it stops crashing, tell me the mod in question so it can be forwarded to the appropriate devs.

**Comment by trilexcom** [comment]
Sure
