### ISSUE TITLE
Config Enhancement 

### ISSUE THREAD

**Issue by uiytt** [Um-Mitternacht/Bewitchment#617]
So I'm a small server manager and I'm a bit sad by the lack of some configs...
Like : 
- Demon trade management (some trade are not very balanced)
- Disabling of some contracts 
- Disabling of some rituals
etc... 

Doing so will really help to allow player to balance the mod thus allowing to add this mod in more modpack / servers without being game-breaking.
Thanks

**Comment by Sunconure11** [comment]
Rituals - Possible, but Patchouli would flip out. I’m not gonna do this so I don’t break the guide books.
Demon Trade - They’re demons, of course they’d give you some OP stuff
Contracts - Possible, but I would need a list of contracts you want to be configurable.

**Comment by uiytt** [comment]
Maybe for the rituals, do not remove it from patchouli, make them just do nothing if deactivated ? 
Demon trade, well yes but for some servers, it's way too op. 
Contracts : All 6 of them :  Desiccation, Devouring Rage, Berserker, Ignition, Salamandrine Tolerance, Mahapadma
(In particular Mahapadma (instant kill of a player)).

Also for even more config option, a crafttweaker integration ?

**Comment by Sunconure11** [comment]
There's already a mod that deals with crafttweaker and us. MoreTweaker.

I think I know of something for the rituals, but it would have to be tested. Heavily.

**Comment by uiytt** [comment]
Ok thanks, I don't think it's a must but it will still be a cool enhancement

**Comment by mxnmnm** [comment]
Speaking of configs would it be possible to add a blacklist for the friendship brew/thyrsus (aka no instataming i&f dragons) and an option to prevent already tamed animals from getting stolen by another player. I know I've already asked on the discord and such but it probably got lost so I figured I'd just add it on here so you can keep track of it if you decide it is a good idea.
