### ISSUE TITLE
Crash. Tried multiple versions.

### ISSUE THREAD

**Issue by MagmaSlime123** [Um-Mitternacht/Bewitchment#618]
### Expected Behavior
The game starting.

### Actual Behavior
The game crashing.

### Steps to Reproduce
Start the game.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
Forge 2856 (The end number)
Patchouli 1.0-21
Bewitchment 1.12.2-0.0.22.18

### Screenshots encouraged
Read the log and crash report file.

### Logs, in the event of a crash
[crash-2020-07-14_22.56.25-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/4923173/crash-2020-07-14_22.56.25-client.txt)
[latest.log](https://github.com/Um-Mitternacht/Bewitchment/files/4923176/latest.log)

The crash report for whatever reason mentions SpongePowered... Which I'm not even using.

**Comment by Sunconure11** [comment]
Update all of your mods + forge.

**Comment by MagmaSlime123** [comment]
I'm on the latest versions of everything. This mod is kinda useless if you wont help me.

**Comment by Sunconure11** [comment]
First, can you put your logs on pastebin?

**Comment by CammiePone** [comment]
EnderBro, you're not on the latest version of Bewitchment, you're on version 0.21.12, which is 16 versions old now and hasn't been the newest version for over 2 months. Update Bewitchment.

If you're still crashing, the post the new logs, preferably in Pastebin. It's free, and you don't need an account.

**Comment by CammiePone** [comment]
Diiiid that fix it, @EnderBro123?
