### ISSUE TITLE
Mowzie's Mobs Potion Effects registering under Bewitchment ModID

### ISSUE THREAD

**Issue by anabsolutesloth** [Um-Mitternacht/Bewitchment#619]
Expected Behavior::
Mowzie's Mobs Potion Effects will register under Mowzie's Mob's ModID.

Actual Behavior:
Mowzie's Mobs Potion Effects register under Bewitchment's ModID instead of its own.

Steps to Reproduce:
Install both Mowzie's Mobs and Bewitchment

Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used:
Minecraft 1.12.2, Forge 14.23.5.2847, Bewitchment 1.12.2-0.0.22.10, Patchouli 1.0-20, Baubles 1.12-1.5.2.
using Mowzie's Mobs 1.5.6.

Screenshots:
![image](https://user-images.githubusercontent.com/63694982/87610722-fb445e80-c6ba-11ea-9ff3-c5f052c5f651.png)

Logs, in the event of a crash:
Snippet from a Tellme dump:
| mowziesmobs:long_poison_resist | 74 | PotionEffect:{Potion:[reg:bewitchment:poison_resist,name:potion.poisonResist,isBad:false,isBeneficial:false],amplifier:0,duration:9600,isSplashPotion:false,isAmbient:false}
| mowziesmobs:poison_resist | 73 | PotionEffect:{Potion:[reg:bewitchment:poison_resist,name:potion.poisonResist,isBad:false,isBeneficial:false],amplifier:0,duration:3600,isSplashPotion:false,isAmbient:false}

Issue was reported at Mowzie's Mobs github: BobMowzie/MowziesMobs#243

**Comment by Sunconure11** [comment]
What the fuck

Alright, I guess I gotta fix this then on my end

**Comment by Sunconure11** [comment]
Still having the issue on my end, and at least one other mod is affected. @pau101

Consecration is also affected.

**Comment by Sunconure11** [comment]
Having difficulty with implementing a fix on our end, but if it continues to be an issue when the next build of mowzies mobs is out, you can reopen this.

In the mean time, I think I know how to fix it for consecration.

Edit: Unable to build an instance of his workspace.

**Comment by Sunconure11** [comment]
Consecration's version of the bug has been fixed, but until it's fixed on Mowzie's end as well, this will remain open.
