### ISSUE TITLE
Adding Mod to Pre-existing Pack Results in Crash

### ISSUE THREAD

**Issue by MadToilet** [Um-Mitternacht/Bewitchment#622]
### Expected Behavior
Minecraft Loads

### Actual Behavior
Minecraft crashes with an unknown error.

### Steps to Reproduce
Adding Bewitchment to this modpack.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft 1.12.2
Forge 14.23.5.2854
Bewitchment-1.12.2-0.0.22.20.jar (tried previous two builds as well - same issue)
Baubles-1.12-1.5.2.jar

### Logs, in the event of a crash
https://paste.ee/p/gePyJ

**Comment by Sunconure11** [comment]
Update all mods and forge.
