### ISSUE TITLE
Grapfically bags with Druden mob

### ISSUE THREAD

**Issue by avescarelo** [Um-Mitternacht/Bewitchment#627]
When this mob is standing next to the player. Renders of inventory, skin, cloak, block nearby and textures break...

### Versions
Minecraft 1.12.2
bewitchment-1.12.2-0.0.22.22
forge-1.12.2-14.23.5.2854
Patchouli-1.0-21
Baubles-1.12-1.5.2
OptiFine_1.12.2_HD_U_F5

### Screenshots encouraged

![image](https://user-images.githubusercontent.com/26678843/88278511-2fd39e00-cceb-11ea-8048-b3df5193b267.png)

**Comment by Sunconure11** [comment]
Try without optifine first.

**Comment by avescarelo** [comment]
![image](https://user-images.githubusercontent.com/26678843/88286617-b1cac380-ccf9-11ea-8ab5-3c2962a2f5fe.png)
![image](https://user-images.githubusercontent.com/26678843/88286627-b8593b00-ccf9-11ea-9222-16c3f27e9899.png)

Without them (Also problem with default textures)

**Comment by Sunconure11** [comment]
Can you post a full mod list, and also tell me what you are using for the server?

**Comment by Sunconure11** [comment]
Another thing I’m noticing in that pic, it’s trying to render druden bits on you.

**Comment by pingvikin** [comment]
> Can you post a full mod list, and also tell me what you are using for the server?

![image](https://user-images.githubusercontent.com/26678843/88315273-c40b2880-cd1e-11ea-85d9-6c4054b23d9d.png)
![image](https://user-images.githubusercontent.com/26678843/88315315-cff6ea80-cd1e-11ea-9e09-9f167a65af8a.png)
![image](https://user-images.githubusercontent.com/26678843/88315352-da18e900-cd1e-11ea-8cda-3d3f46a65b93.png)

**Comment by avescarelo** [comment]
Plugins (18): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AmberShop, BanManager, GTS, GriefPrevention, ImpactorAPI, LuckPerms, Nucleus, Sound Silencer, TabList, Total Economy, UltimateChat, VoxelSniper, WelcomeTitles, WorldEdit

Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Animania, AppleCore, Auto Network Lib, AutoRegLib, Baubles, Bewitchment, Cases, Chameleon, CraftStudio API, Divine Favor, DupeFix Project, Farseek, FoamFix, FoamFixCore, Gravestone Mod, Improved Mobs, IvToolkit, LLibrary, LibraryEx, Login Shield, NetherEx, Ore Veins, OreLib Support Mod, PassableLeaves, PassableLeavesCore, Patchouli, Quark, Realistic Terrain Generation, Recurrent Complex, Restricted Portals, Serene Seasons, Shadowfacts' Forgelin, Spice of Life: Carrot Edition, SpongeForge, Storage Drawers, Streams, TenshiLib, The Twilight Forest, TreeCapitator, Wearable Backpacks, bspkrsCore

**Comment by Sunconure11** [comment]
Can you try without sponge?

**Comment by avescarelo** [comment]
> Can you try without sponge?

Sponge it's a server core, server not working with graphic
Also i checked in singleplayer and also have a bug (in singleplayer sponge no exist)

**Comment by avescarelo** [comment]
Hey!
Also i found some errors in client log
[
https://gist.github.com/pingvikin/ad1817876157ebcbf3508fd747910254
](
https://gist.github.com/pingvikin/ad1817876157ebcbf3508fd747910254
)
@Sunconure11 

[20:00:39] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: null

**Comment by Sunconure11** [comment]
I need you to at least make a test server that does not use sponge, and see if this issue still persists.

**Comment by avescarelo** [comment]
> I need you to at least make a test server that does not use sponge, and see if this issue still persists.

I tried alsoin singleplayer - and i have a bug
I given you logs from client -> that's client bug

(Singleplayer not have a sponge before it's a singleplayer)

**Comment by Sunconure11** [comment]
Can you try, in singleplayer, without optifine?

**Comment by avescarelo** [comment]
> Can you try, in singleplayer, without optifine?

Ahahha, just see that
This is without optifine

![image](https://user-images.githubusercontent.com/26678843/88590631-c0034180-d063-11ea-9a19-b1be65975ec0.png)
![image](https://user-images.githubusercontent.com/26678843/88590772-ede88600-d063-11ea-9d52-f25361906ece.png)
![image](https://user-images.githubusercontent.com/26678843/88590849-11abcc00-d064-11ea-8f70-be93209e446c.png)
![image](https://user-images.githubusercontent.com/26678843/88590942-3b64f300-d064-11ea-8007-6435a2c9332e.png)
![image](https://user-images.githubusercontent.com/26678843/88590966-461f8800-d064-11ea-8960-745252799a53.png)

**Comment by Sunconure11** [comment]
I legitimately have no clue why this is happening. I have packs with far more amounts of mods and I don't see this issue with druden. My guess is something is fucking with rendering.

**Comment by Sunconure11** [comment]
Wait, that cape(?), what's that from?

**Comment by avescarelo** [comment]
These are custom cloaks, they do not affect the rendering. Made through an authlib hack
![image](https://user-images.githubusercontent.com/26678843/88591270-c5ad5700-d064-11ea-9743-0a9cad55de19.png)

**Comment by avescarelo** [comment]
![image](https://user-images.githubusercontent.com/26678843/88591419-fee5c700-d064-11ea-994e-6d632e27a7e0.png)

**Comment by Sunconure11** [comment]
Dumb idea, but could you turn off your hack?

**Comment by Sunconure11** [comment]
See if that does anything. This is clearly a rendering issue.

**Comment by avescarelo** [comment]
> See if that does anything. This is clearly a rendering issue.

Not helped

**Comment by pingvikin** [comment]
Since I have my own authentication and my accounts - they just include cloaks. It doesn't affect anything

**Comment by pingvikin** [comment]
I am the owner of a small server for my friends, we do not make money from your mod. We just want everything to work well

**Comment by Sunconure11** [comment]
I only have one solution left for you to try. Delete your mods, one by one. Take notes of which mods you pull. Whichever mod you take out stops the issue that isn't BW is the one at fault. Report it to the devs of that mod.

**Comment by Sunconure11** [comment]
Do this deductive approach in singleplayer, first.

**Comment by avescarelo** [comment]
This is not before cloaks

**Comment by avescarelo** [comment]
I have a weak and old computer, but my friend has a new and powerful one. The effect is the same

**Comment by Sunconure11** [comment]
It's definitely a conflict with another mod. Try and go through your mods, one by one, until the issue stops.

**Comment by SmallEnderman** [comment]
It has to do mostly with ur modpack/server list and not with bewitchment alone... I personally cant seem to figure out how you've done this or why it's happening. My first thought was indeed the authlib hack was the cause but if u say that's not the case then i personally dont know. My suggestion? remake the modpack and try to make the rendering work... BEFORE you make it into multiplayer. (also i suggest not using authlib hack... it might still be the issue but that's just me).

Another way (if you dont want to remake the modpack) is to disable each mod one by one.. to see if it changes the rendering issue. This is THE LEAST effecient way but it might help you find the source cus currently me (and i assume sun) cannot seem to find the issue 

Sincerely
~SmallEnderman

**Comment by Sunconure11** [comment]
Issue has been resolved. It was likely a cross-mod conflict, but for some reason, due to it not being counted as a biped for quite a bit by accident, it caused issues.
