### ISSUE TITLE
can't find what mod is causing the mixin issue

### ISSUE THREAD

**Issue by HixxyDubz** [Um-Mitternacht/Bewitchment#628]
Getting a crash when i add Bewitchment to a private mod pack of mine, i added in the latest version of Bewitchment 
bewitchment-1.12.2-0.0.22.22.jar, i am using the latest versions of Patchouli and Baubles.

I do not have VanillaFix in the pack, i removed Malisis Doors and Core, and also Da Vinci's Vessels and Moving World from the pack and still no luck, i will keep attempting to remove mods 1 by 1 to see what causes it but if anyone has any suggestions please feel free to let me know so i can test it out, thanks.

**Comment by HixxyDubz** [comment]
Ok after testing each mod in a testing environment pack adding one by one at a time i finally came across BetterPortals, i have notified them of the issue on their issue tracker on github, its the only mod in the 191 mod pack i use that causes the issue, hope this helps you guys if anyone else runs into this problem then this is another mod using old mixin versions.

Link to BetterPortals issue that i posted:

https://github.com/Johni0702/BetterPortals/issues/547

**Comment by Sunconure11** [comment]
Update all of your mods + forge.
