### ISSUE TITLE
Errors in client

### ISSUE THREAD

**Issue by avescarelo** [Um-Mitternacht/Bewitchment#629]
### Expected Behavior
A lot of errors appear in the log from the client side, and only because of the VanillaFix mod - no crash occurs.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
bewitchment-1.12.2-0.0.22.22
forge-1.12.2-14.23.5.2854
Patchouli-1.0-21
Baubles-1.12-1.5.2

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/26678843/88573016-c506c780-d048-11ea-89a5-e080c1370f1d.png)
Also, the consumption of resources with the render has slightly increased. But it may not be your mod. But still, please check for memory leaks. w

### Logs, in the event of a crash
[https://gist.github.com/pingvikin/fdb07829c009b431b854fe4e308642c2](https://gist.github.com/pingvikin/fdb07829c009b431b854fe4e308642c2)

**Comment by Sunconure11** [comment]
1. Dude, how old of a build have you been using? Beehives and apiaries haven't been in this mod for ages.
2. The russian localizations stuff can be ignored by you, if you are not using russian localizations.
3. Aside from those oddities, I cannot see anything from our end. I'm seeing mentions of a mod called craftlogic though.

**Comment by avescarelo** [comment]
Oh, sorry my log have many many text and not restarting after client restart
Now i not have a craftlogic

Try search this in file:
` Suspected Mods: Bewitchment (bewitchment)`

**Comment by avescarelo** [comment]
>The russian localizations stuff can be ignored by you, if you are not using russian localizations.

I am using these localizations, but I do not understand what this question is about

**Comment by Sunconure11** [comment]
I'm saying some of the errors you could possibly be having are from using russian localizations, as looking at the logs, a good chunk do not exist for various books and what not.

**Comment by Sunconure11** [comment]
Also, you're implying a crash, but I cannot see a single crash in the log. Can you go to your crash reports folder and dredge me a crash report?

**Comment by avescarelo** [comment]
> Also, you're implying a crash, but I cannot see a single crash in the log. Can you go to your crash reports folder and dredge me a crash report?

Okay, i was founded crashreport on client
[https://gist.github.com/pingvikin/1054379fb9f03d6bbba1d4f0b783cf92](https://gist.github.com/pingvikin/1054379fb9f03d6bbba1d4f0b783cf92)

That's all

**Comment by Sunconure11** [comment]
This issue is known, but I'm not sure how to fix it.

**Comment by avescarelo** [comment]
Also I cannot refuse Russian localization, since the server itself is Russian

Thanks a lot!
