### ISSUE TITLE
The Bewitchment Light Update!

### ISSUE THREAD

**Issue by avescarelo** [Um-Mitternacht/Bewitchment#630]
We need more lights!
Why?
Because the light gives charm, mystery and coolness.

**Blocks:**
1. Candles and Candelabres
It glows in the hand thanks to optifine, but does not emit light. Since it does not burn anyway, you can make a second version of the candles/candelabra that will burn
![image](https://user-images.githubusercontent.com/26678843/88575986-64c65480-d04d-11ea-9c65-4251b124f5a8.png)
![image](https://user-images.githubusercontent.com/26678843/88575756-05684480-d04d-11ea-89e5-91be9f17c60c.png)

2. All Golden statues
Must give light, before... they are gold
![image](https://user-images.githubusercontent.com/26678843/88575842-2af54e00-d04d-11ea-95d0-751a4a4c6dad.png)

3. Сrystal ball
Light is optional, but add spirit animation to it. After all, the spirit tells us fate through this ball?
![image](https://user-images.githubusercontent.com/26678843/88576080-89223100-d04d-11ea-9dea-2273a83a4b4d.png)

**Comment by MoriyaShiine** [comment]
The candles and candelabras glow when you use flint and steel on it. No gold glowing, spirit animation probably not.

**Comment by avescarelo** [comment]
Okay, thank you 
@MoriyaShiine
