### ISSUE TITLE
Broken: Filled Goblet

### ISSUE THREAD

**Issue by alexgurrola** [Um-Mitternacht/Bewitchment#631]
### Expected Behavior

Add Water to Cauldron, then place Goblet, Cloudy Oil, Ghast Tear, and 3 Redstone, in that order to receive a Filled Goblet and Empty Jar.

### Actual Behavior

Results in nothing but boiling brown water.

### Steps to Reproduce

Attempt the recipe normally.  I tried it 4 times normally, with an Altar of 600+ ME and even tried other liquids, additional things like Mandrake root, etc, but after 15+ attempts in different orders, I give up.  It doesn't work as the Book of Shadows or JEI show it to be.  I even glanced at the source code to find the recipes in hopes something was different, but they appear to be the same.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Modpack: MC Eternal 1.3.7
Minecraft: 1.12.2
Bewitchment: 0.0.21.10
Forge: 14.23.5.2847
Patchouli: 1.0-20
Baubles: 1.5.2

### Code Snippets

Recipe: https://github.com/Um-Mitternacht/Bewitchment/blob/5a15b2246cf6205a89aaad2df313db1df2ea2fcd/src/main/java/com/bewitchment/registry/ModRecipes.java#L458

**Comment by lightlike** [comment]
As the Code you posted says, it needs 3 Redstone Dust. Have you tried that?

**Comment by alexgurrola** [comment]
@lightlike Sorry, that was a typo, which I fixed.  Every time, I used 3 Redstone Dust.  I also added more altars with ME Levels of: 744, 717, & 678 in hopes that it would help push it along, but still nothing.  I clear the cauldron with ash and try again each time, but nothing results.  I made Tallow as well to ensure the cauldron itself worked, and that popped out perfectly.

**Comment by alexgurrola** [comment]
I added a screenshot of the results and the altars below.

![2020-07-28_16 39 45](https://user-images.githubusercontent.com/3461634/88740045-f9ce5980-d0f0-11ea-97df-ad99d1dc8d55.png)

**Comment by MaskedElephant** [comment]
First off, altars only show the MP in the area, and then channel it, adding more altars won't help. Second, you don't have enough MP, so I would add enough plants and trees to get to 1000 MP, at least

**Comment by alexgurrola** [comment]
That makes more sense.  The filled goblet was able to be created after I made a forest of trees surrounding the cauldrons.

Thanks much!
