### ISSUE TITLE
Juniper Chests cannot be used or moved?

### ISSUE THREAD

**Issue by splitcord** [Um-Mitternacht/Bewitchment#632]
Juniper Chests should be able to be moved, and things should stay in the chest if holding the Juniper Key that comes with it, right? Holding a key, and holding a key ring made with multiple keys for other Juniper chests failed to allow items to stay inside the chests. Breaking the chest repeatedly does nothing, as the chest stays a permanent block. I'm not sure if there is a certain method I'm missing or if it is a bug, but I'd appreciate any insight on this issue. Thanks!

**Comment by MaskedElephant** [comment]
The juniper chest acts like a normal chest, but is different in that if you don't have the key, you can't open or break the chest. Otherwise, it acts just like a normal chest.

**Comment by splitcord** [comment]
> The juniper chest acts like a normal chest, but is different in that if you don't have the key, you can't open or break the chest. Otherwise, it acts just like a normal chest.

Hi! Thanks for replying. I know theoretically this should be the case, but even when I am holding the key in my hand, it won’t let me break the chest or even put items in it. It lets me see inside it but that’s about it. I’m just not sure why 😅

**Comment by MaskedElephant** [comment]
Make sure you have the right key, it's based off coordinates so, if you moved it and didn't get a new key, that can be an issue.

**Comment by splitcord** [comment]
> Make sure you have the right key, it's based off coordinates so, if you moved it and didn't get a new key, that can be an issue.

I do have the right key in hand while I try to use the chest. I am able to open the chest with the key, but anything I place inside it spawns back in my inventory immediately. I also cannot move/break the chest at all since first placing it, even with the key directly in my hand. I can take a video if that helps as well.

**Comment by SmallEnderman** [comment]
i personally cannot recreate this, could you perhaps demonstrate what you did? (and update to the latest version of bewitchment just in case)
