### ISSUE TITLE
Bug with dismounting from broom

### ISSUE THREAD

**Issue by StarryMisya** [Um-Mitternacht/Bewitchment#635]
I found an issue, when you can't dismount from broom. If you fly about 200 blocks you aren't able to get away from it, for dismount need reconnect to world/server.

Minecraft 1.12.2
Bewitchment 0.0.22.30 and earlier
Forge 1.12.2-14.23.5.2854
Patchouli 1.0-21
Baubles 1.12-1.5.2

**Comment by Sunconure11** [comment]
We're aware of the bugs with the brooms, but no one has managed to solve them on 1.12.
