### ISSUE TITLE
Baphomet and Covens

### ISSUE THREAD

**Issue by alexgurrola** [Um-Mitternacht/Bewitchment#636]
I'm not sure if this is a real issue or just something hidden I can't find.  The in-game book reads:

```
When in a coven, only one member of the coven must ingest this concoction in order to allow their whole coven to access the powers of the demon.
```

After summoning Baphomet, everything worked correctly, but I am still not clear how to make a coven, and my friends are getting torched quickly.

Thanks for your help!

**Comment by cybercat5555** [comment]
Covens are not in yet, this was referring to a feature we planned but decided to hold back for 1.16 and may change/not do anyways
