### ISSUE TITLE
Cannot load the mod at all

### ISSUE THREAD

**Issue by Delnth** [Um-Mitternacht/Bewitchment#640]
### Expected Behavior
It should load perfectly fine.

### Actual Behavior
Crashes the game during startup.

### Steps to Reproduce
Install bewitchment-1.12.2-0.0.22.34, launch the game, watch the game crash without reporting the mod as a suspect error.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Mod: bewitchment-1.12.2-0.0.22.34
Forge: forge-14.23.5.2854
Patchouli: patchouli-1.0-21
Baubles: baubles-1.12-1.5.2
### Screenshots encouraged
Tried to get one but for some reason it shows up a black screen.

### Logs, in the event of a crash
[Pastebin here.](https://pastebin.com/SXSmpWVK) (Please notice that the suspect mod shows as 'unknown', yet bewitchment has been confirmed to be the problem, I had to manually remove mods one by one until removing bewitchment fixed the issue)

**Comment by Sunconure11** [comment]
Update forge and all of your mods.
