### ISSUE TITLE
Cubic Chunks Incompatibility

### ISSUE THREAD

**Issue by DarianLStephens** [Um-Mitternacht/Bewitchment#643]
### Expected Behavior
To be able to use the Altar and all other witch-y things at any Y level, including outside of the vanilla 0-255 range.

### Actual Behavior
The altar is unable to produce power at levels above 255 or below 0, rendering much witchcraft unusable.
UPDATE: Or, at least that's how it was in previous versions. Now, it seems to freeze the server indefinitely when you make an altar, rendering the mod _entirely_ incompatible now.

### Steps to Reproduce
Install Cubic Chunks and Bewitchment, then build something outside the 0-255 Y range. Observe that your altar is incapable of pulling power from any plants you create up there.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Current latest for 1.12.

**Comment by MoriyaShiine** [comment]
This isn't something we can fix, Cubic Chunks fundamentally changes how the game works, so they have to do this on their end.

**Comment by DarianLStephens** [comment]
Are you sure? There are a bunch of mods which have added compatibility on their own side.
Mekanism, Ice and Fire, and Better Portals are all ones which have done so off the top of my head.

**Comment by Sunconure11** [comment]
Bruh even I don’t want to work on 1.12 builds of this mod much anymore. I wanna dick around with Fabric mods

**Comment by Sunconure11** [comment]
Also, it would require more effort than what I want to put in at this point, since it would require changes to the code in question that are fairly drastic.

**Comment by DarianLStephens** [comment]
That's a fair enough explanation; I know you've been gunning for the final 1.12 release for a while now, I was just hoping I could get something else squeezed in before the true finalé, but there's no harm if you're done with it at this point.
I'll be looking forward to seeing what you come up with on Fabric, at least; I've been interested in that for a while, but haven't had much cause to use it.
