### ISSUE TITLE
New Chunk Loading after reaching destination via Broom doesn't allow you to dismount

### ISSUE THREAD

**Issue by Raybellic** [Um-Mitternacht/Bewitchment#644]
### Expected Behavior
Dismount the broom at your own desire.
### Actual Behavior
Not being able to dismount when reaching new location (it just crouches on the broom).

### Steps to Reproduce
A Cypress Broom was used, non rendered chunks are to be rendered (I travelled 1 thousand blocks + to reach my destination)

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft version: 1.12.2, Bewitchment version: bewitchment-1.12.2-0.0.22.36, Patchouli 1.0-20, Forge Version: 8.0.99.99, Baubles: 1.12 (1.5.2).

### How I resolved it
Exiting and entering back the world.

### How did I know where my destination was?

I used the nature compass mod to find my biome of choice.

**Comment by Sunconure11** [comment]
Brooms are known to be buggy.
