### ISSUE TITLE
Grimoire Magia stored magic returns to maximum limit when middle mouse button bind from inventory tweaks is pressed

### ISSUE THREAD

**Issue by Raybellic** [Um-Mitternacht/Bewitchment#645]
### Expected Behavior
For the stored magic to remain the same until charged by the altar.

### Actual Behavior
When ordering inventory by pressing middle mouse button the stored magic returns to maximum capacity.

### Steps to Reproduce
Have the Grimoire run out of any amount of power then press middle mouse button.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft version: 1.12.2, Bewitchment version: bewitchment-1.12.2-0.0.22.36, Patchouli 1.0-20, Forge Version: 8.0.99.99, Baubles: 1.12 (1.5.2).

**Comment by Sunconure11** [comment]
Hm, this is odd.

I'll see if it's possible for me to investigate this. However, they have ditched all support for the mod at this point. The repo is archived.
