### ISSUE TITLE
Placing Golden Herne Statue Crashes Client

### ISSUE THREAD

**Issue by EmberWulven** [Um-Mitternacht/Bewitchment#646]
### Expected Behavior
Placing Golden Herne statue places statue without complications.

### Actual Behavior
Placing the statue crashes the client entirely.

### Steps to Reproduce
Place a Golden Herne Statue in the world.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC Game Version 1.12.2,  Bewitchment version 1.12.2-0.0.22.36, Forge version forge-14.23.5.2838, Patchouli-1.0-20, baubles version 1.12-1.5.2, Playing RLCraft modpack version 2.8.2 by Shivaxi, 

### Logs, in the event of a crash
[crash-2020-08-19_12.08.25-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/5099078/crash-2020-08-19_12.08.25-client.txt)

**Comment by EmberWulven** [comment]
I have tried this with a stone herne statue as well. Placing the statue causes the game to crash, but when I reload the game the statue is there.

**Comment by Sunconure11** [comment]
I've heard of this issue, but I have been unable to replicate it myself. If someone does find a reliable way to replicate it, and knows what is at fault, they can send over a commit.
