### ISSUE TITLE
Bewitchment Book of Shadows problem

### ISSUE THREAD

**Issue by ClockyVaudeville** [Um-Mitternacht/Bewitchment#647]
The mod itself does't have any issues far as I can tell, but the Book of Shadows saved my progress from a different world AND a different version. I updated Bewitchment to the newest release posted on Curseforge (and all the dependencies and such as well) but for some reason, even though I made a new world with the different version of the Bewitchment mod, it saved my progress from the old one (which I even deleted to see if that was causing the issue). Because it has been almost 6 months since I last played the mod and I am no longer familiar enough with it to know exactly where I need to go and what I need to read from point x, y or z it's kind of left me at a loss as for what I do next, or what I look at next, or the progression I made to get there. If you could fix this for future releases that would be good. ^^

All the best,
ClockyVaudeville

**Comment by MaskedElephant** [comment]
The book of shadows doesn't have any 'progression' like for example the lexica botanica from botania. Once you make the book of shadows, all of its content unlocks

**Comment by ClockyVaudeville** [comment]
that's not what I mean, I know it doesn't have proper progression like Thaumcraft does for example, I mean that when I opened my fresh book of shadows, just made, on a world that I had just started all the red exclamation points on the chapters were missing save for two on chapters I hadn't read yet on my last world 6 months ago. I wondered if maybe because I still had my other Bewitchment world in my world selection it might have confused the game, but when I deleted that world (I had to anyway, installed Biomes O'plenty and Natura before playing the mod again, wouldn't have had the trees/biomes on the other world) the red exclamation points were still gone, that's why I said the mod itself has no problems but the book of shadows didn't reset upon creation of a new world.

**Comment by MaskedElephant** [comment]
That is a strange glitch, but you can always just reread if you can't remember what you need to read.

**Comment by ClockyVaudeville** [comment]
ik, and I am, just figured I'd let them know in case they didn't ^^

**Comment by SmallEnderman** [comment]
That part of the glitch is (im 99% sure) a part of patchouli and not bewitchment, see if you can test this with other patchouli using books aswell (such as Nature's aura or Roots 2? or is it 3 by now, not sure) If the issue still occurs, comment it
