### ISSUE TITLE
Found a crash report from Vanillafix

### ISSUE THREAD

**Issue by SamLam140330** [Um-Mitternacht/Bewitchment#648]
### Expected Behavior
No crash report after disconnected to the server.

### Actual Behavior
The mod called "vanillafix" found a crash from Bewitchment after I disconnected to the server.

### Steps to Reproduce
Every time I disconnect to the server.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 14.23.5.2854
Bewitchment: 0.0.22.36.jar
Patchouli: 1.0-21
Baubles: 1.5.2

### Logs, in the event of a crash
Crash Report: https://pastebin.com/qbEPQDBi
A part of log: https://pastebin.com/mc29BZAb

**Comment by Sunconure11** [comment]
I literally have no clue why this is happening, yet I've encountered it myself. If someone finds a solution, feel free to commit it.
