### ISSUE TITLE
Im concerned the updates are corrupting my game files.

### ISSUE THREAD

**Issue by ClockworkTL** [Um-Mitternacht/Bewitchment#649]
So whenever I update the mod and load previous save files the used previous versions of the mod in my modpack  it tells me that certain files are missing and if I proceed in loading the world save then it will delete the files. After click yes so I can load the world I notice that the creative menu's items have been jumbled for some of the mods. Now I don't necessarily mind this but I am concerned that there may be more damage than I can first see.

Minecraft version 1.12.2. Bewitchment versions bewitchment-1.12.2-0.0.22.9.jar to bewitchment-1.12.2-0.0.22.37.jar

![Screenshot (17)](https://user-images.githubusercontent.com/53408655/90907566-00668e80-e388-11ea-9ec3-93f9c3c18294.png)
![Screenshot (18)](https://user-images.githubusercontent.com/53408655/90907585-0492ac00-e388-11ea-8b65-523710e97737.png)

**Comment by anqingchen** [comment]
Mod update removed a bunch of blocks/registries, that's normal behavior.

**Comment by ClockworkTL** [comment]
Is there any way I can solve the issue of it jumbling the menu?
