### ISSUE TITLE
Filled Goblet when placed by player, no one else sees

### ISSUE THREAD

**Issue by Likeabozz123** [Um-Mitternacht/Bewitchment#650]
### Expected Behavior
Its supposed to show to other people

### Actual Behavior
So basically I was running a multiplayer server, and when a player placed a filled goblet no one else could see expect the person who placed it.

### Steps to Reproduce
Just place it in a multiplayer server

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2, Bewitchment-1.12.2-0.0.22.37, 14.23.5.2847, Patchouli-1.0-20, Baubles-1.12-1.5.2

### Logs, in the event of a crash
No crashes

**Comment by Sunconure11** [comment]
wat

**Comment by Likeabozz123** [comment]
So when a player places a filled goblet, no one else can see the goblet. But no one crashes either, but if someone trys to walk in the block they bug out.

**Comment by anqingchen** [comment]
Cannot replicate, show evidence. Most likely your server is lagging and not syncing with client correctly. Try restarting server/clients
