### ISSUE TITLE
Ideas for Spirit and Nature themed content 

### ISSUE THREAD

**Issue by Theguyofyharn** [Um-Mitternacht/Bewitchment#651]
https://www.reddit.com/r/feedthebeast/comments/iglc3v/ideas_for_bewitchment_content_the_wilds/
Reddit link

**Comment by Sunconure11** [comment]
We aren't taking suggestions. And certainly not on the repo.

**Comment by Theguyofyharn** [comment]
oh sorry,i didnt know XD
