### ISSUE TITLE
[Suggestion] Iron Gall Ink should be able to dye sheep

### ISSUE THREAD

**Issue by MaskedElephant** [Um-Mitternacht/Bewitchment#652]
Just like how black floral powder from botania and ink sacs can dye sheep, I feel like Iron gall ink and the other substitutes should also be able to dye sheep

**Comment by SmallEnderman** [comment]
do note that the iron gall ink is meant as another option if you cannot find squids, it's not ink. (also dont think u can just apply a iron nugget that has black coating onto a sheep). If you really needed black wool either use the iron gall ink (which is quite cheap to make) or just search for squids

**Comment by Sunconure11** [comment]
No no Small, currently Iron Gall Ink can't be used to dye sheep. This could actually be a good minor feature to add.
