### ISSUE TITLE
Double Caduceus and Wand from Baphomet and Leonard

### ISSUE THREAD

**Issue by Raybellic** [Um-Mitternacht/Bewitchment#653]
When using the butter fingers brew on Baphomet and Leonard it drops their weapons and drops them again when they're killed.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft version: 1.12.2, Bewitchment version: bewitchment-1.12.2-0.0.22.39, Patchouli 1.0-20, Forge Version: 8.0.99.99, Baubles: 1.12 (1.5.2).

**Comment by Sunconure11** [comment]
I tried to make butterfingers not apply to them, but I couldn't find a good workaround.
