### ISSUE TITLE
Token of Remedies doesn't work on poison

### ISSUE THREAD

**Issue by TheUnderTaker11** [Um-Mitternacht/Bewitchment#654]
### Expected Behavior
Token of Remedies, along with a fully charged Grimoire Magia, should heal you from poison.

### Actual Behavior
It does absolutely nothing.

### Steps to Reproduce
1. Join a server
2. Get a Token of Remedies, put in Baubles slot (I used Amulet)
3. Have a fully charge Grimoire Magia in your inventory.
4. Splash your self with poison and watch in sadness while you take poison damage for the next 45 seconds.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC 1.12.2
Bewitchment 1.12.2-0.0.22.37
Forge 14.23.5.2854
Patchouli -1.0-21
Baubles 1.12-1.5.2

### Screenshots encouraged
None needed

### Logs, in the event of a crash
N/A

**Comment by Sunconure11** [comment]
It does not clear poison. Just things like blindness and nausea.

**Comment by k1r0s** [comment]
wouldnt be nice if we can set which potion effects token of remedies can remove through config? and set the cost in ME doing so?

- POISON: 100
- NAUSEA: 40
and so forth
