### ISSUE TITLE
[Suggestion] Clarify tooltip/book description on Token of Remedies

### ISSUE THREAD

**Issue by TheUnderTaker11** [Um-Mitternacht/Bewitchment#655]
Currently, the tooltip description says "The gem in its core seems to absorb illnesses", and the book description says "This will cure the wearer of a variety of negative status effects at the cost of magical energy" and the [wiki page](https://bewitchment.fandom.com/wiki/Baubles) says "Cures debuffs at the cost of ME".

In my opinion, this would lead any logical person to think it will cure poison, and possibly even wither.

**Comment by ghost** [comment]
I second this. When I think of illnesses I think of stuff like poison. Not what it actually cures.

**Comment by MayliSong** [comment]
What exactly does it cure? I know this isn't really the place but I cannot for the life of me figure out what it does.

**Comment by k1r0s** [comment]
https://github.com/Um-Mitternacht/Bewitchment/blob/1.12.2/src/main/java/com/bewitchment/common/item/equipment/baubles/ItemTokenOfRemedies.java#L22

BLINDNESS
NAUSEA
WEAKNESS

**Comment by k1r0s** [comment]
https://github.com/Um-Mitternacht/Bewitchment/issues/654#issuecomment-712881170

> wouldnt be nice if we can set which potion effects token of remedies can remove through config? and set the cost in ME doing so?

```
POISON: 100
NAUSEA: 40
and so forth
```

Everybody would enjoy that posibility

**Comment by Sunconure11** [comment]
I'll get to clarifying this in a future update. I keep planning it but keep forgetting.
