### ISSUE TITLE
Coquina Slab Issue

### ISSUE THREAD

**Issue by QuantumGhost64** [Um-Mitternacht/Bewitchment#668]
Expected Behavior:
When two coquina slabs are placed on top of each other to make a full block, it should create a coquina block.

Actual Behavior:
When two coquina slabs are placed on top of each other, it creates a coquina bricks block.

Steps to Reproduce:
Place one coquina slab atop another

Minecraft:1.12.2, Bewitchment:0.0.22.43, Forge:14.23.5.2854, Patchouli:1.0-20, Baubles:1.5.2

Screenshots:
![image](https://user-images.githubusercontent.com/74027749/98309604-cab66680-1fc2-11eb-8d12-3ecab68da7bc.png)
![image](https://user-images.githubusercontent.com/74027749/98309671-f20d3380-1fc2-11eb-93bb-fbeeee976889.png)

**Comment by Sunconure11** [comment]
This is actually deliberate behavior, but if I have to push out another update, I could change this. Though this is unlikely on 1.12, and this block is being moved somewhere else entirely on 1.16+.
