### ISSUE TITLE
Cauldon Fails

### ISSUE THREAD

**Issue by Override5** [Um-Mitternacht/Bewitchment#672]
### Expected Behavior
Im unable to make a potion or use Dimensional Sand

### Actual Behavior
As soon as i place a Mandrake Root or Dimentional Sand into a lit and powered Cauldon, the contents spoils and turns brown.

### Steps to Reproduce
Unknown, currently only able to reproduce on the Raznet MC server on Technic, the mod owners and admins have not touched any config files or messed with the Ticks

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC version 1.12.2
Bewitchment 1.12.2-0.0.21.12
Forge Mod Loader 8.0.99.99
Patchouli 1.0-20
Baubles 1.12-1.5.2
Baubleicious 1.4.0-4

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/69968054/99944957-dd54dc00-2dc7-11eb-8a4a-001ba59f07fa.png)

**Comment by Sunconure11** [comment]
If you are using performant, remove it. It causes this issue.

**Comment by Override5** [comment]
> If you are using performant, remove it. It causes this issue.

performant is not in the modpack. Just had a look. Does it have another name on the mod menu ingame or is there another mod that may cause this kind of problem?

**Comment by Sunconure11** [comment]
I think I found your network's discord server. This may be something that the staff did on the server.

**Comment by Override5** [comment]
All fixed!
