### ISSUE TITLE
Bewitchment & Dynamic Trees Elder Tree Crash

### ISSUE THREAD

**Issue by GameDungeon** [Um-Mitternacht/Bewitchment#674]
Describe the bug
If you plant and break a bewitchment elder tree sapling with dynamic trees compat set to true the game crashes. (tested on a server if that has anything to do with it) I was sent here by the DT mod developers because they said it was not their issue.

Crashes
https://hastebin.com/raw/mefaqohedi

**Comment by Sunconure11** [comment]
Also aware of this. Don't know why this happens.
