### ISSUE TITLE
[Suggestion] Early Crafttweaker Support

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Um-Mitternacht/Bewitchment#678]
_Note: I Know this suggestion can be to early, but maybe some sort of support can be done with low effort._

### Allow Modpack Maker to manipulate recipes
I am trying to use your mod in my modpack, but until now I can not find ways to manipulate, change, add recipes.
- Distillery (input, output, heat source [allow other items too])
- Spinning Wheel (input, output, time needed)
- Cauldron (in,out,ect)
- Oven (in,out,ect)
For all: Magic Energy needed

This would allow Modpack Makers to set basic stuff, until your mod is completed and port to 1.16+
This can be a Agenda for your next Meeting.

**Comment by Ayrion** [comment]
Try using MoreTweaker, it should have at least some of those
https://www.curseforge.com/minecraft/mc-mods/moretweaker

**Comment by Xarmat-GitHub** [comment]
Thanks for the hint, was not aware of that.
Wiki Link: [https://bitbucket.org/noeppi_noeppi/moretweaker/wiki/bewitchment.md](https://bitbucket.org/noeppi_noeppi/moretweaker/wiki/bewitchment.md)

I think this is enough for basic tweaking in this stage of the mod.
-CLOSE-
