### ISSUE TITLE
[Sugesstion] Add Prefix to Item Name

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Um-Mitternacht/Bewitchment#679]
### Make finding and reading Item IDs easier
At the moment, the jars have all unique names and its hard to find all of them with a prefix in JEI.
Adding short profix into the item name can help the player to find faster what they are searching for.
Also it helps me as a modpack creator to set items in scripts and excel sheets.

**Example:**
_Jars:_
- jar_cleansing_balm
- jar_ebb_of_death

_Strings:_
- string_diabolical_vein

_Candle:_
- change name from "magenta_candle" to "candle_magenta" (item + color)

When this is not interesting for you, then close this Ticket. 😉
But naming things right from the beginning, can help a lot in the late production.

**Comment by Sunconure11** [comment]
This would fuck up too much on 1.12, as it would call for a massive refactor. It'd be better for something like 1.16 or something.
