### ISSUE TITLE
game crashes on startup with latest version of minestuck universe

### ISSUE THREAD

**Issue by spyguy26** [Um-Mitternacht/Bewitchment#684]
### Expected Behavior
game loads with bewitchment without crashing while also having minestuck universe installed

### Actual Behavior
game does not start up with the latest version of minestuck universe installed

### Steps to Reproduce
install the latest versions (listed below) of minestuck, minestuck universe, and bewitchment 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
minecraft version: minecraft-1.12.2-client.jar
forge version: 14.23.5.2854
patchouli version: Patchouli-1.0-20.jar
baubles version: Baubles-1.12-1.5.2.jar
bewitchment version: bewitchment-1.12.2-0.0.22.49.jar
minestuck version: Minestuck-1.12.2-1.4.300.jar
minestuck universe version: MinestuckUniverse-1.2.1.jar

### Logs, in the event of a crash
https://gist.github.com/spyguy26/7e5786305b4aed0df89c38d48df6530f

**Comment by MoriyaShiine** [comment]
We can't do anything about it, they're returning null for tool material names, which you should _never_ do.
