### ISSUE TITLE
Issue W/ Cauldrons and Altars 

### ISSUE THREAD

**Issue by twinkl3littl3bat** [Um-Mitternacht/Bewitchment#685]
### Expected Behavior
Altars: When shift + right clicking an altar,  the amount of ME/recharge rate of ME should be displayed.
Cauldrons: Upon tossing ingredients into a cauldron with boiling water, the water will change colors and the desired item should pop out.
### Actual Behavior
Altars: The amount of ME/recharge rate of ME is nowhere to be seen. 
Cauldrons: The water changes colors (blue to purple to a brownish red), but no item appears. My altar is close by, and I have many modifiers on the altar and many plants in close proximity. Still nothing.
^^This occurs in Survival and Creative mode (even with a Blessed Alter and modifiers)^^

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
Bewitchment 1.12.2-0.0.22.49
Forge 1.12.2
Patchouli 1.0-22
Baubles 1.12-1.5.2

**Comment by Sunconure11** [comment]
Do you have performant installed? If so, remove it. It causes this issue.

**Comment by Ayrion** [comment]
You don't shift right click on an altar to get the power reading, you just right click it with an empty hand.

**Comment by twinkl3littl3bat** [comment]
@Sunconure11 Nope! I don't think I've even heard of that before. 
@Ayrion That doesn't seem to work for me either. Where is the power reading supposed to appear? In a corner? At the top?

**Comment by Ayrion** [comment]
![2020-12-10_22 41 54](https://user-images.githubusercontent.com/44817995/101838693-0059ec80-3b39-11eb-8646-cc6aecb237ba.png)

**Comment by twinkl3littl3bat** [comment]
Ah, I see. Here's what mine looks like:
![Screenshot (19)](https://user-images.githubusercontent.com/75811729/101839103-675ead80-3b07-11eb-9132-d6401b3bf41e.png)

**Comment by Ayrion** [comment]
Doesn't look like you've actually made the altar, right click it with a carpet

**Comment by twinkl3littl3bat** [comment]
... so THAT'S what I was doing wrong. Don't I feel sheepish. Thanks for clearing that up for me! Now I need to try making something in my cauldron.

**Comment by twinkl3littl3bat** [comment]
It worked! I finally got some chalk! Thanks for taking the time to help me out, y'all. Hopefully I won't have to come back with any more silly mistakes. :D
