### ISSUE TITLE
Juniper Broom Crashing games and server upon right click

### ISSUE THREAD

**Issue by jordan-moore** [Um-Mitternacht/Bewitchment#686]
### Expected Behavior
Placing broom on ground does not crash the game/server

### Actual Behavior
Placing Juniper broom on the ground does crash the server

### Steps to Reproduce
Place Juniper broom on the ground with right click.
Pastebin of crash log. https://pastebin.com/1PZpgkRX

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2-0.0.22.49, 14.23.5.2854, 1.0-22, 1.12-1.5.2

### Screenshots encouraged
NA

### Logs, in the event of a crash
https://pastebin.com/1PZpgkRX

**Comment by Sunconure11** [comment]
We are aware of this issue. It is due to an attempt at fixing the brooms. It should clear up in a future update, however.

**Comment by jordan-moore** [comment]
Seems fixed in latest updates so closing out.
