### ISSUE TITLE
Remove Contract from player

### ISSUE THREAD

**Issue by Erani0** [Um-Mitternacht/Bewitchment#689]
### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
MC 1.12.2, Bewitchment 0.0.22.47
I have use the wrong contract with auto smelt any chance to remove this now from me?

**Comment by Sunconure11** [comment]
There is a command for this.

Syntax is `/curse <player> <get/add/remove/clear> <time>`

**Comment by Sunconure11** [comment]
And before you ask, yes, codewise, contracts are curses.
