### ISSUE TITLE
EDX-Multipart carpet won't form altar

### ISSUE THREAD

**Issue by Gorgok** [Um-Mitternacht/Bewitchment#693]
### Expected Behavior
Craft altar and form multiblock with carpet placement.

### Actual Behavior
Craft altar and place carpet on top/side, no multiblock forms. Carpet places as normal, or is blocked from placing by player/objects.

### Steps to Reproduce
Place carpet on top/side, won't form. Remove EDX carpet in config (or the whole mod) and it works fine.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
forge-14.23.5.2854

Baubles-1.12-1.5.2.jar
bewitchment-1.12.2-0.0.22.55.jar
Patchouli-1.0-22.jar

EDX-Multipart-1.1.1.jar
MCMultiPart-2.5.3.jar

**Comment by Sunconure11** [comment]
It only works with vanilla carpets.
