### ISSUE TITLE
[Feature Request] OAK APPLE GALL

### ISSUE THREAD

**Issue by jimmytrouser** [Um-Mitternacht/Bewitchment#694]
I would like to suggest there be a cfg option to disable the dropping of these apples and instead use a recipe to craft the oak apple gall; perhaps rotten flesh and an apple in a crafting table or window - shapeless may work.

Thanks.

**Comment by Sunconure11** [comment]
No plans for a crafting recipe.

https://en.m.wikipedia.org/wiki/Oak_apple

That being said, a config is not out of the realm of possibility.

**Comment by jimmytrouser** [comment]
I realise the realism is necessary, I just thought I could get them in game another way so they are not dropping in the game world.

Thanks.
