### ISSUE TITLE
Earth Protection Poppet not working?

### ISSUE THREAD

**Issue by jcor33** [Um-Mitternacht/Bewitchment#695]
### Expected Behavior
Protects the bound player from taking fall damage

### Actual Behavior
Uses durability, but bound player still takes fall damage

### Steps to Reproduce

1. Make Poppet
2. Make Taglock & Bind Poppet to Player
3. Jump from a high place to take fall damage with the poppet in your inventory

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2
Forge: 14.23.5.2847
Patchouli: 1.0-20
Baubles: 1.5.2
(MC Eternal Modpack)

### Screenshots encouraged
![Before Jump](https://user-images.githubusercontent.com/77278421/104184724-e9c9de00-53e1-11eb-8f49-3b76647c9792.png)
![Taking fall damage with poppet in inventory and it using durability](https://user-images.githubusercontent.com/77278421/104184834-1251d800-53e2-11eb-8ad9-b026d59c95c9.png)

**Comment by Sunconure11** [comment]
I literally can’t tell what’s going on here, due to your increased health. Set your health to default and try again. Also, the build Eternal uses is very out of date.
