### ISSUE TITLE
[Crash] [Server] ForgeEssentials +  Bewitchment

### ISSUE THREAD

**Issue by TheMartinfer22** [Um-Mitternacht/Bewitchment#697]
Hello, I am witnessing an inconvenience with the mods mentioned above, it seems to me that they are using a common resource, is there an alternative solution without being not using them? Or is there a possibility for corrections?

Crash: https://haste.mohistmc.com/yutenuxoro.properties

------
**INFO**
------

**Server Build: Mohist #172 1.12.2
Bug Type: On start
Mods: forgeessentials-1.12.2-12.3.82-server and bewitchment-1.12.2-0.0.22.58**

**Comment by Sunconure11** [comment]
Update all mods using mixins.
