### ISSUE TITLE
[BUG] (Juniper) Broom weirdness

### ISSUE THREAD

**Issue by Shazuli** [Um-Mitternacht/Bewitchment#698]
### Expected Behavior
When I was flying my Juniper Broom (haven't tested other brooms yet) over the water it randomly disappeared. Thought it dropped itself in the water so dived into the water and couldn't find it. Read the logs and saw these lines:
```
[20:07:45] [Server thread/WARN] [minecraft/Chunk]: Wrong location! (17, 64) should be (20, 47), EntityJuniperBroom['Juniper Broom'/836065, l='MagicPack2', x=276.83, y=71.16, z=1024.28]
[20:07:45] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity bewitchment:juniper_broom but it was marked as removed already
```

Decided to craft a new Juniper Broom and did a backup of the world to see if it would happen again, and so it did. It wrote the same warning lines again:
```
[21:32:47] [Server thread/WARN] [minecraft/Chunk]: Wrong location! (18, 65) should be (20, 48), EntityJuniperBroom['Juniper Broom'/10818, l='MagicPack2', x=299.29, y=87.89, z=1040.86]
[21:32:47] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity bewitchment:juniper_broom but it was marked as removed already
```

After a bit of testing it appears if I remove the mod [Better Portals](https://www.curseforge.com/minecraft/mc-mods/betterportals) the broom no longer gets deleted when those warning logs appear, but I can no longer dismount the broom unless I reload the world.
Better yet: When it didn't delete the broom I continued flying around on it. I noticed a village and saw other entities walking around like normal, and I could interact with them even if I couldn't dismount the broom. I also noticed there was no aura from the mod [Thaumcraft](https://www.curseforge.com/minecraft/mc-mods/thaumcraft) when I tried to kill the broom entity with the Gauntlet and Foci. The Foci worked fine, but both the Gauntlet and Thaumometer both said there was none. I then flew back home, but I still couldn't dismount the broom. So I tried sleeping and that finally kicked me off the broom, but it got deleted again in the process. The aura was back to normal at my base.

Reading older issues regarding brooms it seems like the problem with no being able to dismount off of brooms is a well-known issue. So perhaps my little bug adventure could give some insight into the problem? I feel like it is a server-client desync issue. I'm guessing the brooms are rideable entities like Minecarts and Horses, but some packages are lost due to brooms being way faster than any other vanilla rideable and causes a rubber-band effect which could explain the message: `Wrong location! (18, 65) should be (20, 48), Ent...` from the logs.

### Steps to Reproduce
Could be fairly complicated to reproduce. I think it would be best to write down every single mod I have installed (I should mention this is a singleplayer world, and not on multiplayer).

Mod | Version
------ | -------
Minecraft | 1.12.2
[Akashic Tome](https://www.curseforge.com/minecraft/mc-mods/akashic-tome) | 1.2-12
[AutoRegLib](https://www.curseforge.com/minecraft/mc-mods/autoreglib) | 1.3-21
[Baubles](https://www.curseforge.com/minecraft/mc-mods/baubles) | 1.12-1.5.2
[Better Portals](https://www.curseforge.com/minecraft/mc-mods/betterportals) | 0.3.7.7
Bewitchment | 1.12.2-0.0.22.55
[Bibliocraft](https://www.curseforge.com/minecraft/mc-mods/bibliocraft) | 2.4.5
[Bloodmoon](https://www.curseforge.com/minecraft/mc-mods/bloodmoon) | 1.5.3
[Chunk Animator](https://www.curseforge.com/minecraft/mc-mods/chunk-animator) | 1.2
[Comforts](https://www.curseforge.com/minecraft/mc-mods/comforts) | 1.12.2-1.4.1.2
[Consecration](https://www.curseforge.com/minecraft/mc-mods/consecration) | 1.12.2-1.0.6
[Dynamic Surroundings](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings) | 1.12.2-3.6.1.0
[Dynamic Trees](https://www.curseforge.com/minecraft/mc-mods/dynamictrees) | 1.12.2-0.9.21
[Dynamic Trees TC](https://www.curseforge.com/minecraft/mc-mods/dttc) | 1.12.2-1.4.2
[End Portal Parallax](https://www.curseforge.com/minecraft/mc-mods/end-portal-parallax) | 1.0
[Gravestone Mod](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod) | 1.10.3
[iChunUtil](https://www.curseforge.com/minecraft/mc-mods/ichunutil) | 1.12.2-7.2.2
[Item Scroller](https://www.curseforge.com/minecraft/mc-mods/item-scroller) | 0.12.0
[Just Enough Items](https://www.curseforge.com/minecraft/mc-mods/jei) | 4.16.1.301
[Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) | 0.8.5
[Mixin Compability](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) | 0.8
[MobDismemberment](https://www.curseforge.com/minecraft/mc-mods/mob-dismemberment) | 1.12.2-7.0.0
[No Recipe Book](https://www.curseforge.com/minecraft/mc-mods/no-recipe-book) | 1.2.1
[Optifine](https://www.optifine.net/home) | 1.12.2-HD-U-F5
[OreLib Support Mod](https://www.curseforge.com/minecraft/mc-mods/orelib) | 1.12.2-3.6.0.1
[Particle Culling](https://www.curseforge.com/minecraft/mc-mods/particle-culling) | 1.0.1
[Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli) | 1.0-20
[PeacefulSurface](https://www.curseforge.com/minecraft/mc-mods/peacefulsurface) | 1.12.2-v1b
[Phosphor Lightning Engine](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge) | 1.12.2-0.2.6+build50
[Quark](https://www.curseforge.com/minecraft/mc-mods/quark) | r1.6-179
[Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) | 1.2.18
[Serene Tweaks](https://www.curseforge.com/minecraft/mc-mods/serene-tweaks) | 0.1
[Shadowfacts' Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin) | 1.8.4
[Smooth Font](https://www.curseforge.com/minecraft/mc-mods/smooth-font) | mc1.12.2-2.1.2
[Sound Filters](https://www.curseforge.com/minecraft/mc-mods/sound-filters) | 0.12.1_for_1.12
[Thaumcraft](https://www.curseforge.com/minecraft/mc-mods/thaumcraft) | 1.12.2-6.1.BETA26
[Thaumic Augmentation](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation) | 1.12.2-2.0.13
[ThaumicJEI](https://www.curseforge.com/minecraft/mc-mods/thaumic-jei) | 1.12.2-1.6.0-27
[VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix) | 1.0.10-150

**Comment by Shazuli** [comment]
Perhaps I could export the whole pack + world and add it to a Cloud service? That was you could experience the bug in a controlled environment. Just a thought if you have problems reproducing it by yourself.

**Comment by Sunconure11** [comment]
Brooms are known to be bugged. We tried to fix them, many times.
