### ISSUE TITLE
[Development] Getting Started

### ISSUE THREAD

**Issue by WalrusSoup** [Um-Mitternacht/Bewitchment#701]
Looking to load this and fix a crash on broom usage (error writing state). However, I can't seem to actually get it to build without throwing an HTTP error pulling a dependent library. 

Any input appreciated. 

### Expected Behavior
 Running grade \ maven should succeed.

This specific website is down:

`repositories { maven { url "https://maven.mcmoddev.com/" } } dependencies { deobfCompile "net.ilexiconn:llibrary:1.7.19-1.12.2" }`

### Actual Behavior

Throws HTTP connection error to https://maven.mcmoddev.com.
mcmoddev.com yields DNS_PROBE_FINISHED_NXDOMAIN 

** server can't find mcmoddev.com: SERVFAIL

### Steps to Reproduce

Run build

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Latest

**Comment by Sunconure11** [comment]
Can you list what build of BW you are using that prompted you to try this, first? Because I had resolved a crash with brooms.

https://github.com/Um-Mitternacht/Bewitchment/issues/686

**Comment by Sunconure11** [comment]
I'll still look into another maven that has this, regardless.

**Comment by Sunconure11** [comment]
Wait, what branch are you even compiling? This mod isn't even using that build in the workspace.

**Comment by WalrusSoup** [comment]
For the modpack it's [FTB infinity evolved reloaded](https://www.curseforge.com/minecraft/modpacks/infinityevolved-reloaded/relations/dependencies). It could be using the wrong version, I'll need to check tonight. Regardless, I've always wanted to check out MC modding and im a big fan of the OG witchery mod so I figured I would just give it a shot.

Process to get up and running so far is:


```
git clone git@github.com:Um-Mitternacht/Bewitchment.git

On branch 1.12.2
Your branch is up to date with 'origin/1.12.2'.
```


Opening up in Intellij Idea will run the build process automatically, yielding:

```
* What went wrong:
A problem occurred configuring root project 'Bewitchment'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve net.ilexiconn:llibrary:1.7.9-1.12.2.
     Required by:
         project :
      > Could not resolve net.ilexiconn:llibrary:1.7.9-1.12.2.
         > Could not get resource 'https://maven.mcmoddev.com/net/ilexiconn/llibrary/1.7.9-1.12.2/llibrary-1.7.9-1.12.2.pom'.
            > Could not GET 'https://maven.mcmoddev.com/net/ilexiconn/llibrary/1.7.9-1.12.2/llibrary-1.7.9-1.12.2.pom'.
               > maven.mcmoddev.com

```


```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://maven.mcmoddev.com/net/ilexiconn/llibrary/1.7.9-1.12.2/llibrary-1.7.9-1.12.2.pom'.
````

![Screen Shot 2021-01-25 at 10 14 57 AM](https://user-images.githubusercontent.com/5719851/105747878-33441e00-5ef6-11eb-8153-3a67e2c7cbb8.png)

**Comment by Sunconure11** [comment]
Okay, I think I know the issue, then. But the crashing with brooms I should've already fixed.

Could you send me a crash report, at least? I'll hunt for an alternative LLibrary maven either way. I know of people who probably would know where to look.

**Comment by WalrusSoup** [comment]
It does look like you fixed the broom issue. Pack is behind a few revisions. Is using: `bewitchment-1.12.2-0.0.22.49.jar`  instead of `22.58`

Will wait for updates on the maven issue.

**Comment by Sunconure11** [comment]
Try now.

**Comment by Sunconure11** [comment]
Mod is using LLibrary so that Mowzie's Mobs (primarily so I can test the cross compat) boots up properly in test environments. Please make sure you can run a game with this.

**Comment by WalrusSoup** [comment]
`BUILD SUCCESSFUL in 1m 45s`

Able to run it without issue and see all the items and indeed, the broom works. Thanks a ton
