### ISSUE TITLE
Battle of the Broom Bugs: A Potential Hope

### ISSUE THREAD

**Issue by mxnmnm** [Um-Mitternacht/Bewitchment#706]
### Expected Behavior
Broom bugs to die after getting stabbed 37 times in the chest

### Actual Behavior
The broom bugs died but then came back to life in a zombified version

### Steps to Reproduce
So the usual dismount bug happens much less often, but it still happens (I think the faster the broom the more likely but I could be wrong). You can usually get it to work by going to the top of the map and going all the way down but it seems to be inconsistent so for repeatability that's the best you're gonna get.

There was another bug that froze my game but it left information in the log, so you'll find a link below

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
0.0.22.61
14.23.5.2854
1.0-23.6
1.5.2

### Screenshots encouraged
An interesting thing about the dismount bug is that I can actually see it with the one probe when it's erroring out vs before when you couldn't at all. Not sure how useful this fact is but figured I'd give you everything I noticed
![2021-02-21_01 06 01](https://user-images.githubusercontent.com/8508976/108621712-1ca3c080-73e9-11eb-8e4b-44982a9a0acf.png)

### Logs, in the event of a crash

https://gist.github.com/mxnmnm/ae26dec78c485e141e6d34cd0fb8c8ad

I know it looks hopeless, but I found something that might help :)
https://github.com/daedalus4096/ThaumicWonders/blob/master/src/main/java/com/verdantartifice/thaumicwonders/common/entities/EntityFlyingCarpet.java

**Comment by Sunconure11** [comment]
I’ll take a look at it. Way overslept.

**Comment by Sunconure11** [comment]
Not gonna look into this further, plus it has been fixed on 1.16.
