### ISSUE TITLE
Check if ovens GUI works in multiplayer

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#71]

**Comment by OtisGoodman** [comment]
is this still a current bug?

**Comment by zabi94** [comment]
Probably, yes

**Comment by OtisGoodman** [comment]
Well then, I will take a look later today.

**Comment by zabi94** [comment]
Actually, since there was a performance problem, it might have been fixed by commits from
36044c83081a0bd56035535b45b4cfe02c1802d3 to dd6085470e967d831a9bf203f0e194a2792c4819. Fix needs to be verified though

**Comment by OtisGoodman** [comment]
I will set up a mini server

**Comment by OtisGoodman** [comment]
rip can't get it working going to need to use the quackcraft test server which I will need to talk with my team first.
