### ISSUE TITLE
Familiar names are not showing up on the creation of a familiar

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#75]

**Comment by OtisGoodman** [comment]
I am on it.

**Comment by OtisGoodman** [comment]
where is the code that is supposed to run when a familiar is created?
I just see the names.

**Comment by zabi94** [comment]
EntityFamiliar

**Comment by OtisGoodman** [comment]
ok

**Comment by OtisGoodman** [comment]
oh crap forgot

**Comment by zabi94** [comment]
Technically, familiars cannot be bound yet, and still have to be implemented
