### ISSUE TITLE
Cauldron bubbles look like squares

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#76]

**Comment by zabi94** [comment]
Is albedo, optifine or any other visually intrusive mod installed when this bug manifests? With just bw I can't seem to reproduce the problen

**Comment by Sunconure11** [comment]
This was spotted on the server while filming the teaser, which did have albedo.

**Comment by Sunconure11** [comment]
I'm not sure if this issue still exists.
