### ISSUE TITLE
Oven producing no wood ash or fume.

### ISSUE THREAD

**Issue by Placid-Storm** [Um-Mitternacht/Bewitchment#8]
### Expected Behavior
Oak saplings in Oven gives wood ash and Exhale of the Horned One.

### Actual Behavior
I got Wood Ash and Exhale of the horned one, one time. Then it promptly disappeared from my inventory.

### Steps to Reproduce
I just loaded the oven with glass jars coal and oak saplings.

### Version of Minecraft, Bewitchment, Forge, Craftstudio API, and Baubles.
Minecraft 1.12.2, Bewitchment 0.7.1, Forge 14.23.1.2555, Craftstudio API none, Baubles 1.5.2

**Comment by Sunconure11** [comment]
That build isn't supported, it was more of a test build for me to see if travis is working with my refactoring. I do not believe this issue even still exists anymore.

**Comment by Placid-Storm** [comment]
Ok, thought I had the latest version I just downloaded it today.
