### ISSUE TITLE
Brews do not show up in creative if they have no recipes

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#81]

**Comment by zabi94** [comment]
Do you have an example ready?

**Comment by Sunconure11** [comment]
None at the moment, since all of them have recipes

**Comment by zabi94** [comment]
That's normal, actually. Brews are a type of potion that can only be obtained through the cauldron. If you can't get them through the cauldron it means they were never registered as brews in the first place, as the method to do so is to provide a recipe
