### ISSUE TITLE
Ravens run in circles

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#87]
https://www.youtube.com/watch?v=mRuQh1p2bPs&feature=youtu.be

**Comment by 63502** [comment]
Nice meme.

ANTICIPATION INTENSIFIES.

**Comment by zabi94** [comment]
Is the model or texture broken?

**Comment by Sunconure11** [comment]
Animation, they suffer from the same issue owls used to

**Comment by zabi94** [comment]
Can you change the issue with a more descriptive title? The video makes it look like the "running in circles" AI is the problem

**Comment by Ingoleth** [comment]
Yup, I was going to say that... Ninja'd, I guess...
