### ISSUE TITLE
Glass Bottles should be returned if they are used as an ingredient in a brew

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#95]
Venom would be an example of this

**Comment by Sunconure11** [comment]
Add clay bottles to this, as well

**Comment by mser7** [comment]
How about, you can eitherl right click the cauldron with the stuff, or throw it in, and you only get the bottle back if you right click

**Comment by zabi94** [comment]
I think this would only make the thing inconsistent. I'll just make it so that it spits out the container item, if the stack thrown in has one
