### ISSUE TITLE
Yew Broom leaves behind "phantom" when dismounting

### ISSUE THREAD

**Issue by RoyaII** [Um-Mitternacht/Bewitchment#97]
### Expected Behavior
Broom shouldn't leave behind a phantom

### Actual Behavior
It does it anyway, though relogging fixes it

### Steps to Reproduce
Mount yew broom, dismount yew broom

### Version of Minecraft, Bewitchment, Forge, and Baubles
MC 1.12.2, BW 0.0.15, Forge 8.0.99.99, Baubles 1.5.2

### Screenshots encouraged
N/A

### Logs, in the event of a crash
N/A

**Comment by Sunconure11** [comment]
Does this still exist?
