### ISSUE TITLE
Various textural notes

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#99]
three other blocks in the mod that could go with chisel variants, provided new textures are done

scorned brick - the color pattern was based off of bricks found in wayne barlowe's depictions of hell (https://waynebarlowe.com/artwork/hell/)

embittered brick - basically an opposite of scorned brick, albeit made from ice as opposed to nether materials.

coquina - needs a new texture, and maybe some new chisel variants. look at spanish forts for possible ideas for how to texture the chisel variants, since some were literally made out of them, at least, in their colonies. (https://en.wikipedia.org/wiki/Castillo_de_San_Marcos)

nethersteel could maybe do with new textures just so we can apply chisel variants

kenaf needs new textures as a whole

**Comment by Sunconure11** [comment]
various seeds probably need new textures

**Comment by zabi94** [comment]
Why not add them to #56?
